"""
Topological layer — core data models.

This module defines the canonical data structures for a DNA origami design.
All models live at the topological layer: they encode strand connectivity and
crossover graph structure.  No geometry is computed here.

Rules:
- Every model is a Pydantic BaseModel and is JSON-serialisable.
- Geometry (nucleotide positions) is computed in geometry.py from these models.
- Physics output never writes back to these models.
"""

from __future__ import annotations

import json
import math
import uuid
from enum import Enum
from typing import Annotated, List, Literal, Optional, Tuple, Union

import numpy as np
from pydantic import BaseModel, Field, field_validator, model_validator


# ── Enumerations ──────────────────────────────────────────────────────────────


class LatticeType(str, Enum):
    """Arrangement of helices within the design."""
    HONEYCOMB = "HONEYCOMB"
    SQUARE = "SQUARE"


class Direction(str, Enum):
    """5′→3′ direction of a domain relative to the helix axis."""
    FORWARD = "FORWARD"   # 5′→3′ in the direction of increasing bp index
    REVERSE = "REVERSE"   # 5′→3′ in the direction of decreasing bp index


class ConnectionType(str, Enum):
    """Chemical nature of an interface point on a Part."""
    BLUNT_END = "BLUNT_END"
    TOEHOLD = "TOEHOLD"
    BIOTIN = "BIOTIN"
    COVALENT = "COVALENT"


_LINKER_HELIX_PREFIX = "__lnk__"


class StrandType(str, Enum):
    """Whether a strand is the scaffold, a staple, or a linker.

    LINKER strands are auto-generated by the Overhang Connections feature to
    represent complementary strands that bridge two overhangs. They live on
    virtual helices prefixed with ``__lnk__`` and are skipped by most pipelines
    (geometry render, scaffold validators, auto-routing tools).
    """
    SCAFFOLD = "scaffold"
    STAPLE = "staple"
    LINKER = "linker"


# ── Primitive types ───────────────────────────────────────────────────────────


class Vec3(BaseModel):
    """3-component vector in nanometres (or dimensionless unit vectors)."""
    x: float
    y: float
    z: float

    def to_array(self) -> np.ndarray:
        return np.array([self.x, self.y, self.z], dtype=float)

    @classmethod
    def from_array(cls, arr: np.ndarray) -> Vec3:
        return cls(x=float(arr[0]), y=float(arr[1]), z=float(arr[2]))


class Mat4x4(BaseModel):
    """Row-major 4×4 homogeneous transform matrix for Part placement."""
    values: List[float] = Field(default_factory=lambda: [
        1, 0, 0, 0,
        0, 1, 0, 0,
        0, 0, 1, 0,
        0, 0, 0, 1,
    ])

    def to_array(self) -> np.ndarray:
        return np.array(self.values, dtype=float).reshape(4, 4)

    @classmethod
    def from_array(cls, arr: np.ndarray) -> Mat4x4:
        return cls(values=[float(v) for v in arr.flatten()])


# ── Core design models ────────────────────────────────────────────────────────


class Helix(BaseModel):
    """
    A single double-stranded DNA helix in the design.

    Axis runs from axis_start to axis_end.  phase_offset is the rotational
    phase (radians) at bp index 0; subsequent nucleotides are offset by
    BDNA_TWIST_PER_BP_RAD per step.

    bp_start is the global bp coordinate of local bp index 0 (axis_start end).
    It defaults to 0 for native NADOC designs.  caDNAno-imported designs may
    have bp_start = 0 with the full caDNAno array length stored in length_bp,
    so that domain start_bp/end_bp values directly match caDNAno bp indices.
    Negative bp_start values are valid for helices that extend in -Z from the
    design's slice-plane origin.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    axis_start: Vec3
    axis_end: Vec3
    phase_offset: float = 0.0   # radians
    twist_per_bp_rad: float = math.radians(34.3)  # radians/bp  (default = B-DNA 34.3°)
    length_bp: int
    bp_start: int = 0           # global bp coordinate of local bp index 0
    loop_skips: List[LoopSkip] = Field(default_factory=list)
    label: Optional[str] = None
    """Display label shown in the pathview gutter (e.g. scadnano helix index).  None = use
    positional index."""
    grid_pos: Optional[Tuple[int, int]] = None
    """(row, col) in the originating lattice grid, when known.  Set by scadnano/caDNAno
    importers so that the crossover lookup table can be used without parsing the helix ID."""
    direction: Optional['Direction'] = None
    """Scaffold-strand direction through this helix (FORWARD or REVERSE).  Set by
    lattice/importer code; None for helices created without lattice context."""
    """
    Loop (+1) and skip (-1) modifications for this helix.

    Keyed by absolute bp index within the helix. The list may contain at most
    one entry per bp index. Entries must be sorted by bp_index ascending.
    Modifications affect both strands at the given bp position.
    See LoopSkip for the physical mechanism.
    """

    @model_validator(mode='after')
    def _recover_grid_pos(self) -> 'Helix':
        """Back-fill grid_pos from the h_XY_{r}_{c} ID pattern for legacy files."""
        import re
        if self.grid_pos is None:
            m = re.fullmatch(r'h_XY_(-?\d+)_(-?\d+)', self.id)
            if m:
                self.grid_pos = (int(m.group(1)), int(m.group(2)))
        return self


class LoopSkip(BaseModel):
    """
    A single-base insertion (loop, delta=+1) or deletion (skip, delta=-1)
    at a specific bp position within a helix.

    Stored at the helix level so both strands share the same modification,
    mirroring the caDNAno convention where a loop/skip at position bp_index
    affects the double-stranded column at that index.

    delta values:
        -1 : skip (deletion) — one bp absent; crossover planes see a shorter
             local segment → locally overtwisted → left-handed torque + pull.
        +1 : loop (insertion) — one extra bp present; locally undertwisted
             → right-handed torque + push.

    Values outside {-1, +1} are not used.  Multiple modifications at adjacent
    bp positions are represented as separate LoopSkip entries.

    Reference: Dietz, Douglas & Shih, Science 2009.
    """
    bp_index: int     # absolute bp index within the helix (0-based)
    delta: int        # +1 = loop (insertion), -1 = skip (deletion)


class OverhangSpec(BaseModel):
    """
    Metadata for a single-stranded overhang domain.

    Overhangs are staple domains that extend beyond the double-stranded bundle
    and are therefore single-stranded.  Each overhang may carry an optional
    user-specified sequence (e.g. for toehold-mediated strand displacement).
    If sequence is None, assign_staple_sequences() fills the domain with 'N'.

    id format: ``ovhg_{source_helix_id}_{bp_index}_{5p|3p}``

    rotation is a unit quaternion [x, y, z, w] (Three.js/scipy convention)
    describing a ball-joint rotation of the overhang helix around pivot.
    Identity [0,0,0,1] means no rotation (default lattice-neighbour direction).

    pivot is the world-space axis-point at the crossover junction (nm).
    Computed once at extrude time and fixed thereafter.
    """
    id: str
    helix_id: str           # the overhang helix ID
    strand_id: str          # the parent staple strand ID
    sequence: Optional[str] = None
    label: Optional[str] = None
    rotation: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0, 1.0])
    pivot: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])


class OverhangConnection(BaseModel):
    """
    Metadata-only record describing a logical linker between two overhangs.

    Does NOT modify strand topology — purely a user-defined annotation that
    travels with the design. Strand-generation from this metadata is deferred.

    overhang_*_attach: which end of each overhang the linker attaches to.
      "root"     — embedded end on the main bundle helix.
      "free_end" — protruding 5'/3' tip on the overhang helix.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: Optional[str] = None
    overhang_a_id: str
    overhang_a_attach: Literal["root", "free_end"]
    overhang_b_id: str
    overhang_b_attach: Literal["root", "free_end"]
    linker_type: Literal["ss", "ds"]
    length_value: float
    length_unit: Literal["bp", "nm"]


class Domain(BaseModel):
    """
    A contiguous run of nucleotides on one helix belonging to one strand.

    start_bp and end_bp are inclusive bp indices (0-based) within the helix.
    direction indicates whether the strand travels in the +axis or -axis
    direction through this domain.
    """
    helix_id: str
    start_bp: int
    end_bp: int
    direction: Direction
    overhang_id: Optional[str] = None  # set if this domain is a single-stranded overhang


class Strand(BaseModel):
    """
    A single DNA strand, ordered 5′ to 3′ through its domains.

    Scaffold strands are marked strand_type=StrandType.SCAFFOLD; there should
    be exactly one per design.  sequence, if provided, must have length equal
    to the total number of nucleotides in all domains.

    color, if set, is a 6-digit hex string (e.g. "#F7931E") overriding the
    default STAPLE_PALETTE assignment.  Preserved on caDNAno import/export.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    domains: List[Domain] = Field(default_factory=list)
    strand_type: StrandType = StrandType.STAPLE
    sequence: Optional[str] = None
    color: Optional[str] = None   # "#RRGGBB" hex; None → use STAPLE_PALETTE
    notes: Optional[str] = None   # user-defined notes (shown in spreadsheet panel)

    @model_validator(mode='before')
    @classmethod
    def _migrate_is_scaffold(cls, data: object) -> object:
        """Migrate old is_scaffold boolean field from pre-StrandType .nadoc files."""
        if isinstance(data, dict) and 'is_scaffold' in data and 'strand_type' not in data:
            data = dict(data)
            data['strand_type'] = 'scaffold' if data.pop('is_scaffold') else 'staple'
        return data

    @field_validator('domains', mode='before')
    @classmethod
    def _drop_null_domains(cls, v: object) -> object:
        """Strip null entries that corrupt files may contain."""
        if isinstance(v, list):
            return [d for d in v if d is not None]
        return v


class PhotoproductJunction(BaseModel):
    """
    A confirmed CPD (cyclobutane pyrimidine dimer) photoproduct site imported
    from a scadnano_cpd design.  Stores the two thymine stable-IDs and the
    photoproduct type.  Not rendered by NADOC yet — preserved for future use.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    t1_stable_id: str
    t2_stable_id: str
    photoproduct_id: str = "TT-CPD"


# ── Crossover models ──────────────────────────────────────────────────────────


class HalfCrossover(BaseModel):
    """One endpoint of a crossover: a (helix, bp_index, strand) slot.

    On its own it is an open/dangling strand end.  When paired with a matching
    HalfCrossover on a neighboring helix at the same index, it forms a full
    Crossover.
    """
    helix_id: str
    index: int        # global bp index — identical on both sides of a crossover
    strand: Direction # FORWARD or REVERSE


class Crossover(BaseModel):
    """A bidirectional link between two HalfCrossover slots on neighboring helices.

    Both halves must share the same bp index.  The two helices must be
    adjacent in the lattice.  Stored in Design.crossovers; the corresponding
    cross-helix domain transition is also reflected in Design.strands.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    half_a: HalfCrossover
    half_b: HalfCrossover
    extra_bases: Optional[str] = None  # e.g. "TT" — single-stranded bases at the junction
    process_id: Optional[str] = None  # operation that placed this crossover, e.g. "manual", "auto_crossover"


class ForcedLigation(BaseModel):
    """Records a manually forced ligation between two strand ends.

    Stored on the Design so that auto_scaffold can detect and preserve
    scaffold strands that contain these connections.  Each record stores
    the 3' and 5' endpoints (helix, bp, direction) at the time of ligation.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    three_prime_helix_id: str
    three_prime_bp: int
    three_prime_direction: Direction
    five_prime_helix_id: str
    five_prime_bp: int
    five_prime_direction: Direction
    extra_bases: Optional[str] = None  # e.g. "TT" — single-stranded bases at the junction


# ── Terminal extension models ─────────────────────────────────────────────────


MODIFICATION_COLORS: dict[str, str] = {
    "cy3":     "#ff8c00",
    "cy5":     "#cc0000",
    "fam":     "#00cc00",
    "tamra":   "#cc00cc",
    "bhq1":    "#444444",
    "bhq2":    "#666666",
    "atto488": "#00ffcc",
    "atto550": "#ffaa00",
    "biotin":  "#eeeeee",
}
VALID_MODIFICATIONS = frozenset(MODIFICATION_COLORS.keys())


class StrandExtension(BaseModel):
    """
    A terminal extension on a strand's 5′ or 3′ end.

    At least one of sequence or modification must be provided.
    sequence: ACGTN bases, e.g. "TTTT"
    modification: predefined key from VALID_MODIFICATIONS, e.g. "cy3"

    The geometry layer places beads along a quadratic Bézier arc extending
    radially outward from the terminal nucleotide in XY, with a +Z bow.
    Uses synthetic helix_id ``__ext_{id}``.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    strand_id: str
    end: Literal["five_prime", "three_prime"]
    sequence: Optional[str] = None      # ACGTN; None if modification-only
    modification: Optional[str] = None  # key from VALID_MODIFICATIONS
    label: Optional[str] = None

    @model_validator(mode='after')
    def _check_not_both_none(self) -> 'StrandExtension':
        if self.sequence is None and self.modification is None:
            raise ValueError("At least one of sequence or modification must be provided.")
        return self


# ── Deformation models (geometric layer, Phase 6) ─────────────────────────────


class TwistParams(BaseModel):
    """Parameters for a twist deformation segment."""
    kind: Literal['twist'] = 'twist'
    total_degrees: Optional[float] = None    # mutually exclusive with degrees_per_nm
    degrees_per_nm: Optional[float] = None   # positive = right-handed, negative = left-handed


class BendParams(BaseModel):
    """Parameters for a bend deformation segment."""
    kind: Literal['bend'] = 'bend'
    angle_deg: float = 0.0          # total arc angle between plane A and plane B; 0 = straight
    direction_deg: float = 0.0      # 0 = +X in the bundle cross-section plane


class DeformationOp(BaseModel):
    """One twist or bend applied to a segment of the bundle."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    type: Literal['twist', 'bend']
    plane_a_bp: int                  # fixed plane (5′ side); must be < plane_b_bp
    plane_b_bp: int                  # mobile plane (3′ side)
    affected_helix_ids: List[str] = Field(default_factory=list)
    cluster_id: Optional[str] = None  # cluster this deformation was scoped to (display only)
    params: Annotated[Union[TwistParams, BendParams], Field(discriminator='kind')]


class DomainRef(BaseModel):
    """Reference to a single domain within a strand (strand_id + domain_index)."""
    strand_id: str
    domain_index: int


class ClusterRigidTransform(BaseModel):
    """
    A named cluster of helices (or sub-helix domains) with a persistent
    rigid-body transform.

    The transform is applied AFTER all bend/twist DeformationOps, as a
    per-helix post-step rigid displacement.

    rotation is a unit quaternion [x, y, z, w] (Three.js / scipy convention).
    translation is in nanometres.
    pivot is the world-space centroid of the cluster's deformed bounding box
    at the time the cluster was last activated; used as the rotation centre.

    When domain_ids is non-empty, only the nucleotides belonging to those
    domains are transformed; helix_ids still lists the helices involved (for
    pivot computation and backward compatibility) but the transform is applied
    at domain granularity.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Cluster"
    is_default: bool = False          # True when auto-created to contain all helices
    helix_ids: List[str] = Field(default_factory=list)
    domain_ids: List[DomainRef] = Field(default_factory=list)
    translation: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
    rotation: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0, 1.0])
    pivot: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])


class ClusterJoint(BaseModel):
    """
    A revolute (rotational) joint axis defined on a cluster.

    The joint axis is a line in world-space defined by axis_origin (any point
    on the axis, in nm) and axis_direction (unit vector along the axis).
    It is derived by approximating the cluster's surface as a lattice-
    appropriate prism and clicking a face; the axis is the face normal at
    that point.

    surface_detail stores the number of lateral faces used in the prism
    approximation at definition time so the slider can be restored.

    joint_type is 'revolute' for now; extend with 'prismatic' later.
    The joint does NOT appear in the feature_log — it is design metadata.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    cluster_id: str
    name: str = "Joint"
    joint_type: Literal['revolute'] = 'revolute'
    axis_origin: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
    axis_direction: List[float] = Field(default_factory=lambda: [0.0, 1.0, 0.0])
    surface_detail: int = 6   # lateral face count; 4 = SQ default, 6 = HC default


class CameraPose(BaseModel):
    """
    A named saved camera viewpoint for animation and presentation purposes.

    Stores the full Three.js camera state so it can be restored exactly.
    position/target/up are in Three.js world space (nanometres).
    orbit_mode matches the viewport control mode at time of capture.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Camera Pose"
    position: List[float] = Field(default_factory=lambda: [6.0, 3.0, 7.0])
    target: List[float] = Field(default_factory=lambda: [0.0, 0.0, 7.0])
    up: List[float] = Field(default_factory=lambda: [0.0, 1.0, 0.0])
    fov: float = 55.0
    orbit_mode: str = "trackball"  # 'trackball' | 'turntable'


class AssemblyInstanceConfigState(BaseModel):
    """Saved per-instance placement for an assembly configuration snapshot."""
    instance_id: str
    name: str = ""
    transform: Mat4x4
    base_transform: Optional[Mat4x4] = None
    joint_states: dict = Field(default_factory=dict)
    cluster_transform_overrides: List[ClusterRigidTransform] = Field(default_factory=list)


class AssemblyJointConfigState(BaseModel):
    """Saved mate/joint state for an assembly configuration snapshot."""
    joint_id: str
    current_value: float = 0.0
    axis_origin: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
    axis_direction: List[float] = Field(default_factory=lambda: [0.0, 0.0, 1.0])


class AssemblyConfigurationSnapshot(BaseModel):
    """
    A named assembly configuration.

    Restoring a configuration updates only instances and joints that still exist;
    parts added after the snapshot was captured are intentionally ignored.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Configuration"
    instance_states: List[AssemblyInstanceConfigState] = Field(default_factory=list)
    joint_states: List[AssemblyJointConfigState] = Field(default_factory=list)


class DeformationLogEntry(BaseModel):
    """Feature log entry for a bend or twist deformation operation."""
    feature_type: Literal['deformation'] = 'deformation'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    deformation_id: str   # references a DeformationOp.id in design.deformations
    op_snapshot: Optional[DeformationOp] = None   # full op data for seek replay


class ClusterOpLogEntry(BaseModel):
    """Feature log entry for a cluster translate/rotate operation."""
    feature_type: Literal['cluster_op'] = 'cluster_op'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    cluster_id: str
    translation: List[float]   # absolute cluster state AFTER this op
    rotation: List[float]      # [qx, qy, qz, qw]
    pivot: List[float]


class OverhangRotationLogEntry(BaseModel):
    """Feature log entry for one or more overhang orientation changes applied as a batch."""
    feature_type: Literal['overhang_rotation'] = 'overhang_rotation'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    overhang_ids: List[str]
    rotations: List[List[float]]   # [qx, qy, qz, qw] per overhang_id (parallel list)
    labels: List[Optional[str]] = []


# Auto-op kinds that emit a SnapshotLogEntry. Keep in sync with state.mutate_with_feature_log
# call sites in backend/api/crud.py.
#
# `bundle-create` is the "fresh start" endpoint: it resets to an empty design
# before running, so its pre-state is an empty Design and seeking to F0 always
# yields an empty workspace.
#
# `extrude-*` are continuation/segment ops that grow an existing design.
# `overhang-extrude` adds a single-helix overhang stub from a nick.
SnapshotOpKind = Literal[
    'bundle-create',
    'extrude-segment',
    'extrude-continuation',
    'extrude-deformed-continuation',
    'overhang-extrude',
    'auto-scaffold',
    'auto-scaffold-seamed',
    'auto-scaffold-seamless',
    'auto-break',
    'auto-merge',
    'auto-crossover',
    'create-near-ends',
    'create-far-ends',
    'overhang-bulk',
    'apply-loop-skips',
    'linker-add',
]


class SnapshotLogEntry(BaseModel):
    """Feature log entry for a bulk auto-operation.

    Carries TWO full design snapshots so the op is fully scrubbable even after
    a browser refresh:

    * ``design_snapshot_gz_b64`` — design state IMMEDIATELY BEFORE the op ran.
      Used by ``POST /design/features/{i}/revert`` and by slider-seek when
      seeking BEFORE this entry's position.
    * ``post_state_gz_b64`` — design state IMMEDIATELY AFTER the op ran (and
      cluster reconcile). Used by slider-seek when seeking AT/AFTER this
      entry's position so back-and-forth scrubbing recovers the live topology
      regardless of intervening seeks.

    Both payloads are ``gzip(Design.model_dump_json())`` with the design's own
    ``feature_log`` and ``feature_log_cursor`` stripped before encoding to
    prevent recursive nesting.

    ``evicted=True`` means the bodies were dropped to free space; the entry is
    still visible historically but is no longer revertable or seek-restorable.
    """
    feature_type: Literal['snapshot'] = 'snapshot'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    op_kind: SnapshotOpKind
    label: str
    timestamp: str = ""                  # ISO-8601 UTC, set by mutate_with_feature_log
    params: dict = Field(default_factory=dict)
    design_snapshot_gz_b64: str = ""     # gzipped JSON of PRE-state design, base64
    snapshot_size_bytes: int = 0         # uncompressed PRE-state JSON byte length
    post_state_gz_b64: str = ""          # gzipped JSON of POST-state design, base64
    post_state_size_bytes: int = 0       # uncompressed POST-state JSON byte length
    evicted: bool = False


# Subtypes of MinorMutationLogEntry — every minor user-driven mutation that
# falls into a Fine Routing cluster. Keep in sync with state.mutate_with_minor_log
# call sites in backend/api/crud.py and the dispatcher _replay_minor_op.
MinorOpSubtype = Literal[
    'strand-end-resize', 'scaffold-domain-paint',
    'crossover-place', 'crossover-place-batch',
    'crossover-move', 'crossover-move-batch',
    'crossover-delete', 'crossover-delete-batch',
    'crossover-extra-bases', 'crossover-extra-bases-batch',
    'nick', 'nick-batch', 'ligate',
    'forced-ligation-create', 'forced-ligation-delete',
    'forced-ligation-delete-batch', 'forced-ligation-extra-bases',
    'helix-add', 'helix-add-at-cell', 'helix-update', 'helix-extend', 'helix-delete',
    'strand-add', 'strand-update', 'strand-delete', 'strand-delete-batch',
    'domain-add', 'domain-delete',
    'loop-skip-insert', 'loop-skip-twist', 'loop-skip-bend',
    'strand-patch', 'strands-color-bulk',
]


class MinorMutationLogEntry(BaseModel):
    """One minor user-driven mutation. Lives ONLY inside RoutingClusterLogEntry.children
    (never at the top level of feature_log). Stores the op_subtype + a JSON-safe
    params dict so the operation can be replayed mid-cluster during slider seek
    via backend.api.crud._replay_minor_op.
    """
    feature_type: Literal['minor'] = 'minor'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    op_subtype: MinorOpSubtype
    label: str          # rendered detail line, e.g. "h_XY_0_0 5' bp 0 → bp 7"
    timestamp: str = ""
    params: dict = Field(default_factory=dict)


class RoutingClusterLogEntry(BaseModel):
    """A 'Fine Routing' cluster grouping consecutive minor mutations.

    A cluster stays open across consecutive minor ops; any snapshot-emitting
    endpoint (auto-op, extrude) implicitly closes it because it appends a
    SnapshotLogEntry, after which the next minor op finds the last entry isn't
    a cluster and opens a fresh one.

    Carries pre+post snapshots like SnapshotLogEntry so:
      - revert restores the design to before the cluster's first child
        (truncating the log).
      - mid-cluster slider seek hydrates pre-state then replays
        children[0..sub_position] via _replay_minor_op.

    ``post_state_gz_b64`` is re-encoded after each child is appended so the
    cluster always has a current post-state for forward seek / latest-state
    queries.

    ``evicted=True`` means the bytes were dropped to free space; the cluster
    entry + children remain visible historically but are no longer revertable
    or seek-restorable.
    """
    feature_type: Literal['routing-cluster'] = 'routing-cluster'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    label: str = 'Fine Routing'
    timestamp: str = ""
    children: List[MinorMutationLogEntry] = Field(default_factory=list)
    pre_state_gz_b64: str = ""
    pre_state_size_bytes: int = 0
    post_state_gz_b64: str = ""
    post_state_size_bytes: int = 0
    evicted: bool = False


FeatureLogEntry = Annotated[
    Union[
        DeformationLogEntry,
        ClusterOpLogEntry,
        OverhangRotationLogEntry,
        SnapshotLogEntry,
        RoutingClusterLogEntry,
    ],
    Field(discriminator='feature_type'),
]


class AnimationKeyframe(BaseModel):
    """
    A single keyframe in a DesignAnimation.

    camera_pose_id: ID of a CameraPose to transition to; None = keep current camera.
    feature_log_index: feature log position to seek to at this keyframe; None = no change.
    hold_duration_s: seconds to hold this state after arriving.
    transition_duration_s: seconds to tween from the previous keyframe into this one.
    easing: interpolation curve for the transition.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    camera_pose_id: Optional[str] = None
    configuration_id: Optional[str] = None  # assembly configuration snapshot id; None = no assembly state change
    feature_log_index: Optional[int] = None  # feature log position to seek to; None = no change
    hold_duration_s: float = 1.0
    transition_duration_s: float = 0.5
    easing: Literal["linear", "ease-in", "ease-out", "ease-in-out"] = "ease-in-out"
    joint_values: dict[str, float] = Field(default_factory=dict)  # assembly joint id → driven value


class DesignAnimation(BaseModel):
    """An ordered sequence of keyframes that can be played back or exported."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Animation"
    fps: int = 30
    loop: bool = False
    keyframes: List[AnimationKeyframe] = Field(default_factory=list)


class DesignMetadata(BaseModel):
    """Freeform metadata attached to a design."""
    name: str = "Untitled"
    description: str = ""
    author: str = ""
    created_at: str = ""
    modified_at: str = ""
    tags: List[str] = Field(default_factory=list)


class Design(BaseModel):
    """
    Top-level design object.  This is the ground truth for a DNA origami
    structure; all geometry and physics are derived from it.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    helices: List[Helix] = Field(default_factory=list)
    strands: List[Strand] = Field(default_factory=list)
    lattice_type: LatticeType = LatticeType.HONEYCOMB
    metadata: DesignMetadata = Field(default_factory=DesignMetadata)
    deformations: List[DeformationOp] = Field(default_factory=list)
    cluster_transforms: List[ClusterRigidTransform] = Field(default_factory=list)
    cluster_joints: List[ClusterJoint] = Field(default_factory=list)
    overhangs: List[OverhangSpec] = Field(default_factory=list)
    overhang_connections: List[OverhangConnection] = Field(default_factory=list)
    extensions: List[StrandExtension] = Field(default_factory=list)
    photoproduct_junctions: List[PhotoproductJunction] = Field(default_factory=list)
    crossovers: List[Crossover] = Field(default_factory=list)
    forced_ligations: List[ForcedLigation] = Field(default_factory=list)
    camera_poses: List[CameraPose] = Field(default_factory=list)
    animations: List[DesignAnimation] = Field(default_factory=list)
    feature_log: List[FeatureLogEntry] = Field(default_factory=list)
    feature_log_cursor: int = -1   # -1 = at end; ≥0 = index of last active entry
    feature_log_sub_cursor: Optional[int] = None
    """Mid-cluster position when ``feature_log_cursor`` indexes a
    RoutingClusterLogEntry. ``None`` = cluster's post-state (all children
    active); ``-2`` = pre-cluster (no children); ``0..M-1`` = first
    sub_cursor+1 children active. Lets the slider thumb land on the
    specific sub-notch the user scrubbed to."""

    @field_validator('feature_log', mode='before')
    @classmethod
    def _drop_checkpoint_entries(cls, v: object) -> object:
        """Strip legacy checkpoint entries (configurations removed) and stray
        top-level ``'minor'`` entries (those should only ever appear inside a
        RoutingClusterLogEntry's children list; a top-level minor would
        indicate a corrupt file or aborted write)."""
        if isinstance(v, list):
            return [
                e for e in v
                if not (isinstance(e, dict) and e.get('feature_type') in ('checkpoint', 'minor'))
            ]
        return v

    @field_validator('strands', mode='after')
    @classmethod
    def _drop_empty_strands(cls, v: list) -> list:
        """Remove strands that have no domains (can occur in corrupt files)."""
        return [s for s in v if s.domains]

    # Convenience accessor — returns the scaffold strand or None.
    def scaffold(self) -> Optional[Strand]:
        for s in self.strands:
            if s.strand_type == StrandType.SCAFFOLD:
                return s
        return None

    def copy_with(self, **overrides: object) -> "Design":
        """Return a shallow copy with specified fields replaced.

        Usage: existing_design.copy_with(helices=new_helices, strands=new_strands)
        All fields not in overrides are carried forward unchanged, including
        extensions, deformations, cluster_transforms, and any future fields.
        """
        return self.model_copy(update=overrides)

    # ── Persistence helpers ───────────────────────────────────────────────

    def to_dict(self) -> dict:
        """Serialise to a plain Python dict (JSON-safe)."""
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: dict) -> Design:
        """Deserialise from a plain Python dict."""
        return cls.model_validate(data)

    def to_json(self, indent: int = 2) -> str:
        """Serialise to a JSON string."""
        return self.model_dump_json(indent=indent)

    @classmethod
    def from_json(cls, text: str) -> Design:
        """Deserialise from a JSON string.

        If the loaded design has an empty crossovers list (files saved before
        the Design.crossovers model was introduced), crossovers are
        back-populated from cross-helix domain transitions in the strand topology.
        This keeps old .nadoc files working correctly without a migration step.
        """
        design = cls.model_validate(json.loads(text))
        if not design.crossovers:
            # Lazy import avoids a circular dependency with crossover_positions.py.
            from backend.core.crossover_positions import extract_crossovers_from_strands  # noqa: PLC0415
            design.crossovers = extract_crossovers_from_strands(design.strands)
        return design


# ── Assembly / parts library models ──────────────────────────────────────────


class InterfacePoint(BaseModel):
    """
    A named connection point on a Part, expressed in the Part's local frame.
    """
    label: str
    position: Vec3
    normal: Vec3
    connection_type: ConnectionType
    cluster_id: Optional[str] = None


class FluctuationEnvelope(BaseModel):
    """
    Optional envelope describing thermal fluctuation of a Part as derived
    from XPBD or oxDNA ensemble data.  Stored as semi-axis lengths (nm) of an
    approximate ellipsoid in the Part's local frame.
    """
    semi_axes: Vec3                  # half-widths in x, y, z (nm)
    source: str = ""                 # e.g. "oxdna_50ns"


class ValidationRecord(BaseModel):
    """Audit trail of external validation runs performed on a Part."""
    oxdna_minimized: bool = False
    cando_run: bool = False
    snupi_run: bool = False
    experimental_validated: bool = False
    notes: str = ""


class Part(BaseModel):
    """
    Export wrapper for the assembly CAD layer.

    A Part wraps a Design with assembly-level metadata: named interface points,
    fluctuation envelope from simulation, and validation audit trail.

    Note: placement (transform) lives on PartInstance, not here.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    design: Design
    interface_points: List[InterfacePoint] = Field(default_factory=list)
    fluctuation_envelope: Optional[FluctuationEnvelope] = None
    validation_record: ValidationRecord = Field(default_factory=ValidationRecord)


# ── Multi-origami assembly models ─────────────────────────────────────────────


class PartSourceInline(BaseModel):
    """Part Design is embedded directly in the assembly file."""
    type: Literal["inline"] = "inline"
    design: Design


class PartSourceFile(BaseModel):
    """Part Design lives in a separate .nadoc file (path relative to assembly file)."""
    type: Literal["file"] = "file"
    path: str                     # relative path to .nadoc file
    sha256: Optional[str] = None  # content hash for verification; None = unverified


PartSource = Annotated[
    Union[PartSourceInline, PartSourceFile],
    Field(discriminator="type"),
]


class PartInstance(BaseModel):
    """
    One placed occurrence of a Part in an Assembly.

    transform: SE3 expressed as a row-major 4×4 matrix (Mat4x4).
    Transforms the Part's local-frame axis_start/axis_end into assembly world-space.
    NOTE: Three.js Matrix4.fromArray() is column-major — always transpose when
    crossing the JS boundary.

    base_transform: snapshot of transform at joint current_value=0, set when a
    joint is first attached.  Used by the joint drive computation to avoid
    accumulation errors across repeated PATCH calls.

    mode:
      "rigid"    — Part treated as a single rigid body; internal ClusterJoints frozen.
      "flexible" — Internal ClusterJoints active; compose with assembly-level joints.

    joint_states: current driven angle/displacement for each ClusterJoint in the
    source design (joint_id → float in radians or nm). Only used when mode="flexible".

    cluster_transform_overrides: per-instance overrides for cluster positions
    (equivalent to Design.cluster_transforms, scoped to this instance).
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Part"
    source: PartSource
    transform: Mat4x4 = Field(default_factory=Mat4x4)
    base_transform: Optional[Mat4x4] = None
    mode: Literal["rigid", "flexible"] = "flexible"
    visible: bool = True
    representation: Literal['full', 'beads', 'cylinders', 'vdw', 'ballstick', 'hull-prism'] = 'full'
    fixed: bool = False   # anchored in assembly; not moved by joint constraint solving
    allow_part_joints: bool = False  # enable interactive internal ClusterJoints in assembly mode
    joint_states: dict = Field(default_factory=dict)  # ClusterJoint.id → float (rad|nm)
    cluster_transform_overrides: List[ClusterRigidTransform] = Field(default_factory=list)
    interface_points: List[InterfacePoint] = Field(default_factory=list)


class AssemblyJoint(BaseModel):
    """
    A kinematic joint connecting two PartInstances in an Assembly.

    instance_a_id: "parent" body; None = world/ground frame.
    instance_b_id: "child" body constrained relative to instance_a.

    cluster_id_a / cluster_id_b: optional sub-cluster on each instance that the
    joint axis references (e.g. the end of a multi-cluster arm).

    axis_origin / axis_direction: in assembly world-space at current_value=0.

    current_value: driven DOF value (radians for revolute, nm for prismatic).
    Stored here for persistence and animation interpolation.

    base_transform on instance_b is set when this joint is first created, and is
    used by the backend to compute instance_b.transform without accumulation error.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Joint"
    joint_type: Literal["revolute", "prismatic", "spherical", "rigid"] = "revolute"
    instance_a_id: Optional[str] = None   # None = ground
    cluster_id_a:  Optional[str] = None
    instance_b_id: str
    cluster_id_b:  Optional[str] = None
    axis_origin:    List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
    axis_direction: List[float] = Field(default_factory=lambda: [0.0, 0.0, 1.0])
    current_value:  float = 0.0
    min_limit: Optional[float] = None
    max_limit: Optional[float] = None
    connector_a_label: Optional[str] = None   # label of instance_a's InterfacePoint used in this mate
    connector_b_label: Optional[str] = None   # label of instance_b's InterfacePoint used in this mate


class PartLibraryEntry(BaseModel):
    """Registry entry for a known .nadoc file in the part library."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    path: str       # absolute or relative path to the .nadoc file
    sha256: str     # SHA-256 hex digest of file contents at scan time
    interface_points: List[InterfacePoint] = Field(default_factory=list)
    tags: List[str] = Field(default_factory=list)


class PartLibrary(BaseModel):
    """User's local library of available Part files."""
    entries: List[PartLibraryEntry] = Field(default_factory=list)


class Assembly(BaseModel):
    """
    A multi-origami assembly.

    Contains PartInstances (each wrapping a Design with a placement transform)
    and AssemblyJoints that define kinematic constraints between instances.

    assembly_helices / assembly_strands: helices and strands that exist at the
    assembly level (e.g. linker strands connecting two Parts, or virtual scaffold
    connections rendered as dashed lines).  Virtual scaffold connections are
    strands with strand_type=SCAFFOLD and id prefix "__vsc__".

    feature_log: undo/redo trail for assembly-level operations only.
    Each Part's own feature_log is separate and unaffected by assembly ops.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    metadata: DesignMetadata = Field(default_factory=DesignMetadata)
    instances: List[PartInstance] = Field(default_factory=list)
    joints: List[AssemblyJoint] = Field(default_factory=list)
    assembly_helices: List[Helix] = Field(default_factory=list)
    assembly_strands: List[Strand] = Field(default_factory=list)
    camera_poses: List[CameraPose] = Field(default_factory=list)
    animations: List[DesignAnimation] = Field(default_factory=list)
    configurations: List[AssemblyConfigurationSnapshot] = Field(default_factory=list)
    configuration_cursor: Optional[str] = None
    feature_log: List[FeatureLogEntry] = Field(default_factory=list)
    feature_log_cursor: int = -1

    def to_dict(self) -> dict:
        """Serialise to a plain Python dict (JSON-safe)."""
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: dict) -> "Assembly":
        """Deserialise from a plain Python dict."""
        return cls.model_validate(data)

    @classmethod
    def from_json(cls, text: str) -> "Assembly":
        """Deserialise from a JSON string."""
        return cls.model_validate(json.loads(text))

    def to_json(self, indent: int = 2) -> str:
        """Serialise to a JSON string."""
        return self.model_dump_json(indent=indent)
