"""
Topological layer — core data models.

This module defines the canonical data structures for a DNA origami design.
All models live at the topological layer: they encode strand connectivity and
crossover graph structure.  No geometry is computed here.

Rules:
- Every model is a Pydantic BaseModel and is JSON-serialisable.
- Geometry (nucleotide positions) is computed in geometry.py from these models.
- Physics output never writes back to these models.
"""

from __future__ import annotations

import json
import math
import time
import uuid
from enum import Enum
from typing import Annotated, Any, Dict, List, Literal, Optional, Tuple, Union

import numpy as np
from pydantic import BaseModel, Field, field_validator, model_validator


# ── Enumerations ──────────────────────────────────────────────────────────────


class LatticeType(str, Enum):
    """Arrangement of helices within the design."""
    HONEYCOMB = "HONEYCOMB"
    SQUARE = "SQUARE"


class Direction(str, Enum):
    """5′→3′ direction of a domain relative to the helix axis."""
    FORWARD = "FORWARD"   # 5′→3′ in the direction of increasing bp index
    REVERSE = "REVERSE"   # 5′→3′ in the direction of decreasing bp index


class ConnectionType(str, Enum):
    """Chemical nature of an interface point on a Part."""
    BLUNT_END = "BLUNT_END"
    TOEHOLD = "TOEHOLD"
    BIOTIN = "BIOTIN"
    COVALENT = "COVALENT"


_LINKER_HELIX_PREFIX = "__lnk__"


class StrandType(str, Enum):
    """Whether a strand is the scaffold, a staple, or a linker.

    LINKER strands are auto-generated by the Overhang Connections feature to
    represent complementary strands that bridge two overhangs. They live on
    virtual helices prefixed with ``__lnk__`` and are skipped by most pipelines
    (geometry render, scaffold validators, auto-routing tools).
    """
    SCAFFOLD = "scaffold"
    STAPLE = "staple"
    LINKER = "linker"


# ── Primitive types ───────────────────────────────────────────────────────────


class Vec3(BaseModel):
    """3-component vector in nanometres (or dimensionless unit vectors)."""
    x: float
    y: float
    z: float

    def to_array(self) -> np.ndarray:
        return np.array([self.x, self.y, self.z], dtype=float)

    @classmethod
    def from_array(cls, arr: np.ndarray) -> Vec3:
        return cls(x=float(arr[0]), y=float(arr[1]), z=float(arr[2]))


class Mat4x4(BaseModel):
    """Row-major 4×4 homogeneous transform matrix for Part placement."""
    values: List[float] = Field(default_factory=lambda: [
        1, 0, 0, 0,
        0, 1, 0, 0,
        0, 0, 1, 0,
        0, 0, 0, 1,
    ])

    def to_array(self) -> np.ndarray:
        return np.array(self.values, dtype=float).reshape(4, 4)

    @classmethod
    def from_array(cls, arr: np.ndarray) -> Mat4x4:
        return cls(values=[float(v) for v in arr.flatten()])


# ── Core design models ────────────────────────────────────────────────────────


class Helix(BaseModel):
    """
    A single double-stranded DNA helix in the design.

    Axis runs from axis_start to axis_end.  phase_offset is the rotational
    phase (radians) at bp index 0; subsequent nucleotides are offset by
    BDNA_TWIST_PER_BP_RAD per step.

    bp_start is the global bp coordinate of local bp index 0 (axis_start end).
    It defaults to 0 for native NADOC designs.  caDNAno-imported designs may
    have bp_start = 0 with the full caDNAno array length stored in length_bp,
    so that domain start_bp/end_bp values directly match caDNAno bp indices.
    Negative bp_start values are valid for helices that extend in -Z from the
    design's slice-plane origin.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    axis_start: Vec3
    axis_end: Vec3
    phase_offset: float = 0.0   # radians
    twist_per_bp_rad: float = math.radians(34.3)  # radians/bp  (default = B-DNA 34.3°)
    length_bp: int
    bp_start: int = 0           # global bp coordinate of local bp index 0
    loop_skips: List[LoopSkip] = Field(default_factory=list)
    label: Optional[str] = None
    """Display label shown in the pathview gutter (e.g. scadnano helix index).  None = use
    positional index."""
    grid_pos: Optional[Tuple[int, int]] = None
    """(row, col) in the originating lattice grid, when known.  Set by scadnano/caDNAno
    importers so that the crossover lookup table can be used without parsing the helix ID."""
    direction: Optional['Direction'] = None
    """Scaffold-strand direction through this helix (FORWARD or REVERSE).  Set by
    lattice/importer code; None for helices created without lattice context."""
    """
    Loop (+1) and skip (-1) modifications for this helix.

    Keyed by absolute bp index within the helix. The list may contain at most
    one entry per bp index. Entries must be sorted by bp_index ascending.
    Modifications affect both strands at the given bp position.
    See LoopSkip for the physical mechanism.
    """

    @model_validator(mode='after')
    def _recover_grid_pos(self) -> 'Helix':
        """Back-fill grid_pos from the h_XY_{r}_{c} ID pattern for legacy files."""
        import re
        if self.grid_pos is None:
            m = re.fullmatch(r'h_XY_(-?\d+)_(-?\d+)', self.id)
            if m:
                self.grid_pos = (int(m.group(1)), int(m.group(2)))
        return self


class LoopSkip(BaseModel):
    """
    A single-base insertion (loop, delta=+1) or deletion (skip, delta=-1)
    at a specific bp position within a helix.

    Stored at the helix level so both strands share the same modification,
    mirroring the caDNAno convention where a loop/skip at position bp_index
    affects the double-stranded column at that index.

    delta values:
        -1 : skip (deletion) — one bp absent; crossover planes see a shorter
             local segment → locally overtwisted → left-handed torque + pull.
        +1 : loop (insertion) — one extra bp present; locally undertwisted
             → right-handed torque + push.

    Values outside {-1, +1} are not used.  Multiple modifications at adjacent
    bp positions are represented as separate LoopSkip entries.

    Reference: Dietz, Douglas & Shih, Science 2009.
    """
    bp_index: int     # absolute bp index within the helix (0-based)
    delta: int        # +1 = loop (insertion), -1 = skip (deletion)


# ── Sub-domains (Phase 1, overhang revamp) ───────────────────────────────────
#
# Sub-domains tile an overhang into named, gap-less pieces that may carry their
# own sequence overrides, cached thermodynamic annotations, and (in later phases)
# rotation hints. They are a topological-layer concept: pure metadata on the
# OverhangSpec. Geometry / atomistic / physical layers must not write back here.
#
# Determinism: when a `.nadoc` file is loaded that predates sub-domains, the
# model validator backfills a single whole-overhang sub-domain. Its UUID is a
# UUID5 derived from the parent overhang id so the same id is produced on every
# load — a hard requirement for stable references from cross-design tooling
# (Phase 5+ bindings) and from `.nadoc` round-trips.


NADOC_SUBDOMAIN_NS = uuid.UUID('6f8a8b1e-5b3a-4b1f-8c2a-d0e5b3f1a204')


class SubDomain(BaseModel):
    """A named slice of an overhang.

    Sub-domains tile the parent overhang gap-lessly. ``start_bp_offset`` is
    measured in base pairs from the overhang's 5' end (offset 0 = first base);
    ``length_bp`` covers `length_bp` consecutive bases starting at that offset.

    The sum of ``length_bp`` across an overhang's sub-domains must equal the
    backing domain length. This invariant is enforced by ``_validate_sub_domain_tiling``
    on every mutating endpoint; the ``OverhangSpec`` model validator backfills a
    single whole-overhang sub-domain when ``sub_domains`` is empty.

    ``sequence_override``:
      - ``None`` → assemble from the parent ``OverhangSpec.sequence`` slice.
      - ``str``  → must have length equal to ``length_bp`` and contain only ACGTN.

    The rotation fields are stored but unused in Phase 1; reserved for Phase 2.

    Cached annotations (``tm_celsius``, ``gc_percent``, ``hairpin_warning``,
    ``dimer_warning``) are invalidated whenever this sub-domain's sequence or
    the design-level ``tm_settings`` change.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "a"
    color: Optional[str] = None              # "#RRGGBB" hex, or None to inherit parent strand color
    start_bp_offset: int = 0                 # 0-based from the overhang's 5' end
    length_bp: int = 1                       # gap-less tiling invariant per parent overhang
    sequence_override: Optional[str] = None  # None = use parent slice; len must == length_bp
    rotation_theta_deg: float = 0.0          # parent-relative, 2-DOF; stored but UNUSED in Phase 1
    rotation_phi_deg: float = 0.0
    notes: str = ""
    # ── Cached annotations (invalidated on sequence / tm_settings change) ────
    tm_celsius: Optional[float] = None
    gc_percent: Optional[float] = None
    hairpin_warning: bool = False
    dimer_warning: bool = False


class OverhangSpec(BaseModel):
    """
    Metadata for a single-stranded overhang domain.

    Overhangs are staple domains that extend beyond the double-stranded bundle
    and are therefore single-stranded.  Each overhang may carry an optional
    user-specified sequence (e.g. for toehold-mediated strand displacement).
    If sequence is None, assign_staple_sequences() fills the domain with 'N'.

    id format: ``ovhg_{source_helix_id}_{bp_index}_{5p|3p}``

    rotation is a unit quaternion [x, y, z, w] (Three.js/scipy convention)
    describing a ball-joint rotation of the overhang helix around pivot.
    Identity [0,0,0,1] means no rotation (default lattice-neighbour direction).

    pivot is the world-space axis-point at the crossover junction (nm).
    Computed once at extrude time and fixed thereafter.

    ``sub_domains`` tile the overhang gap-lessly 5'→3'. On load (or model
    validation) of an overhang without sub-domains, the model validator
    backfills a single whole-overhang sub-domain with a deterministic UUID5
    derived from the overhang id so cross-load references are stable. The
    sum-of-length invariant is enforced at the endpoint level because the
    backing domain length lives outside this model.
    """
    id: str
    helix_id: str           # the overhang helix ID
    strand_id: str          # the parent staple strand ID
    sequence: Optional[str] = None
    label: Optional[str] = None
    rotation: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0, 1.0])
    pivot: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
    sub_domains: List[SubDomain] = Field(default_factory=list)

    # Chained-overhang link (Alt A foundation, multi-domain audit 07).
    # ``None`` = bundle-anchored (every overhang today). A non-None value names
    # another OverhangSpec whose free tip this OH is anchored to — together
    # parent/child specs form a chain (tree, no cycles). Per-segment cluster
    # membership and color are achieved via the segment's own helix and strand;
    # no per-domain color field is needed.
    parent_overhang_id: Optional[str] = None

    @model_validator(mode='after')
    def _backfill_whole_overhang_sub_domain(self) -> 'OverhangSpec':
        """Ensure every overhang has at least one sub-domain.

        Idempotent: returns ``self`` unchanged when ``sub_domains`` is non-empty.
        When empty, inserts one whole-overhang sub-domain named ``"a"`` with a
        deterministic UUID5 derived from this overhang's id. The tiling-length
        invariant is enforced at the endpoint level (see
        ``backend.api.crud._validate_sub_domain_tiling``) because the backing
        domain length is not known to this model.
        """
        if self.sub_domains:
            return self
        seq = self.sequence
        whole_len = len(seq) if isinstance(seq, str) and seq else 1
        whole = SubDomain(
            id=str(uuid.uuid5(NADOC_SUBDOMAIN_NS, f"{self.id}:whole")),
            name="a",
            start_bp_offset=0,
            length_bp=whole_len,
            sequence_override=None,
        )
        # Avoid re-triggering the validator: assign directly to the underlying dict.
        object.__setattr__(self, 'sub_domains', [whole])
        return self


class OverhangConnection(BaseModel):
    """
    Metadata-only record describing a logical linker between two overhangs.

    Does NOT modify strand topology — purely a user-defined annotation that
    travels with the design. Strand-generation from this metadata is deferred.

    overhang_*_attach: which end of each overhang the linker attaches to.
      "root"     — embedded end on the main bundle helix.
      "free_end" — protruding 5'/3' tip on the overhang helix.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: Optional[str] = None
    overhang_a_id: str
    overhang_a_attach: Literal["root", "free_end"]
    overhang_b_id: str
    overhang_b_attach: Literal["root", "free_end"]
    linker_type: Literal["ss", "ds"]
    length_value: float
    length_unit: Literal["bp", "nm"]
    # ss linker only: True once the linker config modal has Applied for this
    # connection. The frontend switches the bridge bead chain from a smooth
    # Bezier (default pre-relax) to the chosen FJC pre-baked shape.
    bridge_relaxed: bool = False
    # Bin index into the ssDNA FJC lookup's per-length `bins` array (the
    # binned R_ee histogram emitted by scripts/generate_ssdna_fjc_lookup.py).
    # The chosen bin's `rep_positions` is the rendered chain; its `rep_r_ee_nm`
    # is the target chord that relax optimises joints toward. 0..hist_bins-1.
    bridge_bin_index: int = 0
    # Optional kinematic limits set by the user via the modal's range thumbs
    # on the R_ee histogram. Downstream uses (animation, joint clamp) treat
    # these as the allowed chord range; None means "no explicit limit". The
    # picked snapshot's R_ee is guaranteed to lie inside [min, max].
    bridge_r_ee_min_nm: Optional[float] = None
    bridge_r_ee_max_nm: Optional[float] = None
    # User-supplied bridge sequence (5'→3' on strand `__a` for ds linkers,
    # or strand `__s` for ss linkers). The Connection Types tab's bridge box
    # writes here. The linker table's Sequence column composes the full
    # strand sequence as RC(overhang_a.sequence) + bridge + RC(overhang_b.sequence)
    # so it stays in sync when the user later edits an overhang sequence.
    # On ds linkers, strand `__b`'s bridge is the reverse complement of this.
    # `None` means "no bridge sequence assigned yet" — the table shows N×L
    # placeholders for the bridge portion.
    bridge_sequence: Optional[str] = None


def _resolve_sd_sequence(ovhg: 'OverhangSpec', sd: 'SubDomain') -> Optional[str]:
    """Module-level helper used by Design._validate_overhang_bindings.

    Mirrors backend.api.crud._resolve_sub_domain_sequence (override > parent
    slice). Returns None when nothing is resolvable yet — the binding
    validator skips the WC check in that case.
    """
    if sd.sequence_override:
        return sd.sequence_override.upper()
    if not ovhg.sequence:
        return None
    start = sd.start_bp_offset
    end = start + sd.length_bp
    sl = ovhg.sequence.upper()[start:end]
    if len(sl) < sd.length_bp:
        return None
    return sl


def _sub_domain_at_attach(design: 'Design', overhang_id: str, attach: str) -> Optional[str]:
    """Return the sub-domain id at the overhang's ``attach`` end (5'→3' offset).

    Used to build the mutex pair-set covering both bindings and linker
    OverhangConnection endpoints. Returns None when the overhang isn't
    found or has no sub-domains.
    """
    ovhg = next((o for o in design.overhangs if o.id == overhang_id), None)
    if ovhg is None or not ovhg.sub_domains:
        return None
    sub_doms = sorted(ovhg.sub_domains, key=lambda s: s.start_bp_offset)
    # root = embedded end on the bundle (= 5' end of the overhang strand in
    # this convention); free_end = protruding tip = 3' end. The sub-domain
    # tile at each side is the first / last entry by offset.
    if attach == 'root':
        return sub_doms[0].id
    return sub_doms[-1].id


class OverhangBinding(BaseModel):
    """
    Metadata-only record describing a Watson-Crick binding pairing between two
    sub-domains on different overhangs (Phase 5 of the overhang revamp).

    Bindings live on TOPOLOGY (this file). The geometric / physical layers
    READ binding state to apply kinematic coupling (joint lock-in when bound)
    — they never write back.

    Locked angle semantics
    ----------------------
    When ``bound`` flips to True, the relax solver computes the joint angle
    that brings the bound sub-domains' duplex chord to its B-DNA length, and
    that angle is committed to ``locked_angle_deg``. The associated
    ClusterJoint's ``min_angle_deg`` / ``max_angle_deg`` are then both set to
    ``locked_angle_deg`` (so the joint freezes at the bound pose). The
    binding that owns the lock is termed the *driver*; when multiple bindings
    target the same joint, the driver is the most recently created bound
    binding (tiebreak: lex id). The *first claimant* (earliest binding to
    target the joint, bound or not) snapshots the joint's pre-binding angle
    window into ``prior_min_angle_deg`` / ``prior_max_angle_deg`` so the
    window can be restored when the last bound claimant releases.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str                           # auto B1, B2, ...
    created_at: float = Field(default_factory=time.time)  # tiebreak among bound bindings
    sub_domain_a_id: str
    sub_domain_b_id: str
    overhang_a_id: str                  # denormalized for fast cross-ref filter
    overhang_b_id: str
    bound: bool = False
    binding_mode: Literal['duplex', 'toehold'] = 'duplex'
    target_joint_id: Optional[str] = None
    locked_angle_deg: Optional[float] = None
    prior_min_angle_deg: Optional[float] = None  # snapshot taken by the first claimant
    prior_max_angle_deg: Optional[float] = None
    allow_n_wildcard: bool = True
    # Phase-6: snapshot of the driven side's pre-bind topology so unbind can
    # restore the driven helix + the OH's strand domain. Populated when bind
    # relocates the driven OH's domain onto the driver's helix (sharing the
    # same bp range, antiparallel direction — mirrors the linker complement-
    # domain pattern). On unbind, the snapshot is used to recreate the driven
    # helix and rewrite the OH's domain back. Cleared after restore.
    #
    # Shape: {
    #   "driver_oh_id":     str,
    #   "driven_oh_id":     str,
    #   "driven_helix":     <Helix.to_dict() snapshot>,
    #   "strand_id":        str,
    #   "domain_index":     int,
    #   "prior_domain":     {helix_id, start_bp, end_bp, direction},
    #   "prior_ovhg_helix_id": str,
    #   "crossovers":       [<Crossover.to_dict()>, ...]  # ones that referenced the driven helix
    # }
    prior_driven_topology: Optional[Dict[str, Any]] = None

    @model_validator(mode='after')
    def _check_self_consistency(self) -> 'OverhangBinding':
        if self.sub_domain_a_id == self.sub_domain_b_id:
            raise ValueError(
                f"OverhangBinding {self.id}: sub_domain_a_id and "
                f"sub_domain_b_id must differ (no self-binding)."
            )
        # Phase-6: bound=True imposes no further field requirements. The
        # topology relocation alone defines the bound state. The
        # target_joint_id / locked_angle_deg pair is set by the bind-
        # relax step when a crossover record exists for the OH→parent
        # bond; otherwise both stay None and only the topology change is
        # applied.
        return self


class AssemblyOverhangConnection(BaseModel):
    """
    Cross-part overhang connection (linker) between two PartInstances.

    Mirrors :class:`OverhangConnection` but with PartInstance qualification
    on each side. Metadata-only — does NOT modify strand topology in either
    part. The frontend's CT tab uses these rows alongside
    :class:`AssemblyOverhangBinding` (direct WC pairs) to populate the
    assembly-level connections table.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: Optional[str] = None
    created_at: float = Field(default_factory=time.time)
    instance_a_id: str
    overhang_a_id: str
    overhang_a_attach: Literal["root", "free_end"]
    instance_b_id: str
    overhang_b_id: str
    overhang_b_attach: Literal["root", "free_end"]
    linker_type: Literal["ss", "ds"]
    length_value: float
    length_unit: Literal["bp", "nm"]
    bridge_sequence: Optional[str] = None


class AssemblyOverhangBinding(BaseModel):
    """
    Cross-part Watson-Crick pairing between two overhangs on different
    PartInstances within an Assembly.

    Mirrors :class:`OverhangBinding` but with PartInstance qualification on each
    side. v1: pure topology metadata — no geometry application, no joint coupling.
    Lives on Assembly.overhang_bindings.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str                           # auto AB1, AB2, ...
    created_at: float = Field(default_factory=time.time)
    instance_a_id: str                  # PartInstance.id (side A)
    sub_domain_a_id: str
    overhang_a_id: str                  # denormalized for fast lookup
    instance_b_id: str                  # PartInstance.id (side B)
    sub_domain_b_id: str
    overhang_b_id: str
    binding_mode: Literal['duplex', 'toehold'] = 'duplex'
    allow_n_wildcard: bool = True

    @model_validator(mode='after')
    def _check_self_consistency(self) -> 'AssemblyOverhangBinding':
        if (self.instance_a_id == self.instance_b_id and
                self.sub_domain_a_id == self.sub_domain_b_id):
            raise ValueError(
                f"AssemblyOverhangBinding {self.id}: cannot bind a sub-domain "
                f"to itself within the same PartInstance.")
        return self


class Domain(BaseModel):
    """
    A contiguous run of nucleotides on one helix belonging to one strand.

    start_bp and end_bp are inclusive bp indices (0-based) within the helix.
    direction indicates whether the strand travels in the +axis or -axis
    direction through this domain.
    """
    helix_id: str
    start_bp: int
    end_bp: int
    direction: Direction
    overhang_id: Optional[str] = None  # set if this domain is a single-stranded overhang


class Strand(BaseModel):
    """
    A single DNA strand, ordered 5′ to 3′ through its domains.

    Scaffold strands are marked strand_type=StrandType.SCAFFOLD; there should
    be exactly one per design.  sequence, if provided, must have length equal
    to the total number of nucleotides in all domains.

    color, if set, is a 6-digit hex string (e.g. "#F7931E") overriding the
    default STAPLE_PALETTE assignment.  Preserved on caDNAno import/export.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    domains: List[Domain] = Field(default_factory=list)
    strand_type: StrandType = StrandType.STAPLE
    sequence: Optional[str] = None
    color: Optional[str] = None   # "#RRGGBB" hex; None → use STAPLE_PALETTE
    notes: Optional[str] = None   # user-defined notes (shown in spreadsheet panel)

    @model_validator(mode='before')
    @classmethod
    def _migrate_is_scaffold(cls, data: object) -> object:
        """Migrate old is_scaffold boolean field from pre-StrandType .nadoc files."""
        if isinstance(data, dict) and 'is_scaffold' in data and 'strand_type' not in data:
            data = dict(data)
            data['strand_type'] = 'scaffold' if data.pop('is_scaffold') else 'staple'
        return data

    @field_validator('domains', mode='before')
    @classmethod
    def _drop_null_domains(cls, v: object) -> object:
        """Strip null entries that corrupt files may contain."""
        if isinstance(v, list):
            return [d for d in v if d is not None]
        return v

    @property
    def is_scaffold(self) -> bool:
        return self.strand_type == StrandType.SCAFFOLD


class PhotoproductJunction(BaseModel):
    """
    A confirmed CPD (cyclobutane pyrimidine dimer) photoproduct site imported
    from a scadnano_cpd design.  Stores the two thymine stable-IDs and the
    photoproduct type.  Not rendered by NADOC yet — preserved for future use.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    t1_stable_id: str
    t2_stable_id: str
    photoproduct_id: str = "TT-CPD"


# ── Crossover models ──────────────────────────────────────────────────────────


class HalfCrossover(BaseModel):
    """One endpoint of a crossover: a (helix, bp_index, strand) slot.

    On its own it is an open/dangling strand end.  When paired with a matching
    HalfCrossover on a neighboring helix at the same index, it forms a full
    Crossover.
    """
    helix_id: str
    index: int        # global bp index — identical on both sides of a crossover
    strand: Direction # FORWARD or REVERSE


class Crossover(BaseModel):
    """A bidirectional link between two HalfCrossover slots on neighboring helices.

    Both halves must share the same bp index.  The two helices must be
    adjacent in the lattice.  Stored in Design.crossovers; the corresponding
    cross-helix domain transition is also reflected in Design.strands.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    half_a: HalfCrossover
    half_b: HalfCrossover
    extra_bases: Optional[str] = None  # e.g. "TT" — single-stranded bases at the junction
    process_id: Optional[str] = None  # operation that placed this crossover, e.g. "manual", "auto_crossover"


class ForcedLigation(BaseModel):
    """Records a manually forced ligation between two strand ends.

    Stored on the Design so that auto_scaffold can detect and preserve
    scaffold strands that contain these connections.  Each record stores
    the 3' and 5' endpoints (helix, bp, direction) at the time of ligation.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    three_prime_helix_id: str
    three_prime_bp: int
    three_prime_direction: Direction
    five_prime_helix_id: str
    five_prime_bp: int
    five_prime_direction: Direction
    extra_bases: Optional[str] = None  # e.g. "TT" — single-stranded bases at the junction


# ── Terminal extension models ─────────────────────────────────────────────────


MODIFICATION_COLORS: dict[str, str] = {
    "cy3":     "#ff8c00",
    "cy5":     "#cc0000",
    "fam":     "#00cc00",
    "tamra":   "#cc00cc",
    "bhq1":    "#444444",
    "bhq2":    "#666666",
    "atto488": "#00ffcc",
    "atto550": "#ffaa00",
    "biotin":  "#eeeeee",
}
VALID_MODIFICATIONS = frozenset(MODIFICATION_COLORS.keys())


class StrandExtension(BaseModel):
    """
    A terminal extension on a strand's 5′ or 3′ end.

    At least one of sequence or modification must be provided.
    sequence: ACGTN bases, e.g. "TTTT"
    modification: predefined key from VALID_MODIFICATIONS, e.g. "cy3"

    The geometry layer places beads along a quadratic Bézier arc extending
    radially outward from the terminal nucleotide in XY, with a +Z bow.
    Uses synthetic helix_id ``__ext_{id}``.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    strand_id: str
    end: Literal["five_prime", "three_prime"]
    sequence: Optional[str] = None      # ACGTN; None if modification-only
    modification: Optional[str] = None  # key from VALID_MODIFICATIONS
    label: Optional[str] = None

    @model_validator(mode='after')
    def _check_not_both_none(self) -> 'StrandExtension':
        if self.sequence is None and self.modification is None:
            raise ValueError("At least one of sequence or modification must be provided.")
        return self


# ── Deformation models (geometric layer, Phase 6) ─────────────────────────────


class TwistParams(BaseModel):
    """Parameters for a twist deformation segment."""
    kind: Literal['twist'] = 'twist'
    total_degrees: Optional[float] = None    # mutually exclusive with degrees_per_nm
    degrees_per_nm: Optional[float] = None   # positive = right-handed, negative = left-handed


class BendParams(BaseModel):
    """Parameters for a bend deformation segment."""
    kind: Literal['bend'] = 'bend'
    angle_deg: float = 0.0          # total arc angle between plane A and plane B; 0 = straight
    direction_deg: float = 0.0      # 0 = +X in the bundle cross-section plane


class DeformationOp(BaseModel):
    """One twist or bend applied to a segment of the bundle."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    type: Literal['twist', 'bend']
    plane_a_bp: int                  # fixed plane (5′ side); must be < plane_b_bp
    plane_b_bp: int                  # mobile plane (3′ side)
    affected_helix_ids: List[str] = Field(default_factory=list)
    # Clusters this deformation was scoped to. Empty list = unscoped (all crossing helices).
    # When non-empty, affected_helix_ids is filtered to the union of these clusters' helix_ids
    # at creation/edit time, so multiple clusters within a part can be bent or twisted
    # independently — even when their bp ranges overlap.
    cluster_ids: List[str] = Field(default_factory=list)
    params: Annotated[Union[TwistParams, BendParams], Field(discriminator='kind')]


class DomainRef(BaseModel):
    """Reference to a single domain within a strand (strand_id + domain_index)."""
    strand_id: str
    domain_index: int


class ClusterRigidTransform(BaseModel):
    """
    A named cluster of helices (or sub-helix domains) with a persistent
    rigid-body transform.

    The transform is applied AFTER all bend/twist DeformationOps, as a
    per-helix post-step rigid displacement.

    rotation is a unit quaternion [x, y, z, w] (Three.js / scipy convention).
    translation is in nanometres.
    pivot is the world-space centroid of the cluster's deformed bounding box
    at the time the cluster was last activated; used as the rotation centre.

    When domain_ids is non-empty, only the nucleotides belonging to those
    domains are transformed; helix_ids still lists the helices involved (for
    pivot computation and backward compatibility) but the transform is applied
    at domain granularity.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Cluster"
    is_default: bool = False          # True when auto-created to contain all helices
    helix_ids: List[str] = Field(default_factory=list)
    domain_ids: List[DomainRef] = Field(default_factory=list)
    translation: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
    rotation: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0, 1.0])
    pivot: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])


class ClusterJoint(BaseModel):
    """
    A revolute (rotational) joint axis defined on a cluster.

    The joint axis is stored in the cluster's LOCAL frame
    (``local_axis_origin`` / ``local_axis_direction``) — the coordinates
    you'd see if the cluster's transform were the identity. World-space
    axes are derived lazily by composing the cluster's current
    ``cluster_transforms[id]`` with the local axis:

        world_origin = R_cluster · (local_origin - pivot) + pivot + T_cluster
        world_dir    = R_cluster · local_direction

    Storing in local frame eliminates the floating-point drift that the old
    world-space + incremental-update scheme accumulated over many cluster
    transforms (the recompute math is now O(1) regardless of history depth
    and is identical on every read).

    surface_detail stores the number of lateral faces used in the prism
    approximation at definition time so the slider can be restored.

    The joint itself is design metadata; placement / edit / delete events
    are tracked in the feature_log via JointPlacementLogEntry (Phase 3 of
    the joint-storage refactor).
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    cluster_id: str
    name: str = "Joint"
    joint_type: Literal['revolute'] = 'revolute'
    # CLUSTER-LOCAL frame. Set once at creation; never mutated by cluster transforms.
    local_axis_origin:    List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
    local_axis_direction: List[float] = Field(default_factory=lambda: [0.0, 1.0, 0.0])
    surface_detail: int = 6   # lateral face count; 4 = SQ default, 6 = HC default
    # Mechanical rotation limits (degrees). Defaults of [-180°, +180°] are
    # equivalent to "unbounded" for a revolute joint and preserve legacy
    # designs whose .nadoc files predate these fields. Honoured by the
    # linker-relax optimizer, the cluster rotate gizmo (ring drag + numeric
    # input), and the animation player's per-keyframe slerp.
    min_angle_deg: float = -180.0
    max_angle_deg: float =  180.0

    @model_validator(mode='after')
    def _check_angle_range(self) -> 'ClusterJoint':
        if self.max_angle_deg < self.min_angle_deg:
            raise ValueError(
                f"ClusterJoint {self.id}: max_angle_deg ({self.max_angle_deg}) "
                f"must be >= min_angle_deg ({self.min_angle_deg})"
            )
        return self


class CameraPose(BaseModel):
    """
    A named saved camera viewpoint for animation and presentation purposes.

    Stores the full Three.js camera state so it can be restored exactly.
    position/target/up are in Three.js world space (nanometres).
    orbit_mode matches the viewport control mode at time of capture.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Camera Pose"
    position: List[float] = Field(default_factory=lambda: [6.0, 3.0, 7.0])
    target: List[float] = Field(default_factory=lambda: [0.0, 0.0, 7.0])
    up: List[float] = Field(default_factory=lambda: [0.0, 1.0, 0.0])
    fov: float = 55.0
    orbit_mode: str = "trackball"  # 'trackball' | 'turntable'


class AssemblyInstanceConfigState(BaseModel):
    """Saved per-instance placement for an assembly configuration snapshot."""
    instance_id: str
    name: str = ""
    transform: Mat4x4
    base_transform: Optional[Mat4x4] = None
    joint_states: dict = Field(default_factory=dict)
    cluster_transform_overrides: List[ClusterRigidTransform] = Field(default_factory=list)


class AssemblyJointConfigState(BaseModel):
    """Saved mate/joint state for an assembly configuration snapshot."""
    joint_id: str
    current_value: float = 0.0
    axis_origin: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
    axis_direction: List[float] = Field(default_factory=lambda: [0.0, 0.0, 1.0])


class AssemblyConfigurationSnapshot(BaseModel):
    """
    A named assembly configuration.

    Restoring a configuration updates only instances and joints that still exist;
    parts added after the snapshot was captured are intentionally ignored.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Configuration"
    instance_states: List[AssemblyInstanceConfigState] = Field(default_factory=list)
    joint_states: List[AssemblyJointConfigState] = Field(default_factory=list)


class DeformationLogEntry(BaseModel):
    """Feature log entry for a bend or twist deformation operation."""
    feature_type: Literal['deformation'] = 'deformation'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    deformation_id: str   # references a DeformationOp.id in design.deformations
    op_snapshot: Optional[DeformationOp] = None   # full op data for seek replay


class ClusterOpLogEntry(BaseModel):
    """Feature log entry for a cluster translate/rotate operation.

    `source` flags the originating operation when it differs from the default
    manual move/rotate UI. Frontend uses it to prefix the label so the user
    can tell e.g. relax-driven cluster updates from manual ones at a glance.
    """
    feature_type: Literal['cluster_op'] = 'cluster_op'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    cluster_id: str
    translation: List[float]   # absolute cluster state AFTER this op
    rotation: List[float]      # [qx, qy, qz, qw]
    pivot: List[float]
    source: Optional[str] = None   # e.g. 'relax', None for manual move/rotate


class OverhangRotationLogEntry(BaseModel):
    """Feature log entry for one or more overhang orientation changes applied as a batch.

    Two flavours of entry coexist (Phase 4):

    * **Whole-overhang rotation** (legacy): ``rotations[i]`` is the new
      quaternion ``[qx, qy, qz, qw]`` for ``overhang_ids[i]``. The trailing
      sub_domain lists are either empty or carry ``None`` for that index.

    * **Sub-domain (theta, phi) rotation** (new): ``sub_domain_ids[i]`` is
      the UUID of the sub-domain whose ``(theta_deg, phi_deg)`` changed;
      ``sub_domain_thetas_deg[i]`` and ``sub_domain_phis_deg[i]`` carry the
      new values; ``rotations[i]`` is a placeholder ``[0,0,0,1]``.

    Mixing the two flavours within a single entry is permitted: e.g. a
    batch may contain one whole-overhang rotation and two sub-domain
    rotations on different overhangs, in which case the trailing lists
    carry ``None`` for the whole-overhang index.
    """
    feature_type: Literal['overhang_rotation'] = 'overhang_rotation'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    overhang_ids: List[str]
    rotations: List[List[float]]   # [qx, qy, qz, qw] per overhang_id (parallel list)
    labels: List[Optional[str]] = []
    # Phase 4 parallel lists. Length 0 == legacy entry (all whole-overhang).
    # Length N == one entry per overhang_ids[i]; None == whole-overhang at
    # that index, UUID == sub-domain rotation at that index.
    sub_domain_ids: List[Optional[str]] = []
    sub_domain_thetas_deg: List[Optional[float]] = []
    sub_domain_phis_deg: List[Optional[float]] = []

    @model_validator(mode='after')
    def _validate_subdomain_lists(self) -> 'OverhangRotationLogEntry':
        n = len(self.overhang_ids)

        # Each trailing list must be empty (legacy) or length-n.
        for name, lst in (
            ('sub_domain_ids', self.sub_domain_ids),
            ('sub_domain_thetas_deg', self.sub_domain_thetas_deg),
            ('sub_domain_phis_deg', self.sub_domain_phis_deg),
        ):
            if len(lst) not in (0, n):
                raise ValueError(
                    f"OverhangRotationLogEntry.{name} must have length 0 or "
                    f"{n} (== len(overhang_ids)), got {len(lst)}"
                )

        if not self.sub_domain_ids and not self.sub_domain_thetas_deg and not self.sub_domain_phis_deg:
            return self

        # When any trailing list is populated, all three must be the same
        # length (pad missing ones with None).
        if len(self.sub_domain_ids) == 0:
            object.__setattr__(self, 'sub_domain_ids', [None] * n)
        if len(self.sub_domain_thetas_deg) == 0:
            object.__setattr__(self, 'sub_domain_thetas_deg', [None] * n)
        if len(self.sub_domain_phis_deg) == 0:
            object.__setattr__(self, 'sub_domain_phis_deg', [None] * n)

        # Per-index validation.
        for i in range(n):
            sd_id = self.sub_domain_ids[i]
            theta = self.sub_domain_thetas_deg[i]
            phi   = self.sub_domain_phis_deg[i]
            if sd_id is None:
                # Whole-overhang slot: theta/phi must also be None.
                if theta is not None or phi is not None:
                    raise ValueError(
                        "OverhangRotationLogEntry: index "
                        f"{i} has sub_domain_ids=None but theta/phi populated."
                    )
            else:
                if theta is None or phi is None:
                    raise ValueError(
                        "OverhangRotationLogEntry: index "
                        f"{i} has sub_domain_ids set but theta/phi missing."
                    )
                if not (-180.0 <= float(theta) <= 180.0):
                    raise ValueError(
                        f"sub_domain_thetas_deg[{i}] out of range [-180, 180]: {theta}"
                    )
                if not (0.0 <= float(phi) <= 180.0):
                    raise ValueError(
                        f"sub_domain_phis_deg[{i}] out of range [0, 180]: {phi}"
                    )
        return self


# Auto-op kinds that emit a SnapshotLogEntry. Keep in sync with state.mutate_with_feature_log
# call sites in backend/api/crud.py.
#
# `bundle-create` is the "fresh start" endpoint: it resets to an empty design
# before running, so its pre-state is an empty Design and seeking to F0 always
# yields an empty workspace.
#
# `extrude-*` are continuation/segment ops that grow an existing design.
# `overhang-extrude` adds a single-helix overhang stub from a nick.
SnapshotOpKind = Literal[
    'bundle-create',
    'extrude-segment',
    'extrude-continuation',
    'extrude-deformed-continuation',
    'overhang-extrude',
    'auto-scaffold',
    'auto-scaffold-seamed',
    'auto-scaffold-seamless',
    'auto-break',
    'auto-merge',
    'auto-crossover',
    'create-near-ends',
    'create-far-ends',
    'overhang-bulk',
    'apply-loop-skips',
    'linker-add',
    'linker-delete',
    'assembly-overhang-bind',
    'assembly-overhang-bind-patch',
    'assembly-overhang-unbind',
    'assembly-overhang-connection-add',
    'assembly-overhang-connection-patch',
    'assembly-overhang-connection-delete',
    'assembly-polymerize',
    'assembly-add-instance',
    'assembly-delete-instance',
    'assembly-duplicate-instance',
    'assembly-add-connector',
    'assembly-delete-connector',
    'assembly-add-joint',
    'assembly-delete-joint',
]


class SnapshotLogEntry(BaseModel):
    """Feature log entry for a bulk auto-operation.

    Carries TWO full design snapshots so the op is fully scrubbable even after
    a browser refresh:

    * ``design_snapshot_gz_b64`` — design state IMMEDIATELY BEFORE the op ran.
      Used by ``POST /design/features/{i}/revert`` and by slider-seek when
      seeking BEFORE this entry's position.
    * ``post_state_gz_b64`` — design state IMMEDIATELY AFTER the op ran (and
      cluster reconcile). Used by slider-seek when seeking AT/AFTER this
      entry's position so back-and-forth scrubbing recovers the live topology
      regardless of intervening seeks.

    Both payloads are ``gzip(Design.model_dump_json())`` with the design's own
    ``feature_log`` and ``feature_log_cursor`` stripped before encoding to
    prevent recursive nesting.

    ``evicted=True`` means the bodies were dropped to free space; the entry is
    still visible historically but is no longer revertable or seek-restorable.
    """
    feature_type: Literal['snapshot'] = 'snapshot'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    op_kind: SnapshotOpKind
    label: str
    timestamp: str = ""                  # ISO-8601 UTC, set by mutate_with_feature_log
    params: dict = Field(default_factory=dict)
    design_snapshot_gz_b64: str = ""     # gzipped JSON of PRE-state design, base64
    snapshot_size_bytes: int = 0         # uncompressed PRE-state JSON byte length
    post_state_gz_b64: str = ""          # gzipped JSON of POST-state design, base64
    post_state_size_bytes: int = 0       # uncompressed POST-state JSON byte length
    evicted: bool = False


# Subtypes of MinorMutationLogEntry — every minor user-driven mutation that
# falls into a Fine Routing cluster. Keep in sync with state.mutate_with_minor_log
# call sites in backend/api/crud.py and the dispatcher _replay_minor_op.
MinorOpSubtype = Literal[
    'strand-end-resize', 'scaffold-domain-paint',
    'crossover-place', 'crossover-place-batch',
    'crossover-move', 'crossover-move-batch',
    'crossover-delete', 'crossover-delete-batch',
    'crossover-extra-bases', 'crossover-extra-bases-batch',
    'nick', 'nick-batch', 'ligate',
    'forced-ligation-create', 'forced-ligation-delete',
    'forced-ligation-delete-batch', 'forced-ligation-extra-bases',
    'helix-add', 'helix-add-at-cell', 'helix-update', 'helix-extend', 'helix-delete',
    'strand-add', 'strand-update', 'strand-delete', 'strand-delete-batch',
    'domain-add', 'domain-delete', 'domain-shift',
    'loop-skip-insert', 'loop-skip-twist', 'loop-skip-bend',
    'strand-patch', 'strands-color-bulk',
    'joint-place', 'joint-update', 'joint-delete',
]


class MinorMutationLogEntry(BaseModel):
    """One minor user-driven mutation. Lives ONLY inside RoutingClusterLogEntry.children
    (never at the top level of feature_log). Stores the op_subtype + a JSON-safe
    params dict so the operation can be replayed mid-cluster during slider seek
    via backend.api.crud._replay_minor_op.
    """
    feature_type: Literal['minor'] = 'minor'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    op_subtype: MinorOpSubtype
    label: str          # rendered detail line, e.g. "h_XY_0_0 5' bp 0 → bp 7"
    timestamp: str = ""
    params: dict = Field(default_factory=dict)


class RoutingClusterLogEntry(BaseModel):
    """A 'Fine Routing' cluster grouping consecutive minor mutations.

    A cluster stays open across consecutive minor ops; any snapshot-emitting
    endpoint (auto-op, extrude) implicitly closes it because it appends a
    SnapshotLogEntry, after which the next minor op finds the last entry isn't
    a cluster and opens a fresh one.

    Carries pre+post snapshots like SnapshotLogEntry so:
      - revert restores the design to before the cluster's first child
        (truncating the log).
      - mid-cluster slider seek hydrates pre-state then replays
        children[0..sub_position] via _replay_minor_op.

    ``post_state_gz_b64`` is re-encoded after each child is appended so the
    cluster always has a current post-state for forward seek / latest-state
    queries.

    ``evicted=True`` means the bytes were dropped to free space; the cluster
    entry + children remain visible historically but are no longer revertable
    or seek-restorable.
    """
    feature_type: Literal['routing-cluster'] = 'routing-cluster'
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    label: str = 'Fine Routing'
    timestamp: str = ""
    children: List[MinorMutationLogEntry] = Field(default_factory=list)
    pre_state_gz_b64: str = ""
    pre_state_size_bytes: int = 0
    post_state_gz_b64: str = ""
    post_state_size_bytes: int = 0
    evicted: bool = False


FeatureLogEntry = Annotated[
    Union[
        DeformationLogEntry,
        ClusterOpLogEntry,
        OverhangRotationLogEntry,
        SnapshotLogEntry,
        RoutingClusterLogEntry,
    ],
    Field(discriminator='feature_type'),
]


class AnimationKeyframe(BaseModel):
    """
    A single keyframe in a DesignAnimation.

    camera_pose_id: ID of a CameraPose to transition to; None = keep current camera.
    feature_log_index: feature log position to seek to at this keyframe; None = no change.
    hold_duration_s: seconds to hold this state after arriving.
    transition_duration_s: seconds to tween from the previous keyframe into this one.
    easing: interpolation curve for the transition.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    camera_pose_id: Optional[str] = None
    configuration_id: Optional[str] = None  # assembly configuration snapshot id; None = no assembly state change
    feature_log_index: Optional[int] = None  # feature log position to seek to; None = no change
    hold_duration_s: float = 1.0
    transition_duration_s: float = 0.5
    easing: Literal["linear", "ease-in", "ease-out", "ease-in-out"] = "ease-in-out"
    joint_values: dict[str, float] = Field(default_factory=dict)  # assembly joint id → driven value

    # Spin = camera orbits the model centroid for the full keyframe duration.
    # Mutually exclusive with camera_pose_id at the UI layer.
    spin_axis: Optional[Literal["x", "y", "z"]] = None
    spin_rotations: float = 0.0
    spin_invert: bool = False  # negate rotation direction about the chosen axis

    # Text overlay shown during this keyframe's transition + hold window.
    # Empty `text` = no overlay; renderer fades in/out 0.1 s at each edge.
    text: str = ""
    text_font_family: str = "sans-serif"
    text_font_size_px: int = 24
    text_color: str = "#ffffff"
    text_bold: bool = False
    text_italic: bool = False
    text_align: Literal["left", "center", "right"] = "center"


class DesignAnimation(BaseModel):
    """An ordered sequence of keyframes that can be played back or exported."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Animation"
    fps: int = 30
    loop: bool = False
    keyframes: List[AnimationKeyframe] = Field(default_factory=list)


class DesignMetadata(BaseModel):
    """Freeform metadata attached to a design."""
    name: str = "Untitled"
    description: str = ""
    author: str = ""
    created_at: str = ""
    modified_at: str = ""
    tags: List[str] = Field(default_factory=list)


class TmSettings(BaseModel):
    """Design-level conditions used when computing sub-domain ``tm_celsius`` cache.

    Storing on the design (rather than per-sub-domain) keeps the experimental
    knobs consistent across an entire structure. Changing either value
    invalidates all sub-domain Tm caches — see the PATCH /design/tm-settings
    endpoint.
    """
    na_mM: float = 50.0     # monovalent salt concentration, mM
    conc_nM: float = 250.0  # total oligo concentration, nM (SantaLucia C_T term)


def _world_to_local_joint(world_origin, world_direction, ct) -> tuple[list[float], list[float]]:
    """Convert a joint axis from world-space to the cluster's local frame.

    *ct* is the cluster's transform record (dict, not a Pydantic model — this
    is called from a mode='before' validator). When ct is None / missing
    fields, defaults to identity transform (local == world).

    world_origin = R · (local_origin - pivot) + pivot + T
    → local_origin = R⁻¹ · (world_origin - pivot - T) + pivot
    world_dir    = R · local_dir
    → local_dir = R⁻¹ · world_dir
    """
    import numpy as np
    if not isinstance(ct, dict):
        return list(world_origin or [0.0, 0.0, 0.0]), list(world_direction or [0.0, 1.0, 0.0])
    # Build R from quaternion [x, y, z, w] — same convention as
    # backend.api.crud._rot_from_quaternion. Inlined to avoid a backend.api
    # import from inside backend.core.
    rotation = ct.get('rotation') or [0.0, 0.0, 0.0, 1.0]
    qx, qy, qz, qw = (float(rotation[i]) for i in range(4))
    R = np.array([
        [1 - 2*(qy*qy + qz*qz), 2*(qx*qy - qz*qw),     2*(qx*qz + qy*qw)],
        [2*(qx*qy + qz*qw),     1 - 2*(qx*qx + qz*qz), 2*(qy*qz - qx*qw)],
        [2*(qx*qz - qy*qw),     2*(qy*qz + qx*qw),     1 - 2*(qx*qx + qy*qy)],
    ], dtype=float)
    pivot       = np.array(ct.get('pivot')       or [0.0, 0.0, 0.0], dtype=float)
    translation = np.array(ct.get('translation') or [0.0, 0.0, 0.0], dtype=float)
    if world_origin is not None:
        wo = np.array(world_origin, dtype=float)
        local_origin = (R.T @ (wo - pivot - translation) + pivot).tolist()
    else:
        local_origin = [0.0, 0.0, 0.0]
    if world_direction is not None:
        wd = np.array(world_direction, dtype=float)
        local_dir = (R.T @ wd).tolist()
    else:
        local_dir = [0.0, 1.0, 0.0]
    return local_origin, local_dir


def _local_to_world_joint(local_origin, local_direction, ct) -> tuple[list[float], list[float]]:
    """Inverse of `_world_to_local_joint` — derive the joint's current
    world-space axis from its cluster-local storage and the cluster's
    transform. Used by callers that need world-space axes (rendering,
    exports, AssemblyJoint conversions). When ct is None defaults to
    identity (world == local).

    world_origin = R · (local_origin - pivot) + pivot + T
    world_dir    = R · local_direction
    """
    import numpy as np
    if not isinstance(ct, dict):
        # Pydantic model passed — extract fields.
        if ct is None:
            return list(local_origin), list(local_direction)
        rotation    = list(ct.rotation)
        pivot       = list(ct.pivot)
        translation = list(ct.translation)
    else:
        rotation    = ct.get('rotation')    or [0.0, 0.0, 0.0, 1.0]
        pivot       = ct.get('pivot')       or [0.0, 0.0, 0.0]
        translation = ct.get('translation') or [0.0, 0.0, 0.0]
    qx, qy, qz, qw = (float(rotation[i]) for i in range(4))
    R = np.array([
        [1 - 2*(qy*qy + qz*qz), 2*(qx*qy - qz*qw),     2*(qx*qz + qy*qw)],
        [2*(qx*qy + qz*qw),     1 - 2*(qx*qx + qz*qz), 2*(qy*qz - qx*qw)],
        [2*(qx*qz - qy*qw),     2*(qy*qz + qx*qw),     1 - 2*(qx*qx + qy*qy)],
    ], dtype=float)
    P = np.array(pivot,       dtype=float)
    T = np.array(translation, dtype=float)
    lo = np.array(local_origin, dtype=float)
    ld = np.array(local_direction, dtype=float)
    world_origin = (R @ (lo - P) + P + T).tolist()
    world_dir    = (R @ ld).tolist()
    return world_origin, world_dir


def _reclassify_invalid_crossovers(design: 'Design') -> None:
    """Move Crossover records that fail the lattice-neighbour test into
    ``forced_ligations``.

    Older importers — and any cadnano save predating the import audit — emitted
    Crossover records for some same-bp transitions even when the two helices
    were not valid lattice neighbours at that bp. After the audit, those should
    be ForcedLigations. Mismatched-bp halves (which the model normally forbids)
    are also handled defensively.

    Mutates *design* in place.
    """
    from backend.core.crossover_positions import crossover_neighbor  # noqa: PLC0415

    helix_grid: dict[str, tuple[int, int]] = {
        h.id: (h.grid_pos[0], h.grid_pos[1])
        for h in design.helices if h.grid_pos is not None
    }

    valid_xos: list = []
    new_fls: list[ForcedLigation] = []
    for xo in design.crossovers:
        a, b = xo.half_a, xo.half_b
        # Mismatched bp index — never a valid DX crossover.
        if a.index != b.index:
            new_fls.append(ForcedLigation(
                three_prime_helix_id=a.helix_id, three_prime_bp=a.index, three_prime_direction=a.strand,
                five_prime_helix_id=b.helix_id,  five_prime_bp=b.index,  five_prime_direction=b.strand,
            ))
            continue
        ga = helix_grid.get(a.helix_id)
        gb = helix_grid.get(b.helix_id)
        if ga is None or gb is None:
            valid_xos.append(xo)   # cannot test → preserve verbatim
            continue
        is_neighbor = False
        for is_scaf in (False, True):
            ab = crossover_neighbor(design.lattice_type, ga[0], ga[1], a.index, is_scaffold=is_scaf)
            ba = crossover_neighbor(design.lattice_type, gb[0], gb[1], b.index, is_scaffold=is_scaf)
            if (ab is not None and ab == gb) or (ba is not None and ba == ga):
                is_neighbor = True
                break
        if is_neighbor:
            valid_xos.append(xo)
        else:
            new_fls.append(ForcedLigation(
                three_prime_helix_id=a.helix_id, three_prime_bp=a.index, three_prime_direction=a.strand,
                five_prime_helix_id=b.helix_id,  five_prime_bp=b.index,  five_prime_direction=b.strand,
            ))

    if new_fls:
        design.crossovers = valid_xos
        design.forced_ligations = list(design.forced_ligations) + new_fls


def _backfill_dropped_forced_ligations(design: 'Design') -> None:
    """Add ForcedLigation records for cross-helix domain transitions that
    aren't covered by any existing Crossover or ForcedLigation.

    Older importers silently dropped scadnano-style loopouts (consecutive
    cross-helix domains where ``d0.end_bp != d1.start_bp``) instead of
    classifying them as ForcedLigations. This pass heals affected
    .nadoc files on load by emitting the missing FL records. Existing
    crossovers and forced ligations are preserved verbatim.

    Mutates *design* in place.
    """
    covered: set[tuple[str, int, str, str, int, str]] = set()
    for xo in design.crossovers:
        a = (xo.half_a.helix_id, xo.half_a.index, xo.half_a.strand.value)
        b = (xo.half_b.helix_id, xo.half_b.index, xo.half_b.strand.value)
        covered.add(a + b)
        covered.add(b + a)
    for fl in design.forced_ligations:
        covered.add((
            fl.three_prime_helix_id, fl.three_prime_bp, fl.three_prime_direction.value,
            fl.five_prime_helix_id,  fl.five_prime_bp,  fl.five_prime_direction.value,
        ))

    new_fls: list[ForcedLigation] = []
    seen: set[tuple] = set()
    for strand in design.strands:
        for i in range(len(strand.domains) - 1):
            d0 = strand.domains[i]
            d1 = strand.domains[i + 1]
            if d0.helix_id == d1.helix_id:
                continue
            key = (
                d0.helix_id, d0.end_bp, d0.direction.value,
                d1.helix_id, d1.start_bp, d1.direction.value,
            )
            if key in covered or key in seen:
                continue
            seen.add(key)
            new_fls.append(ForcedLigation(
                three_prime_helix_id=d0.helix_id,
                three_prime_bp=d0.end_bp,
                three_prime_direction=d0.direction,
                five_prime_helix_id=d1.helix_id,
                five_prime_bp=d1.start_bp,
                five_prime_direction=d1.direction,
            ))
    if new_fls:
        design.forced_ligations = list(design.forced_ligations) + new_fls


class DesignLoadout(BaseModel):
    """A named branch of the design feature timeline.

    ``design_snapshot_gz_b64`` stores a full Design payload with loadouts
    stripped, but with feature_log and feature_log_cursor preserved.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Loadout"
    design_snapshot_gz_b64: str = ""
    snapshot_size_bytes: int = 0


class Design(BaseModel):
    """
    Top-level design object.  This is the ground truth for a DNA origami
    structure; all geometry and physics are derived from it.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    helices: List[Helix] = Field(default_factory=list)
    strands: List[Strand] = Field(default_factory=list)
    lattice_type: LatticeType = LatticeType.HONEYCOMB
    metadata: DesignMetadata = Field(default_factory=DesignMetadata)
    deformations: List[DeformationOp] = Field(default_factory=list)
    cluster_transforms: List[ClusterRigidTransform] = Field(default_factory=list)
    cluster_joints: List[ClusterJoint] = Field(default_factory=list)
    overhangs: List[OverhangSpec] = Field(default_factory=list)
    overhang_connections: List[OverhangConnection] = Field(default_factory=list)
    overhang_bindings: List[OverhangBinding] = Field(default_factory=list)
    tm_settings: TmSettings = Field(default_factory=TmSettings)
    extensions: List[StrandExtension] = Field(default_factory=list)
    photoproduct_junctions: List[PhotoproductJunction] = Field(default_factory=list)
    crossovers: List[Crossover] = Field(default_factory=list)
    forced_ligations: List[ForcedLigation] = Field(default_factory=list)
    camera_poses: List[CameraPose] = Field(default_factory=list)
    animations: List[DesignAnimation] = Field(default_factory=list)
    loadouts: List[DesignLoadout] = Field(default_factory=list)
    active_loadout_id: Optional[str] = None
    feature_log: List[FeatureLogEntry] = Field(default_factory=list)
    feature_log_cursor: int = -1   # -1 = at end; ≥0 = index of last active entry
    feature_log_sub_cursor: Optional[int] = None
    """Mid-cluster position when ``feature_log_cursor`` indexes a
    RoutingClusterLogEntry. ``None`` = cluster's post-state (all children
    active); ``-2`` = pre-cluster (no children); ``0..M-1`` = first
    sub_cursor+1 children active. Lets the slider thumb land on the
    specific sub-notch the user scrubbed to."""

    @field_validator('feature_log', mode='before')
    @classmethod
    def _drop_checkpoint_entries(cls, v: object) -> object:
        """Strip legacy checkpoint entries (configurations removed) and stray
        top-level ``'minor'`` entries (those should only ever appear inside a
        RoutingClusterLogEntry's children list; a top-level minor would
        indicate a corrupt file or aborted write)."""
        if isinstance(v, list):
            return [
                e for e in v
                if not (isinstance(e, dict) and e.get('feature_type') in ('checkpoint', 'minor'))
            ]
        return v

    @model_validator(mode='before')
    @classmethod
    def _migrate_world_space_joints(cls, data: object) -> object:
        """Migrate cluster_joints from the legacy world-space schema
        (``axis_origin`` / ``axis_direction``) to the cluster-local schema
        (``local_axis_origin`` / ``local_axis_direction``).

        Legacy joints stored their axis in world space and were re-applied
        on every cluster transform commit, accumulating floating-point drift.
        The new schema stores the axis once in the cluster's local frame;
        world-space is derived lazily. This pre-validator detects any joint
        that still has the old fields, undoes the joint's cluster transform
        to recover the local-frame axis, and writes the new fields.
        Idempotent — joints already in the new schema are left untouched.
        """
        if not isinstance(data, dict):
            return data
        joints = data.get('cluster_joints')
        cts    = data.get('cluster_transforms')
        if not isinstance(joints, list) or not joints:
            return data
        ct_by_id: dict = {}
        if isinstance(cts, list):
            for ct in cts:
                if isinstance(ct, dict) and ct.get('id'):
                    ct_by_id[ct['id']] = ct
        for j in joints:
            if not isinstance(j, dict):
                continue
            if 'local_axis_origin' in j and 'local_axis_direction' in j:
                continue   # already migrated
            ax_origin    = j.get('axis_origin')
            ax_direction = j.get('axis_direction')
            if ax_origin is None and ax_direction is None:
                continue   # nothing to migrate
            ct = ct_by_id.get(j.get('cluster_id'))
            local_origin, local_dir = _world_to_local_joint(
                ax_origin, ax_direction, ct,
            )
            j['local_axis_origin']    = local_origin
            j['local_axis_direction'] = local_dir
            # Drop the legacy fields so the model doesn't carry stale state.
            j.pop('axis_origin',    None)
            j.pop('axis_direction', None)
        return data

    @field_validator('strands', mode='after')
    @classmethod
    def _drop_empty_strands(cls, v: list) -> list:
        """Remove strands that have no domains (can occur in corrupt files)."""
        return [s for s in v if s.domains]

    @model_validator(mode='after')
    def _validate_overhang_bindings(self) -> 'Design':
        """Cross-model checks for Phase 5 OverhangBinding records.

        Short-circuits when `overhang_bindings` is empty (backward compat with
        every pre-Phase-5 `.nadoc` file). When non-empty, enforces:

          • sub_domain ids resolve to existing sub-domains;
          • length match between the two referenced sub-domains;
          • antiparallel Watson-Crick complementarity (resolved sequences
            including overrides). The check is skipped (treated as not-yet-
            sequenced rather than a hard error) when either side has no
            resolvable sequence — letting users create bindings on
            unsequenced sub-domains and fill sequences later.
          • mutual exclusion with existing OverhangConnections (linker
            attach endpoints) and other bindings, keyed by the unordered
            pair {sd_a, sd_b};
          • overhang_a_id / overhang_b_id denormalization consistency;
          • target_joint_id, when set, resolves to an existing cluster_joint.
        """
        if not self.overhang_bindings:
            return self

        # ── Resolve sub-domains to (overhang, sub_domain) tuples ─────────
        sd_lookup: dict[str, tuple[OverhangSpec, SubDomain]] = {}
        for ovhg in self.overhangs:
            for sd in ovhg.sub_domains:
                sd_lookup[sd.id] = (ovhg, sd)

        joint_ids = {j.id for j in self.cluster_joints}

        # ── Mutex pair set (linker attach endpoints + bindings) ──────────
        used_pairs: dict[frozenset, str] = {}
        for conn in self.overhang_connections:
            sd_a = _sub_domain_at_attach(self, conn.overhang_a_id, conn.overhang_a_attach)
            sd_b = _sub_domain_at_attach(self, conn.overhang_b_id, conn.overhang_b_attach)
            if sd_a is None or sd_b is None:
                continue
            key = frozenset({sd_a, sd_b})
            if len(key) < 2:
                continue
            if key in used_pairs:
                continue   # don't reject existing connections; bindings will compare
            used_pairs[key] = f"linker {conn.id}"

        for binding in self.overhang_bindings:
            res_a = sd_lookup.get(binding.sub_domain_a_id)
            res_b = sd_lookup.get(binding.sub_domain_b_id)
            if res_a is None:
                raise ValueError(
                    f"OverhangBinding {binding.id}: sub_domain_a_id "
                    f"{binding.sub_domain_a_id!r} does not resolve."
                )
            if res_b is None:
                raise ValueError(
                    f"OverhangBinding {binding.id}: sub_domain_b_id "
                    f"{binding.sub_domain_b_id!r} does not resolve."
                )
            ovhg_a, sd_a = res_a
            ovhg_b, sd_b = res_b

            # Denormalization consistency.
            if binding.overhang_a_id != ovhg_a.id:
                raise ValueError(
                    f"OverhangBinding {binding.id}: overhang_a_id "
                    f"({binding.overhang_a_id}) does not match the parent overhang "
                    f"of sub_domain_a_id ({ovhg_a.id})."
                )
            if binding.overhang_b_id != ovhg_b.id:
                raise ValueError(
                    f"OverhangBinding {binding.id}: overhang_b_id "
                    f"({binding.overhang_b_id}) does not match the parent overhang "
                    f"of sub_domain_b_id ({ovhg_b.id})."
                )

            # Length match.
            if sd_a.length_bp != sd_b.length_bp:
                raise ValueError(
                    f"OverhangBinding {binding.id}: sub-domain lengths must match "
                    f"({sd_a.length_bp} vs {sd_b.length_bp})."
                )

            # Watson-Crick complementarity (only when both sequences resolvable).
            seq_a = _resolve_sd_sequence(ovhg_a, sd_a)
            seq_b = _resolve_sd_sequence(ovhg_b, sd_b)
            if seq_a is not None and seq_b is not None:
                # Local import to avoid `models -> sequences -> models` cycle.
                from backend.core.sequences import is_watson_crick_complement
                if not is_watson_crick_complement(seq_a, seq_b, allow_n=binding.allow_n_wildcard):
                    raise ValueError(
                        f"OverhangBinding {binding.id}: sequences are not "
                        f"Watson-Crick complementary (allow_n_wildcard="
                        f"{binding.allow_n_wildcard})."
                    )

            # Mutual exclusion.
            pair_key = frozenset({binding.sub_domain_a_id, binding.sub_domain_b_id})
            if pair_key in used_pairs:
                raise ValueError(
                    f"OverhangBinding {binding.id}: sub-domain pair already "
                    f"claimed by {used_pairs[pair_key]}."
                )
            used_pairs[pair_key] = f"binding {binding.id}"

            # target_joint_id resolves.
            if binding.target_joint_id is not None and binding.target_joint_id not in joint_ids:
                raise ValueError(
                    f"OverhangBinding {binding.id}: target_joint_id "
                    f"{binding.target_joint_id!r} does not resolve to a cluster_joint."
                )
        return self

    # Convenience accessor — returns the scaffold strand or None.
    def scaffold(self) -> Optional[Strand]:
        for s in self.strands:
            if s.is_scaffold:
                return s
        return None

    def scaffolds(self) -> List[Strand]:
        return [s for s in self.strands if s.is_scaffold]

    def staples(self) -> List[Strand]:
        return [s for s in self.strands if s.strand_type == StrandType.STAPLE]

    def find_helix(self, helix_id: str) -> Optional[Helix]:
        for h in self.helices:
            if h.id == helix_id:
                return h
        return None

    def find_strand(self, strand_id: str) -> Optional[Strand]:
        for s in self.strands:
            if s.id == strand_id:
                return s
        return None

    def copy_with(self, **overrides: object) -> "Design":
        """Return a shallow copy with specified fields replaced.

        Usage: existing_design.copy_with(helices=new_helices, strands=new_strands)
        All fields not in overrides are carried forward unchanged, including
        extensions, deformations, cluster_transforms, and any future fields.
        """
        return self.model_copy(update=overrides)

    # ── Persistence helpers ───────────────────────────────────────────────

    def to_dict(self) -> dict:
        """Serialise to a plain Python dict (JSON-safe)."""
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: dict) -> Design:
        """Deserialise from a plain Python dict."""
        return cls.model_validate(data)

    def to_json(self, indent: int = 2) -> str:
        """Serialise to a JSON string."""
        return self.model_dump_json(indent=indent)

    @classmethod
    def from_json(cls, text: str) -> Design:
        """Deserialise from a JSON string.

        If the loaded design has an empty crossovers list (files saved before
        the Design.crossovers model was introduced), crossovers are
        back-populated from cross-helix domain transitions in the strand topology.
        This keeps old .nadoc files working correctly without a migration step.
        """
        design = cls.model_validate(json.loads(text))
        if not design.crossovers:
            # Lazy import avoids a circular dependency with crossover_positions.py.
            from backend.core.crossover_positions import extract_crossovers_from_strands  # noqa: PLC0415
            xos, fls = extract_crossovers_from_strands(
                design.strands, design.helices, design.lattice_type,
            )
            design.crossovers = xos
            # Only seed forced_ligations if the file didn't already record any —
            # otherwise we'd duplicate user-created records on re-load.
            if not design.forced_ligations:
                design.forced_ligations = fls

        # Reclassify Crossover records that fail the lattice-neighbour test
        # (older cadnano imports kept them as Crossovers even when same-bp
        # transitions weren't between adjacent lattice cells). They now
        # become ForcedLigations.
        _reclassify_invalid_crossovers(design)
        # Backfill ForcedLigations for cross-helix transitions that older
        # imports silently dropped (mismatched-bp loopouts, etc.). Existing
        # Crossover and ForcedLigation records are preserved; only un-covered
        # transitions are added.
        _backfill_dropped_forced_ligations(design)
        return design


# ── Assembly / parts library models ──────────────────────────────────────────


class InterfacePoint(BaseModel):
    """
    A named connection point on a Part, expressed in the Part's local frame.
    """
    label: str
    position: Vec3
    normal: Vec3
    connection_type: ConnectionType
    cluster_id: Optional[str] = None


class FluctuationEnvelope(BaseModel):
    """
    Optional envelope describing thermal fluctuation of a Part as derived
    from XPBD or oxDNA ensemble data.  Stored as semi-axis lengths (nm) of an
    approximate ellipsoid in the Part's local frame.
    """
    semi_axes: Vec3                  # half-widths in x, y, z (nm)
    source: str = ""                 # e.g. "oxdna_50ns"


class ValidationRecord(BaseModel):
    """Audit trail of external validation runs performed on a Part."""
    oxdna_minimized: bool = False
    cando_run: bool = False
    snupi_run: bool = False
    experimental_validated: bool = False
    notes: str = ""


class Part(BaseModel):
    """
    Export wrapper for the assembly CAD layer.

    A Part wraps a Design with assembly-level metadata: named interface points,
    fluctuation envelope from simulation, and validation audit trail.

    Note: placement (transform) lives on PartInstance, not here.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    design: Design
    interface_points: List[InterfacePoint] = Field(default_factory=list)
    fluctuation_envelope: Optional[FluctuationEnvelope] = None
    validation_record: ValidationRecord = Field(default_factory=ValidationRecord)


# ── Multi-origami assembly models ─────────────────────────────────────────────


class PartSourceInline(BaseModel):
    """Part Design is embedded directly in the assembly file."""
    type: Literal["inline"] = "inline"
    design: Design


class PartSourceFile(BaseModel):
    """Part Design lives in a separate .nadoc file (path relative to assembly file)."""
    type: Literal["file"] = "file"
    path: str                     # relative path to .nadoc file
    sha256: Optional[str] = None  # content hash for verification; None = unverified


PartSource = Annotated[
    Union[PartSourceInline, PartSourceFile],
    Field(discriminator="type"),
]


class PartInstance(BaseModel):
    """
    One placed occurrence of a Part in an Assembly.

    transform: SE3 expressed as a row-major 4×4 matrix (Mat4x4).
    Transforms the Part's local-frame axis_start/axis_end into assembly world-space.
    NOTE: Three.js Matrix4.fromArray() is column-major — always transpose when
    crossing the JS boundary.

    base_transform: snapshot of transform at joint current_value=0, set when a
    joint is first attached.  Used by the joint drive computation to avoid
    accumulation errors across repeated PATCH calls.

    mode:
      "rigid"    — Part treated as a single rigid body; internal ClusterJoints frozen.
      "flexible" — Internal ClusterJoints active; compose with assembly-level joints.

    joint_states: current driven angle/displacement for each ClusterJoint in the
    source design (joint_id → float in radians or nm). Only used when mode="flexible".

    cluster_transform_overrides: per-instance overrides for cluster positions
    (equivalent to Design.cluster_transforms, scoped to this instance).
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Part"
    source: PartSource
    transform: Mat4x4 = Field(default_factory=Mat4x4)
    base_transform: Optional[Mat4x4] = None
    mode: Literal["rigid", "flexible"] = "flexible"
    visible: bool = True
    representation: Literal['full', 'beads', 'cylinders', 'vdw', 'ballstick', 'hull-prism'] = 'full'
    fixed: bool = False   # anchored in assembly; not moved by joint constraint solving
    allow_part_joints: bool = False  # enable interactive internal ClusterJoints in assembly mode
    joint_states: dict = Field(default_factory=dict)  # ClusterJoint.id → float (rad|nm)
    cluster_transform_overrides: List[ClusterRigidTransform] = Field(default_factory=list)
    interface_points: List[InterfacePoint] = Field(default_factory=list)


class AssemblyJoint(BaseModel):
    """
    A kinematic joint connecting two PartInstances in an Assembly.

    instance_a_id: "parent" body; None = world/ground frame.
    instance_b_id: "child" body constrained relative to instance_a.

    cluster_id_a / cluster_id_b: optional sub-cluster on each instance that the
    joint axis references (e.g. the end of a multi-cluster arm).

    axis_origin / axis_direction: in assembly world-space at current_value=0.

    current_value: driven DOF value (radians for revolute, nm for prismatic).
    Stored here for persistence and animation interpolation.

    base_transform on instance_b is set when this joint is first created, and is
    used by the backend to compute instance_b.transform without accumulation error.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "Joint"
    joint_type: Literal["revolute", "prismatic", "spherical", "rigid"] = "revolute"
    instance_a_id: Optional[str] = None   # None = ground
    cluster_id_a:  Optional[str] = None
    instance_b_id: str
    cluster_id_b:  Optional[str] = None
    axis_origin:    List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
    axis_direction: List[float] = Field(default_factory=lambda: [0.0, 0.0, 1.0])
    current_value:  float = 0.0
    min_limit: Optional[float] = None
    max_limit: Optional[float] = None
    connector_a_label: Optional[str] = None   # label of instance_a's InterfacePoint used in this mate
    connector_b_label: Optional[str] = None   # label of instance_b's InterfacePoint used in this mate


class PartLibraryEntry(BaseModel):
    """Registry entry for a known .nadoc file in the part library."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    path: str       # absolute or relative path to the .nadoc file
    sha256: str     # SHA-256 hex digest of file contents at scan time
    interface_points: List[InterfacePoint] = Field(default_factory=list)
    tags: List[str] = Field(default_factory=list)


class PartLibrary(BaseModel):
    """User's local library of available Part files."""
    entries: List[PartLibraryEntry] = Field(default_factory=list)


class Assembly(BaseModel):
    """
    A multi-origami assembly.

    Contains PartInstances (each wrapping a Design with a placement transform)
    and AssemblyJoints that define kinematic constraints between instances.

    assembly_helices / assembly_strands: helices and strands that exist at the
    assembly level (e.g. linker strands connecting two Parts, or virtual scaffold
    connections rendered as dashed lines).  Virtual scaffold connections are
    strands with strand_type=SCAFFOLD and id prefix "__vsc__".

    feature_log: undo/redo trail for assembly-level operations only.
    Each Part's own feature_log is separate and unaffected by assembly ops.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    metadata: DesignMetadata = Field(default_factory=DesignMetadata)
    instances: List[PartInstance] = Field(default_factory=list)
    joints: List[AssemblyJoint] = Field(default_factory=list)
    assembly_helices: List[Helix] = Field(default_factory=list)
    assembly_strands: List[Strand] = Field(default_factory=list)
    camera_poses: List[CameraPose] = Field(default_factory=list)
    animations: List[DesignAnimation] = Field(default_factory=list)
    configurations: List[AssemblyConfigurationSnapshot] = Field(default_factory=list)
    configuration_cursor: Optional[str] = None
    feature_log: List[FeatureLogEntry] = Field(default_factory=list)
    feature_log_cursor: int = -1
    overhang_bindings: List[AssemblyOverhangBinding] = Field(default_factory=list)
    overhang_connections: List[AssemblyOverhangConnection] = Field(default_factory=list)

    def to_dict(self) -> dict:
        """Serialise to a plain Python dict (JSON-safe)."""
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: dict) -> "Assembly":
        """Deserialise from a plain Python dict."""
        return cls.model_validate(data)

    @classmethod
    def from_json(cls, text: str) -> "Assembly":
        """Deserialise from a JSON string."""
        return cls.model_validate(json.loads(text))

    def to_json(self, indent: int = 2) -> str:
        """Serialise to a JSON string."""
        return self.model_dump_json(indent=indent)
