"""
API layer — complete molecular-simulation package exports (extracted from crud.py).

This module hosts the ``/design/export/namd-*`` and ``/design/export/gromacs-*``
endpoints — the routes that build a *ready-to-run simulation package* (a ZIP
bundle, or a probe/job-status pair) for an external MD engine:

  - NAMD: complete package, AI-assistant prompt, and the legacy inline bundle
    (PDB + PSF + identity/basepair/stacking maps + restraints + namd.conf +
    README, assembled from the templates below).
  - GROMACS: complete package, server-side installation probe, and the
    background-job export pair (synchronous + oxDNA-pre-relaxed CG variant,
    with poll-status and download-result), tracked in an in-process job store.

One reason to change: the set of complete MD-engine packages NADOC emits and how
they are bundled/launched. The lower-level single-file structural exporters
(``/design/export/pdb|psf|identity|basepairs|stacking|...``), the atomistic /
surface *display* routes, the 3D-print STL/3MF exports, and the crossover
``/design/debug/strand-stats`` diagnostic are a different concern and stay in
crud.py.

The shared export/geometry resolvers ``_design_for_export`` /
``_geometry_for_design`` stay in crud.py (used by ~12 / ~8 routes across crud.py
+ assembly.py + several core modules) and are imported back here — same
shared-kernel convention as ``routes_camera_poses.py`` / ``routes_flexible_segments.py``.

URLs are unchanged from their previous home in crud.py. Mounting is done in
``backend/api/main.py`` via ``app.include_router(...)``.
"""

from __future__ import annotations

import copy
import threading
import uuid as _uuid

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

from backend.api import state as design_state

# Shared export/geometry resolvers used by 100+ routes across crud.py +
# assembly.py + core; they stay in crud.py and are imported back here (same
# convention as routes_camera_poses.py / routes_flexible_segments.py).
from backend.api.crud import _design_for_export, _geometry_for_design

router = APIRouter()


# ── GROMACS background export job store ───────────────────────────────────────
# { job_id: { status: "running"|"done"|"error", result: bytes|None, error: str|None, name: str } }
_gromacs_jobs: dict[str, dict] = {}
_gromacs_jobs_lock = threading.Lock()


# ── NAMD bundle templates ──────────────────────────────────────────────────────

_NAMD_CONF_TEMPLATE = """\
# NAMD configuration generated by NADOC
# ─────────────────────────────────────────────────────────────────────────────
# IMPORTANT: This PSF has no angles/dihedrals.  Complete it first (see README).
# ─────────────────────────────────────────────────────────────────────────────

structure          complete.psf
coordinates        {name}.pdb
outputName         output

# CHARMM36 nucleic acid force field
# Download: http://mackerell.umaryland.edu/charmm_ff.shtml
paraTypeCharmm     on
parameters         par_all36_na.prm

# Thermostat (310 K = body temperature)
temperature        310
langevin           on
langevinDamping    5
langevinTemp       310

# Periodic boundary conditions (cell from NADOC bounding box + 5 nm margin)
PME                yes
PMEGridSpacing     1.0
cellBasisVector1   {ax:.3f}  0.000  0.000
cellBasisVector2   0.000  {ay:.3f}  0.000
cellBasisVector3   0.000  0.000  {az:.3f}
cellOrigin         {ox:.3f}  {oy:.3f}  {oz:.3f}

# Integration
timestep           2.0
nonbondedFreq      1
fullElectFrequency 2
stepspercycle      10

# Energy minimization then short MD run
minimize           1000
reinitvels         310
run                50000
"""

_NAMD_README_TEMPLATE = """\
NADOC NAMD Export
=================

Files in this archive
---------------------
  {name}.pdb   All-atom model, heavy atoms only (CHARMM36 naming, Angstroms)
  {name}.psf   Topology: atoms + bonds.  INCOMPLETE — angles/dihedrals are stubs.
  namd.conf    NAMD configuration template
  README.txt   This file

Prerequisites
-------------
  - CHARMM36 NA force field files:
      top_all36_na.rtf
      par_all36_na.prm
    Download from: http://mackerell.umaryland.edu/charmm_ff.shtml
  - psfgen (bundled with VMD or NAMD distributions)
  - NAMD2 or NAMD3

Step 1 — Complete the PSF (add angles, dihedrals, impropers)
------------------------------------------------------------
The PSF exported by NADOC contains atoms and bonds only.  Use psfgen to
generate the full CHARMM topology before running NAMD.

Create a file complete_psf.tcl with the following content:

    package require psfgen
    topology top_all36_na.rtf
    readpsf {name}.psf
    guesscoord
    writepsf complete.psf
    writepdb {name}_complete.pdb

Then run it through VMD:

    vmd -dispdev none -e complete_psf.tcl

Step 2 — Edit namd.conf
------------------------
Open namd.conf and update the path to par_all36_na.prm:

    parameters  /path/to/par_all36_na.prm

Step 3 — Run NAMD
------------------
    namd2 +p4 namd.conf > namd.log

For NAMD3 with GPU acceleration:

    namd3 +p4 +devices 0 namd.conf > namd.log

Notes
-----
  - Coordinates reflect the idealised B-form geometry from NADOC.  The
    included namd.conf runs 1000 steps of energy minimisation before
    dynamics — always minimise before production runs.
  - The model contains heavy atoms only (no hydrogens).  psfgen's
    guesscoord will place hydrogens from the RTF topology.
  - No solvent or counter-ions are included.  Add them using VMD's
    Solvation and Autoionize plugins before production MD.
  - Crossover O3\\'→P bonds are present in both PSF !NBOND and PDB LINK
    records.
"""


@router.get("/design/export/namd-complete")
def export_namd_complete() -> Response:
    """Complete NAMD simulation package — ready to run on a fresh Ubuntu machine."""
    from backend.core.namd_package import build_namd_package

    design = _design_for_export()
    name = (design.metadata.name or "design").replace(" ", "_")
    zip_bytes = build_namd_package(design)
    return Response(
        content=zip_bytes,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{name}_namd_complete.zip"'
        },
    )


@router.get("/design/export/namd-prompt")
def export_namd_prompt() -> Response:
    """Return the AI assistant prompt text for the current design (plain text)."""
    from backend.core.namd_package import get_ai_prompt

    design = design_state.get_or_404()
    return Response(
        content=get_ai_prompt(design),
        media_type="text/plain; charset=utf-8",
    )


@router.get("/design/export/gromacs-complete")
def export_gromacs_complete() -> Response:
    """
    Complete GROMACS simulation package — ready to run on a fresh Ubuntu machine.

    Runs pdb2gmx + editconf server-side (GROMACS must be installed on the NADOC
    server) and returns a self-contained ZIP containing the topology, initial
    structure, bundled force-field files, MDP files, and a one-click launch script.
    """
    from backend.core.gromacs_package import build_gromacs_package

    design = _design_for_export()
    name = (design.metadata.name or "design").replace(" ", "_")
    try:
        zip_bytes = build_gromacs_package(design)
    except RuntimeError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    return Response(
        content=zip_bytes,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{name}_gromacs.zip"'},
    )


@router.get("/design/export/gromacs-probe")
def probe_gromacs_installation() -> dict:
    """Return GROMACS availability and chosen force-field on this server."""
    from backend.core.gromacs_package import probe_gromacs

    return probe_gromacs()


@router.post("/design/export/gromacs-start")
def start_gromacs_export(
    package_name: str | None = None,
    use_deformed: bool = False,
    nvt_steps: int | None = None,
    solvate: bool = False,
    ion_conc_mM: float = 10.0,
):
    """
    Snapshot the current design and start building the GROMACS package in a
    background thread.  Returns a job_id; poll /gromacs-status/{job_id} to
    check progress, then fetch /gromacs-result/{job_id} to download the ZIP.

    Parameters
    ----------
    package_name : override the ZIP directory/file prefix (default: design name)
    use_deformed : if True, apply active deformation to helix positions
    nvt_steps    : override nsteps in nvt.mdp (default: 25 000 vacuum / 50 000 solvated)
    solvate      : add TIP3P water + MgCl2 ions
    ion_conc_mM  : MgCl2 concentration in mM (default: 10.0)
    """
    from backend.core.gromacs_package import build_gromacs_package

    design = design_state.get_or_404()
    snapshot = copy.deepcopy(design)
    name = (package_name or design.metadata.name or "design").replace(" ", "_")
    job_id = str(_uuid.uuid4())

    with _gromacs_jobs_lock:
        _gromacs_jobs[job_id] = {
            "status": "running",
            "result": None,
            "error": None,
            "name": name,
        }

    def _run() -> None:
        try:
            data = build_gromacs_package(
                snapshot,
                package_name=name,
                use_deformed=use_deformed,
                nvt_steps=nvt_steps,
                solvate=solvate,
                ion_conc_mM=ion_conc_mM,
            )
            with _gromacs_jobs_lock:
                _gromacs_jobs[job_id]["status"] = "done"
                _gromacs_jobs[job_id]["result"] = data
        except Exception as exc:
            with _gromacs_jobs_lock:
                _gromacs_jobs[job_id]["status"] = "error"
                _gromacs_jobs[job_id]["error"] = str(exc)

    threading.Thread(target=_run, daemon=True).start()
    return {"job_id": job_id}


@router.post("/design/export/gromacs-cg-start")
def start_gromacs_cg_export(
    package_name: str | None = None,
    nvt_steps: int | None = None,
    solvate: bool = False,
    ion_conc_mM: float = 10.0,
    oxdna_steps: int = 50_000,
):
    """
    oxDNA-pre-relaxed GROMACS export.

    Runs a short oxDNA energy minimisation on the current design, then
    uses the relaxed backbone positions as the starting structure for the
    GROMACS package.  Crossover terminal atom clashes (O5'/O1P at ~0.05 nm)
    are resolved by oxDNA before GROMACS EM, so EM converges in ~1000 steps
    instead of ~12000 and avoids the 10¹² kJ/mol LJ spike.

    Requires oxDNA to be installed (set OXDNA_BIN env var if not on PATH).
    Falls back gracefully: if oxDNA is unavailable the job fails with a clear
    error message; use /design/export/gromacs-start for the ideal-B-DNA path.

    Returns job_id; poll /design/export/gromacs-status/{job_id} then fetch
    /design/export/gromacs-result/{job_id} when done.
    """
    import os
    import tempfile as _tempfile
    import pathlib as _pathlib

    from backend.physics.oxdna_interface import (
        write_topology,
        write_configuration,
        write_oxdna_input,
        run_oxdna,
        read_configuration,
    )

    design = design_state.get_or_404()
    snapshot = copy.deepcopy(design)
    geometry = _geometry_for_design(design)
    name = (package_name or design.metadata.name or "design").replace(" ", "_")
    job_id = str(_uuid.uuid4())

    with _gromacs_jobs_lock:
        _gromacs_jobs[job_id] = {
            "status": "running",
            "result": None,
            "error": None,
            "name": name,
        }

    def _run() -> None:
        try:
            oxdna_bin = os.environ.get("OXDNA_BIN", "oxDNA")
            with _tempfile.TemporaryDirectory() as tmpdir:
                p = _pathlib.Path(tmpdir)
                write_topology(snapshot, p / "topology.top")
                write_configuration(snapshot, geometry, p / "conf.dat")
                write_oxdna_input(
                    p / "topology.top",
                    p / "conf.dat",
                    p / "input.txt",
                    steps=oxdna_steps,
                    relaxation_steps=min(oxdna_steps // 10, 5000),
                )
                ret = run_oxdna(p / "input.txt", oxdna_bin=oxdna_bin, timeout=300)
                if ret is None:
                    raise RuntimeError(
                        f"oxDNA binary not found (tried: {oxdna_bin!r}). "
                        "Install with: conda install -c bioconda oxdna  "
                        "or set OXDNA_BIN env var.  "
                        "Use /design/export/gromacs-start for the ideal-B-DNA path."
                    )
                if ret != 0:
                    raise RuntimeError(
                        f"oxDNA exited with code {ret}. "
                        "Check design topology for disconnected strands."
                    )
                last_conf = p / "last_conf.dat"
                if not last_conf.exists():
                    raise RuntimeError("oxDNA finished but produced no last_conf.dat.")

                from backend.core.cg_to_atomistic import _smooth_cg_positions_per_domain

                cg_positions = read_configuration(last_conf, snapshot)
                nuc_pos_override = _smooth_cg_positions_per_domain(
                    snapshot, cg_positions
                )

            from backend.core.gromacs_package import build_gromacs_package

            data = build_gromacs_package(
                snapshot,
                package_name=name,
                nuc_pos_override=nuc_pos_override,
                nvt_steps=nvt_steps,
                solvate=solvate,
                ion_conc_mM=ion_conc_mM,
            )
            with _gromacs_jobs_lock:
                _gromacs_jobs[job_id]["status"] = "done"
                _gromacs_jobs[job_id]["result"] = data
        except Exception as exc:
            with _gromacs_jobs_lock:
                _gromacs_jobs[job_id]["status"] = "error"
                _gromacs_jobs[job_id]["error"] = str(exc)

    threading.Thread(target=_run, daemon=True).start()
    return {"job_id": job_id}


@router.post("/design/export/gromacs-mrdna-start")
def start_gromacs_mrdna_export(
    mrdna_job_id: str,
    package_name: str | None = None,
    nvt_steps: int | None = None,
    solvate: bool = False,
    ion_conc_mM: float = 10.0,
):
    """
    mrDNA-pre-relaxed GROMACS export.

    Seeds the GROMACS package from a COMPLETED fine-stage mrDNA/ARBD relaxation
    job (created via ``POST /mrdna/jobs`` with ``fine_steps > 0``) instead of
    running a fresh CG relaxation.  The job's fine-stage bead positions become the
    atomistic starting structure via ``nuc_pos_override_from_arbd_strands``
    (crossover nucleotides INCLUDED at the CG-realistic ~0.3-0.5 nm gap), so the
    downstream GROMACS EM converges in ~hundreds of steps without the crossover
    LJ spike.  Sibling of ``/design/export/gromacs-cg-start`` (which runs oxDNA).

    Unlike the other export routes this seeds from the JOB'S design snapshot (the
    structure the relaxation actually ran on), NOT the live active design — the
    bead↔nucleotide mapping is only valid against that snapshot's helix geometry.

    Gating (returns 4xx synchronously, before the background job starts):
      - 404 if the mrDNA job id is unknown;
      - 409 if the job is not completed, is coarse-only (``fine_steps = 0``), or
        its fine-stage snapshot/PSF/DCD are missing.

    Returns ``job_id``; poll ``/design/export/gromacs-status/{job_id}`` then fetch
    ``/design/export/gromacs-result/{job_id}`` when done.
    """
    from backend.api.assembly import _WORKSPACE_DIR
    from backend.core.mrdna_job import MrdnaJob
    from backend.core.mrdna_runner import (
        build_md_seed_override,
        reconcile_mrdna_status,
        resolve_md_seed_inputs,
    )

    try:
        job = MrdnaJob.load(mrdna_job_id, _WORKSPACE_DIR)
    except FileNotFoundError:
        raise HTTPException(
            status_code=404, detail=f"mrDNA job {mrdna_job_id!r} not found"
        )
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(
            status_code=500, detail=f"Failed to load mrDNA job {mrdna_job_id}: {exc}"
        )
    job = reconcile_mrdna_status(job, _WORKSPACE_DIR)

    # Gate + resolve fine-stage inputs synchronously so the client gets a specific,
    # immediate error (coarse-only / not finished / missing output) rather than an
    # opaque background-job failure.
    try:
        snapshot, psf, dcd = resolve_md_seed_inputs(job, _WORKSPACE_DIR)
    except ValueError as exc:
        raise HTTPException(status_code=409, detail=str(exc))

    name = (
        package_name or snapshot.metadata.name or job.design_name or "design"
    ).replace(" ", "_")
    job_id = str(_uuid.uuid4())
    with _gromacs_jobs_lock:
        _gromacs_jobs[job_id] = {
            "status": "running",
            "result": None,
            "error": None,
            "name": name,
        }

    def _run() -> None:
        try:
            override = build_md_seed_override(snapshot, psf, dcd)
            from backend.core.gromacs_package import build_gromacs_package

            data = build_gromacs_package(
                snapshot,
                package_name=name,
                nuc_pos_override=override,
                nvt_steps=nvt_steps,
                solvate=solvate,
                ion_conc_mM=ion_conc_mM,
            )
            with _gromacs_jobs_lock:
                _gromacs_jobs[job_id]["status"] = "done"
                _gromacs_jobs[job_id]["result"] = data
        except Exception as exc:  # noqa: BLE001
            with _gromacs_jobs_lock:
                _gromacs_jobs[job_id]["status"] = "error"
                _gromacs_jobs[job_id]["error"] = str(exc)

    threading.Thread(target=_run, daemon=True).start()
    return {"job_id": job_id}


@router.get("/design/export/gromacs-status/{job_id}")
def gromacs_export_status(job_id: str) -> dict:
    """Poll for job status.  Returns {status, error, name}."""
    with _gromacs_jobs_lock:
        job = _gromacs_jobs.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")
    return {"status": job["status"], "error": job.get("error"), "name": job["name"]}


@router.get("/design/export/gromacs-result/{job_id}")
def gromacs_export_result(job_id: str) -> Response:
    """
    Download the completed GROMACS ZIP.  Deletes the job from the store after
    returning so memory is freed immediately.
    """
    with _gromacs_jobs_lock:
        job = _gromacs_jobs.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")
    if job["status"] != "done":
        raise HTTPException(status_code=409, detail=f"Job status: {job['status']}")
    result = job["result"]
    name = job["name"]
    with _gromacs_jobs_lock:
        _gromacs_jobs.pop(job_id, None)
    return Response(
        content=result,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{name}_gromacs.zip"'},
    )


@router.get("/design/export/namd-bundle")
def export_namd_bundle_file() -> Response:
    """ZIP archive: {name}.pdb, {name}.psf, namd.conf, README.txt"""
    import io
    import zipfile
    from backend.core.atomistic import build_atomistic_model
    from backend.core.pdb_export import (
        _box_dimensions,
        export_basepair_map_json,
        export_basepair_map_tsv,
        export_design_maps_json,
        export_dry_implicit_restraints,
        export_identity_json,
        export_identity_tsv,
        export_pdb,
        export_psf,
        export_stacking_map_json,
        export_stacking_map_tsv,
    )

    design = _design_for_export()
    name = (design.metadata.name or "design").replace(" ", "_")

    model = build_atomistic_model(design)
    ax, ay, az, ox, oy, oz = _box_dimensions(model.atoms, margin_nm=5.0)

    pdb_text = export_pdb(design, model=model)
    psf_text = export_psf(design, model=model)
    identity_json = export_identity_json(design, model=model)
    identity_tsv = export_identity_tsv(design, model=model)
    design_maps_json = export_design_maps_json(design, model=model)
    basepairs_json = export_basepair_map_json(design, model=model)
    basepairs_tsv = export_basepair_map_tsv(design, model=model)
    stacking_json = export_stacking_map_json(design, model=model)
    stacking_tsv = export_stacking_map_tsv(design, model=model)
    dry_restraints = export_dry_implicit_restraints(design, model=model)
    conf_text = _NAMD_CONF_TEMPLATE.format(
        name=name,
        ax=ax,
        ay=ay,
        az=az,
        ox=ox,
        oy=oy,
        oz=oz,
    )
    readme_text = _NAMD_README_TEMPLATE.format(name=name)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{name}.pdb", pdb_text)
        zf.writestr(f"{name}.psf", psf_text)
        zf.writestr(f"{name}.identity.json", identity_json)
        zf.writestr(f"{name}.identity.tsv", identity_tsv)
        zf.writestr(f"{name}.design_maps.json", design_maps_json)
        zf.writestr(f"{name}.basepairs.json", basepairs_json)
        zf.writestr(f"{name}.basepairs.tsv", basepairs_tsv)
        zf.writestr(f"{name}.stacking.json", stacking_json)
        zf.writestr(f"{name}.stacking.tsv", stacking_tsv)
        for filename, text in dry_restraints.items():
            zf.writestr(f"restraints/{filename}", text)
        zf.writestr("namd.conf", conf_text)
        zf.writestr("README.txt", readme_text)
    buf.seek(0)

    return Response(
        content=buf.getvalue(),
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{name}_namd.zip"'},
    )
