"""Generation must leave native editable operations, not a bespoke feature language."""

import numpy as np
import pytest
from backend.api import state
from backend.api.headless_build import scratch_session
from backend.api.generated_history import build_recorded
from backend.api.crud import _seek_feature_log
from backend.core.models import Design, Nanoparticle, Mat4x4
from backend.core.two_np_generator import GeneratorSettings
from backend.core.platform_generator import plan_generated


def source():
    particles = []
    for point in [(0, 0, 0), (40, 0, 0), (40, 0, 45)]:
        pose = np.eye(4)
        pose[:3, 3] = point
        particles.append(Nanoparticle(diameter_nm=10, pose=Mat4x4.from_array(pose)))
    return Design(nanoparticles=particles)


@pytest.fixture(scope="module")
def construction():
    original = source()
    settings = GeneratorSettings(shape="curved-rod")
    candidate, _ = plan_generated(original, settings)
    with scratch_session():
        result, report = build_recorded(original, candidate, settings)
    return original, result, report


def test_native_operations_and_snapshot_boundaries(construction):
    original, design, report = construction
    from backend.core.validator import validate_design
    from backend.core.curved_rod_generator import physical_scaffold_nt

    assert report["connections"]
    restored = Design.model_validate_json(design.model_dump_json())
    assert all(e.autogenerated_group_id for e in restored.feature_log)
    assert len({e.autogenerated_group_id for e in restored.feature_log}) == 1
    assert all(child.autogenerated_group_id == e.autogenerated_group_id
               for e in restored.feature_log for child in getattr(e, "children", []))
    attachments = [e for e in design.feature_log if getattr(e, "op_kind", "") == "nanoparticle-attach-overhang"]
    assert len(attachments) == len(original.nanoparticles)
    assert all(e.params["fixed_center"] for e in attachments)
    assert not any(getattr(e, "op_kind", "") == "nanoparticle-connection-version-create" for e in design.feature_log)
    assert validate_design(design).passed
    assert physical_scaffold_nt(design) <= 8064
    assert max(report["attachment_residuals_nm"]) < 1e-8
    assert sum(getattr(e, "op_kind", "") == "sweep" for e in design.feature_log) == 1
    assert [op.type for op in design.deformations] == ["sweep"]
    assert any(e.feature_type == "cluster_op" for e in design.feature_log)
    assert any(e.feature_type == "routing-cluster" for e in design.feature_log)
    for e in design.feature_log:
        assert getattr(e, "op_kind", "") not in (
            "curve-path",
            "cluster-pose",
            "nanoparticle-connection-relax",
        )
    for i, entry in enumerate(design.feature_log):
        scrubbed = _seek_feature_log(design, i)
        if entry.feature_type == "deformation":
            assert entry.deformation_id in {op.id for op in scrubbed.deformations}
        if entry.feature_type == "cluster_create":
            assert entry.cluster_id in {c.id for c in scrubbed.cluster_transforms}
            created = next(
                c for c in scrubbed.cluster_transforms if c.id == entry.cluster_id
            )
            assert created.parent_cluster_id == entry.cluster_snapshot.parent_cluster_id
            assert (
                created.overhang_duplex_driver_id
                == entry.cluster_snapshot.overhang_duplex_driver_id
            )
        if not getattr(entry, "post_state_gz_b64", ""):
            continue
        expected = state.decode_design_snapshot(entry.post_state_gz_b64)
        for field in (
            "helices",
            "strands",
            "nanoparticles",
            "deformations",
            "cluster_transforms",
            "duplexes",
        ):
            assert getattr(scrubbed, field) == getattr(expected, field), (
                i,
                getattr(entry, "label", ""),
                field,
            )
    np.testing.assert_allclose(
        [p.pose.values[3::4][:3] for p in design.nanoparticles],
        [p.pose.values[3::4][:3] for p in original.nanoparticles],
    )


def test_ordinary_sweep_editor_and_revert(construction):
    from backend.api.crud import edit_feature, EditFeatureBody, revert_to_before_feature
    from backend.api.sweep_history import preview_sweep_edit
    from backend.core.sweep import SweepRequest

    original, design, _ = construction
    index = next(
        i
        for i, e in enumerate(design.feature_log)
        if getattr(e, "op_kind", "") == "sweep"
    )
    with scratch_session():
        state.set_design(design)
        revert_to_before_feature(index + 1)
        current = state.get_or_404()
        params = dict(current.feature_log[index].params)
        preview = preview_sweep_edit(current, SweepRequest(**params), index)
        assert preview["length_bp"] > 0
        points = [list(p) for p in params["points_nm"]]
        points[-1][0] += 0.1
        params["points_nm"] = points
        old_ids = {h.id for h in current.helices}
        edit_feature(index, EditFeatureBody(params=params))
        edited = state.get_or_404()
        assert {h.id for h in edited.helices} == old_ids
        assert list(edited.deformations[-1].params.points_nm[-1]) == points[-1]
        revert_to_before_feature(0)
        assert state.get_or_404().helices == original.helices
        assert state.get_or_404().nanoparticles == original.nanoparticles
