"""Validation tests for the parametric *circle* (flat disc) primitive.

A circle primitive is a single row of SQUARE-lattice helices whose lengths trace
a circular chord profile. Two things must hold:

1. **Circularity** — the generated length profile is far more circular than the
   hand-built ``small_circle.nadoc`` it generalises. We measure circularity as
   the spread (max − min) of the per-column *implied radius* ``√(x² + (L/2)²)``;
   a perfect circle has spread 0. The analytic generator must beat the hand-made
   baseline by a wide margin across a range of radii.
2. **Placement** — dropping the disc via ``POST /design/circle-segment`` builds
   one helix per column, each *centred* on the slice plane, recorded as a single
   revertable feature-log entry, additive over existing DNA.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from backend.api import state as design_state
from backend.api.main import app
from backend.core.circle_primitive import (
    DEFAULT_MIN_CHORD_BP,
    circle_footprint,
    circularity_spread,
    column_lengths,
    fit_radius,
)
from backend.core.constants import BDNA_RISE_PER_BP, SQUARE_COL_PITCH
from backend.core.models import Design

client = TestClient(app)

_SMALL_CIRCLE = Path("workspace/Primitives/small_circle.nadoc")

# small_circle.nadoc is a hand-built reference design kept under workspace/ and not
# checked into the repo, so skip the tests that read it when it's absent (fresh
# clone / CI / second computer) rather than erroring with FileNotFoundError.
_skip_if_no_circle = pytest.mark.skipif(
    not _SMALL_CIRCLE.exists(),
    reason=f"primitive fixture missing: {_SMALL_CIRCLE} (hand-built, not in repo)",
)


@pytest.fixture(autouse=True)
def reset_state():
    yield
    design_state.close_session()


# The ORIGINAL hand-trimmed small_circle profile (the wobbly baseline this feature
# generalises). Hardcoded, NOT read from the file — the file is now regenerated by
# the analytic generator (clean), so it's no longer a hand-built baseline.
HAND_BUILT_BASELINE = [16, 32, 54, 60, 64, 64, 60, 54, 32, 16]


# ── 1. Pure geometry invariants ────────────────────────────────────────────────


@pytest.mark.parametrize("radius", [6.0, 8.0, 10.6, 12.0, 15.0, 20.0])
def test_column_lengths_even_symmetric_and_above_floor(radius):
    cols = column_lengths(radius)
    lengths = [bp for _, bp in cols]
    offsets = [c for c, _ in cols]
    assert lengths, "a usable radius must admit at least the centre column"
    assert all(bp % 2 == 0 for bp in lengths), "lengths must be even (symmetric trim)"
    assert all(bp >= DEFAULT_MIN_CHORD_BP for bp in lengths), "edge cutoff respected"
    assert offsets == sorted(offsets) and offsets == [-o for o in reversed(offsets)], (
        "columns are symmetric about the centre"
    )
    assert lengths == lengths[::-1], "length profile is centre-symmetric"
    # The centre column is the longest chord.
    assert max(lengths) == lengths[len(lengths) // 2]


def test_min_chord_floor_is_configurable():
    loose = column_lengths(10.6, min_chord_bp=2)
    tight = column_lengths(10.6, min_chord_bp=40)
    assert len(loose) > len(tight), "a higher floor drops more edge columns"
    assert all(bp >= 40 for _, bp in tight)


def test_radius_too_small_yields_no_columns():
    # Below the floor: even the centre chord rounds under min_chord_bp.
    assert column_lengths(0.5) == []
    assert circle_footprint(0.5) is None


# ── 2. Circularity beats the hand-built baseline ───────────────────────────────


def test_generated_circle_far_more_circular_than_hand_built():
    baseline = circularity_spread(HAND_BUILT_BASELINE)
    # The hand-trimmed original wobbles ~1.2 nm in implied radius.
    assert baseline > 1.0, (
        f"sanity: hand-built baseline should be wobbly, got {baseline:.3f}"
    )

    radius = fit_radius(
        HAND_BUILT_BASELINE
    )  # default radius "corresponds" to the original
    generated = [bp for _, bp in column_lengths(radius)]
    spread = circularity_spread(generated)
    assert spread < 0.5, f"generated spread {spread:.3f} nm should be tight"
    assert spread < baseline / 2, (
        f"generated {spread:.3f} nm must beat hand-built {baseline:.3f} nm by 2x+"
    )


@pytest.mark.parametrize("radius", [6.0, 8.0, 10.6, 12.0, 15.0, 20.0, 30.0])
def test_circularity_spread_bounded_across_radii(radius):
    generated = [bp for _, bp in column_lengths(radius)]
    # Spread is bounded by the bp quantisation: at most ~one bp rise of half-chord
    # slack per column. Half a nanometre is a comfortable, radius-independent cap.
    assert circularity_spread(generated) < 0.5


# ── 3. Placement route: centred, additive, revertable ──────────────────────────


def test_place_circle_is_tangent_to_plane_and_revertable():
    design_state.set_design(Design(lattice_type="SQUARE"))
    fp = circle_footprint(10.6)
    assert fp is not None
    r = client.post(
        "/api/design/circle-segment",
        json={
            "cells": fp["cells"],
            "cell_lengths": fp["cell_lengths"],
            "plane": "XY",
            "offset_nm": 0.0,
            "strand_filter": "both",
            "ligate_adjacent": True,
        },
    )
    assert r.status_code == 201, r.text

    d = design_state.get_or_404()
    assert len(d.helices) == len(fp["cells"])
    # The disc sits entirely on the +normal side, tangent to the plane (z=0): every
    # helix is centred on the disc mid-line at z=R, and the longest (centre) helix
    # reaches down to exactly z=0. Nothing dips below the plane.
    radius_nm = max(fp["cell_lengths"]) * BDNA_RISE_PER_BP / 2.0
    by_col = {h.grid_pos[1]: h for h in d.helices}
    lows = []
    for i, length in enumerate(fp["cell_lengths"]):
        h = by_col[i]
        lo = min(h.axis_start.z, h.axis_end.z)
        mid = (h.axis_start.z + h.axis_end.z) / 2.0
        span = abs(h.axis_end.z - h.axis_start.z)
        assert lo >= -1e-6, "no helix dips below the slice plane (+bp only)"
        assert mid == pytest.approx(radius_nm, abs=1e-6), (
            "centred on the disc mid-line z=R"
        )
        assert span == pytest.approx(length * BDNA_RISE_PER_BP, abs=1e-6)
        lows.append(lo)
    assert min(lows) == pytest.approx(0.0, abs=1e-6), "disc is tangent to the plane"

    assert len(d.feature_log) == 1
    assert d.feature_log[-1].op_kind == "circle-segment"

    rv = client.post("/api/design/features/0/revert")
    assert rv.status_code == 200
    assert design_state.get_or_404().helices == []


def test_place_circle_into_honeycomb_design():
    """The circle is lattice-agnostic — it builds into a HONEYCOMB design's lattice."""
    design_state.set_design(Design(lattice_type="HONEYCOMB"))
    fp = circle_footprint(10.6)
    r = client.post(
        "/api/design/circle-segment",
        json={
            "cells": fp["cells"],
            "cell_lengths": fp["cell_lengths"],
            "plane": "XY",
        },
    )
    assert r.status_code == 201, r.text
    d = design_state.get_or_404()
    assert len(d.helices) == len(fp["cells"])
    assert d.lattice_type.value.upper() == "HONEYCOMB"


def test_place_circle_is_additive_over_existing_dna():
    from backend.core.lattice import make_bundle_design

    base = make_bundle_design([(0, 0)], length_bp=42, lattice_type="SQUARE")
    design_state.set_design(base)
    fp = circle_footprint(8.0)
    # Shift the footprint columns away from the existing (0,0) helix.
    cells = [[0, c + 5] for _, c in fp["cells"]]
    r = client.post(
        "/api/design/circle-segment",
        json={
            "cells": cells,
            "cell_lengths": fp["cell_lengths"],
            "plane": "XY",
        },
    )
    assert r.status_code == 201, r.text
    grid = {tuple(h.grid_pos) for h in design_state.get_or_404().helices}
    assert (0, 0) in grid
    assert len(grid) == 1 + len(cells)


# ── 4. Catalog surfaces the parametric spec ────────────────────────────────────


@_skip_if_no_circle
def test_small_circle_derives_parametric_circle_spec():
    from backend.core.primitive_catalog import derive_placement_spec

    spec = derive_placement_spec(json.loads(_SMALL_CIRCLE.read_text()))
    assert spec is not None
    assert spec["kind"] == "circle"
    assert spec["lattice"] == "SQUARE"
    # Default radius is fit from the example's own helices (~10.4 nm).
    assert 9.0 < spec["default_radius_nm"] < 12.0
    assert spec["min_chord_bp"] == DEFAULT_MIN_CHORD_BP


@_skip_if_no_circle
def test_small_circle_metadata_is_named_circle_no_lattice():
    from backend.core.primitive_catalog import derive_metadata

    meta = derive_metadata(json.loads(_SMALL_CIRCLE.read_text()), "small_circle")
    assert meta["name"] == "Circle"
    assert meta["kind"] == "circle"
    # The disc is lattice-agnostic → its description must not mention a lattice.
    assert "Square" not in meta["description"]
    assert "Honeycomb" not in meta["description"]
    assert "helix beam" not in meta["description"]


@_skip_if_no_circle
def test_primitive_kind_survives_design_roundtrip():
    """`primitive_kind` is a real DesignMetadata field, so it persists through a
    load→save round-trip (the app's save would drop a freeform metadata key)."""
    design = Design.model_validate(json.loads(_SMALL_CIRCLE.read_text()))
    assert design.metadata.primitive_kind == "circle"
    reloaded = json.loads(design.model_dump_json())
    assert reloaded["metadata"]["primitive_kind"] == "circle"


def test_footprint_matches_lattice_constants():
    fp = circle_footprint(10.6)
    # Single row, contiguous columns 0..N-1, anchor on the CENTRE column (tangent
    # point) so the cursor sits at the disc's midpoint, not the first helix.
    assert all(cell[0] == 0 for cell in fp["cells"])
    assert [c for _, c in fp["cells"]] == list(range(len(fp["cells"])))
    assert fp["anchor_cell"] == [0, (len(fp["cells"]) - 1) // 2]
    # The anchor column carries the longest chord (the disc's diameter).
    anchor_col = fp["anchor_cell"][1]
    assert fp["cell_lengths"][anchor_col] == max(fp["cell_lengths"])
    # Uses the real square col pitch, not a stale 2.6 nm comment value.
    assert SQUARE_COL_PITCH == pytest.approx(2.25, abs=1e-9)
