#!/usr/bin/env bash
# Sequential EM → NVT → NPT → production run.
# Parallel gmx mdrun runs are slower on this hardware; runs are serial.
# Generated by NADOC crossover parameterization pipeline.
set -euo pipefail

GMX=gmx
NTMPI=1
# Leave 4 threads free for user tasks (Compy5000 has 32 total → cap at 28)
NTOMP=$(( $(nproc --all 2>/dev/null || echo 8) - 4 ))
# EM uses steep (non-dynamical): PME GPU not supported, use nb GPU only.
# MD phases (sd integrator): full GPU offload for nb, PME, and bonded.
# -update gpu omitted: position restraints are active in all phases.
EM_GPU="-nb gpu"
MD_GPU="-nb gpu -pme gpu -bonded gpu"

echo "[$(date)] === Energy minimisation ==="
$GMX grompp -f em.mdp    -c conf.gro   -r conf.gro  -p topol.top -o em.tpr    -maxwarn 10
$GMX mdrun  -v -ntmpi $NTMPI -ntomp $NTOMP $EM_GPU -deffnm em

echo "[$(date)] === NVT heating 0→310 K ==="
$GMX grompp -f nvt.mdp   -c em.gro    -r conf.gro  -p topol.top -o nvt.tpr   -maxwarn 10
$GMX mdrun  -v -ntmpi $NTMPI -ntomp $NTOMP $MD_GPU -deffnm nvt

echo "[$(date)] === NPT equilibration ==="
$GMX grompp -f npt.mdp   -c nvt.gro   -r conf.gro  -t nvt.cpt   -p topol.top -o npt.tpr   -maxwarn 10
$GMX mdrun  -v -ntmpi $NTMPI -ntomp $NTOMP $MD_GPU -deffnm npt

echo "[$(date)] === Production (10 ns) ==="
$GMX grompp -f production.mdp -c npt.gro -r conf.gro -t npt.cpt -p topol.top -o prod.tpr -maxwarn 10
$GMX mdrun  -v -ntmpi $NTMPI -ntomp $NTOMP $MD_GPU -deffnm prod

echo "[$(date)] === Done. Production trajectory: prod.xtc ==="
