import { it, expect, vi, afterEach } from 'vitest'
import { createVRShare } from './vr_share.js'
import { initPresentationControls } from '../viewer/presentation_controls.js'
afterEach(() => { document.body.innerHTML = '' })
it('controls only an active desktop presentation and deduplicates events', async () => {
  const onPerspective = vi.fn(), onEnd = vi.fn(), request = vi.fn(async () => ({ ok: true }))
  const controls = initPresentationControls({ onPerspective, onEnd })
  const vr = createVRShare({ request })
  await vr.activate({ sequence: 1, action: 'resume' })
  expect(onPerspective).not.toHaveBeenCalled()
  controls.setActive(true); controls.setPerspective(true)
  await vr.activate({ sequence: 2, action: 'pause' })
  await vi.waitFor(() => expect(controls.perspective).toBe(false))
  await vr.activate({ sequence: 2, action: 'resume' })
  expect(onPerspective).toHaveBeenCalledTimes(1)
  await vr.activate({ sequence: 3, action: 'resume' })
  await vi.waitFor(() => expect(controls.perspective).toBe(true))
  await vr.activate({ sequence: 4, action: 'create' })
  expect(onPerspective).toHaveBeenCalledTimes(2)
  await vr.activate({ sequence: 5, action: 'end' })
  expect(onEnd).toHaveBeenCalledOnce()
  expect(request.mock.calls.every(([url]) => url === '/api/vr/share-controls')).toBe(true)
  controls.dispose()
})
it('keeps failed perspective state retryable and exposes desktop errors', async () => {
  const controls = initPresentationControls({ onPerspective: async () => { throw Error('Offline') }, onEnd: vi.fn() })
  controls.setActive(true)
  const vr = createVRShare({ request: async () => ({ ok: true }) })
  await vr.activate({ sequence: 1, action: 'resume' })
  await vi.waitFor(() => expect(vr.state().failed).toBe(true))
  expect(vr.state().perspective).toBe(false)
  expect(vr.state().busy).toBe(false)
  controls.dispose()
})
