"""Enumerate topology terms changed or generated by a photoproduct graph delta."""

from __future__ import annotations

from collections import defaultdict
import json
from pathlib import Path
from typing import Any, Iterable

from backend.core.photoproduct_chemistry import load_chemical_definition


def _canonical_path(atoms: Iterable[str]) -> tuple[str, ...]:
    path = tuple(atoms)
    reverse = tuple(reversed(path))
    return min(path, reverse)


def enumerate_graph_terms(
    bonds: Iterable[tuple[str, str] | list[str]],
) -> dict[str, list[list[str]]]:
    canonical_bonds = {_canonical_path(bond) for bond in bonds}
    neighbors: dict[str, set[str]] = defaultdict(set)
    for first, second in canonical_bonds:
        if first == second:
            raise ValueError(f"self bond is invalid: {first}")
        neighbors[first].add(second)
        neighbors[second].add(first)
    angles = {
        _canonical_path((first, center, third))
        for center, attached in neighbors.items()
        for first in attached
        for third in attached
        if first != third
    }
    dihedrals = {
        _canonical_path((outer_1, center_1, center_2, outer_2))
        for center_1, center_2 in canonical_bonds
        for outer_1 in neighbors[center_1] - {center_2}
        for outer_2 in neighbors[center_2] - {center_1}
        if len({outer_1, center_1, center_2, outer_2}) == 4
    }
    return {
        "bonds": [list(item) for item in sorted(canonical_bonds)],
        "angles": [list(item) for item in sorted(angles)],
        "dihedrals": [list(item) for item in sorted(dihedrals)],
    }


def build_term_inventory(product: str, stereochemistry: str) -> dict[str, Any]:
    definition = load_chemical_definition(product, stereochemistry)
    precursor = definition.get("precursor_local_connectivity")
    if not isinstance(precursor, dict) or not precursor.get("bonds"):
        raise ValueError("chemical definition has no reviewed precursor_local_connectivity")
    reactant_bonds = [tuple(item) for item in precursor["bonds"]]
    added = [
        (item["atom_1"], item["atom_2"])
        for item in definition["graph_delta"]["bonds_added"]
    ]
    reactant = enumerate_graph_terms(reactant_bonds)
    product_graph = enumerate_graph_terms([*reactant_bonds, *added])
    generated = {
        category: [
            item for item in product_graph[category] if item not in reactant[category]
        ]
        for category in ("bonds", "angles", "dihedrals")
    }
    changed_order = [
        item
        for item in definition["graph_delta"]["bonds_retained"]
        if item.get("precursor_order") != item.get("product_order")
    ]
    affected_atoms = {
        atom
        for bond in [*added, *((x["atom_1"], x["atom_2"]) for x in changed_order)]
        for atom in bond
    }
    local_audit = {
        category: [
            item
            for item in product_graph[category]
            if affected_atoms.intersection(item)
        ]
        for category in ("bonds", "angles", "dihedrals")
    }
    return {
        "schema": "nadoc.photoproduct-bonded-term-inventory.v1",
        "product_id": definition["id"],
        "gate_effect": "none",
        "graph_scope": precursor["scope"],
        "affected_atoms": sorted(affected_atoms),
        "changed_bond_orders": changed_order,
        "newly_generated_terms": generated,
        "all_local_terms_requiring_type_or_parameter_audit": local_audit,
        "stereochemical_impropers": {
            "status": "review-required",
            "reason": "improper definitions and conventions cannot be inferred from graph connectivity",
            "centers": [item["atom"] for item in definition["product_stereocenters"]],
        },
        "parameter_status": "unassigned",
    }


def write_term_inventory(
    product: str, stereochemistry: str, output_path: Path
) -> dict[str, Any]:
    inventory = build_term_inventory(product, stereochemistry)
    if output_path.exists():
        raise FileExistsError(f"refusing to overwrite existing inventory: {output_path}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(inventory, indent=2) + "\n")
    return inventory
