#!/usr/bin/env node
/**
 * scaffold-tests.mjs — emit a vitest skeleton for a freshly-extracted module.
 *
 * This generates STRUCTURE, never the oracle. It reads an extracted module and
 * prints a `.test.js` skeleton: imports of the shared helpers, a `mountIds` stub
 * built from the `getElementById` ids the factory queries, a `makeDeps()` with
 * `vi.fn()` stubs for every `dep.method()` call site, and empty `describe`/`it`
 * blocks (one per export) with `// TODO` assertions. You fill the assertions by
 * hand — that judgment is deliberately NOT automated (auto-written assertions
 * just restate the implementation and pin nothing).
 *
 * Usage:
 *   node scripts/scaffold-tests.mjs src/ui/strand_groups_panel.js
 *   node scripts/scaffold-tests.mjs src/ui/strand_groups_panel.js > src/ui/strand_groups_panel.test.js
 *
 * Heuristic + regex-based on purpose (no AST dep): the output is a starting
 * point to edit, not a finished file. Re-read it before trusting it.
 */
import { readFileSync } from 'node:fs'
import { basename } from 'node:path'

const path = process.argv[2]
if (!path) {
  console.error('usage: node scripts/scaffold-tests.mjs <module.js>')
  process.exit(1)
}
const src = readFileSync(path, 'utf8')
const modName = basename(path).replace(/\.js$/, '')
const importPath = `./${basename(path)}`

// ── Exported functions ──────────────────────────────────────────────────────
const exports_ = [...src.matchAll(/export\s+function\s+(\w+)\s*\(([^)]*)\)/g)]
  .map(m => ({ name: m[1], params: m[2].trim() }))

// A factory is `initX({ a, b, ... })` — destructured-object first param.
const factory = exports_.find(e => /^init/.test(e.name) && /^\{/.test(e.params))
const pureFns = exports_.filter(e => e !== factory)

// Dep names from the factory's destructured param: initX({ store, api, ... })
let deps = []
if (factory) {
  const inner = factory.params.replace(/^\{|\}$/g, '')
  deps = inner.split(',').map(s => s.split(/[:=]/)[0].trim()).filter(Boolean)
}

// getElementById ids the module queries (→ mountIds stub).
const ids = [...new Set([...src.matchAll(/getElementById\(\s*['"]([^'"]+)['"]\s*\)/g)].map(m => m[1]))]

// Per-dep call sites. `depName.method(` → object of vi.fn() stubs;
// a direct `depName(` call (no dot) → the dep is itself a function → vi.fn().
const depMethods = {}      // dep → method names
const depIsFn = {}         // dep → true if called directly as a function
for (const d of deps) {
  const methodRe = new RegExp(`\\b${d}\\.(\\w+)\\s*\\(`, 'g')
  depMethods[d] = [...new Set([...src.matchAll(methodRe)].map(m => m[1]))]
  const callRe = new RegExp(`\\b${d}\\s*\\(`, 'g')
  depIsFn[d] = callRe.test(src)
}

// ── Emit ────────────────────────────────────────────────────────────────────
const L = []
const idsLiteral = ids.length
  ? `[${ids.map(i => `'${i}'`).join(', ')}]`
  : '[]'

L.push(`/**`)
L.push(` * Tests for ${modName}. SKELETON — fill every TODO with a real oracle.`)
L.push(` * Generated by scripts/scaffold-tests.mjs; structure only, no assertions.`)
L.push(` */`)
L.push(`import { describe, it, expect, vi, beforeEach } from 'vitest'`)
if (factory) {
  L.push(`import { createMockStore } from '../test-helpers/mock_store.js'`)
  if (ids.length) L.push(`import { mountIds, clearDom } from '../test-helpers/factory_dom.js'`)
}
const importNames = [...pureFns.map(f => f.name), ...(factory ? [factory.name] : [])]
L.push(`import { ${importNames.join(', ')} } from '${importPath}'`)
L.push('')

for (const fn of pureFns) {
  L.push(`describe('${fn.name} (pure)', () => {`)
  L.push(`  it('TODO: happy path', () => {`)
  L.push(`    // expect(${fn.name}(/* … */)).toEqual(/* … */)`)
  L.push(`  })`)
  L.push(`  it('TODO: null / empty / boundary', () => {})`)
  L.push(`})`)
  L.push('')
}

if (factory) {
  // Tags are guessed loosely; adjust button/input/canvas by hand.
  const tagGuess = id =>
    /btn|button|new|colors|close|save|create|cancel|gen/i.test(id) ? 'button'
    : /input|slider|size|search|name|seq/i.test(id) ? 'input'
    : /canvas|hist/i.test(id) ? 'canvas'
    : 'div'
  L.push(`// Adjust tags (button/input/canvas) where the factory needs them.`)
  if (ids.length) {
    L.push(`const DOM = {`)
    for (const id of ids) L.push(`  '${id}': '${tagGuess(id)}',`)
    L.push(`}`)
  }
  L.push('')
  L.push(`function makeDeps(initialState = {}) {`)
  for (const d of deps) {
    if (d === 'store') { L.push(`  const store = createMockStore(initialState)`); continue }
    const methods = depMethods[d] ?? []
    if (methods.length) {
      L.push(`  const ${d} = { ${methods.map(m => `${m}: vi.fn()`).join(', ')} }`)
    } else if (depIsFn[d]) {
      L.push(`  const ${d} = vi.fn()`)
    } else {
      L.push(`  const ${d} = {} // TODO: stub methods this factory calls`)
    }
  }
  L.push(`  return { ${deps.join(', ')} }`)
  L.push(`}`)
  L.push('')
  L.push(`beforeEach(() => { ${ids.length ? 'clearDom()' : ''} })`)
  L.push('')
  L.push(`describe('${factory.name}', () => {`)
  L.push(`  it('no-ops gracefully when DOM is absent', () => {`)
  L.push(`    const api = ${factory.name}(makeDeps())`)
  L.push(`    expect(api).toBeTruthy()`)
  L.push(`  })`)
  L.push('')
  L.push(`  it('TODO: mounts + wires its DOM', () => {`)
  if (ids.length) L.push(`    mountIds(DOM)`)
  L.push(`    const deps = makeDeps()`)
  L.push(`    ${factory.name}(deps)`)
  L.push(`    // document.getElementById('…').click()  → expect(deps.X.method).toHaveBeenCalledWith(…)`)
  L.push(`  })`)
  L.push(`})`)
  L.push('')
}

process.stdout.write(L.join('\n'))
