import { afterEach, expect, it, vi } from 'vitest'
import { mountInvitationLobby } from './invitation_lobby.js'
afterEach(() => { document.body.innerHTML = ''; vi.useRealTimers() })
it('waits through inactive, preparation, and network recovery, then opens only an active presentation', async () => {
  vi.useFakeTimers()
  document.body.innerHTML = '<main></main>'
  const request = vi.fn()
    .mockResolvedValueOnce({ ok: true, json: async () => ({ state: 'inactive' }) })
    .mockResolvedValueOnce({ ok: true, json: async () => ({ state: 'preparing' }) })
    .mockRejectedValueOnce(new Error('Network down'))
    .mockResolvedValue({ ok: true, json: async () => ({ state: 'active' }) })
  const onActive = vi.fn(), dispose = mountInvitationLobby({ base: '/meeting/design', fetch: request, onActive })
  await vi.advanceTimersByTimeAsync(0)
  expect(document.querySelector('h1').textContent).toBe('Presentation not active')
  expect(document.querySelector('main').inert).toBe(true)
  await vi.advanceTimersByTimeAsync(3000)
  expect(document.querySelector('h1').textContent).toBe('Preparing presentation…')
  expect(onActive).not.toHaveBeenCalled()
  await vi.advanceTimersByTimeAsync(3000)
  expect(document.body.textContent).toContain('Reconnecting automatically')
  await vi.advanceTimersByTimeAsync(3000)
  expect(onActive).toHaveBeenCalledOnce()
  expect(request.mock.calls.every(([url]) => url.endsWith('/availability'))).toBe(true)
  dispose()
  expect(document.querySelector('#presentation-waiting')).toBeNull()
  expect(vi.getTimerCount()).toBe(0)
})
it('stops polling a reset invitation and ignores a late response after leaving', async () => {
  vi.useFakeTimers()
  const request = vi.fn().mockResolvedValue({ status: 404 }), onActive = vi.fn()
  const dispose = mountInvitationLobby({ base: '/meeting/design', fetch: request, onActive })
  await vi.advanceTimersByTimeAsync(10000)
  expect(request).toHaveBeenCalledOnce()
  expect(document.body.textContent).toContain('Ask the presenter for a new link')
  dispose()
  let resolve
  const leave = mountInvitationLobby({ base: '/meeting/design', fetch: () => new Promise(r => { resolve = r }), onActive })
  leave(); resolve({ ok: true, json: async () => ({ state: 'active' }) })
  await vi.advanceTimersByTimeAsync(0)
  expect(onActive).not.toHaveBeenCalled()
})
