/** Provenance is independent of whether an operation is also available manually. */
export function autogeneratedGroups(entries) {
  const groups = entries.map(e => e.autogenerated_group_id || e.params?._generator?.group_id || null)
  // Older native histories retained provenance only on snapshot operations.
  // Recognize native children between matching snapshots, and the initial sweep.
  for (const group of new Set(groups.filter(Boolean))) {
    const first = groups.indexOf(group), last = groups.lastIndexOf(group)
    let start = first - 1
    while (start >= 0 && entries[start].feature_type === 'routing-cluster' && !groups[start]) start--
    const sweepCluster = entries[start]?.op_kind === 'sweep' ? `sweep_cluster_${entries[start].params?.sweep_id}` : null
    for (let i = first + 1; i < last; i++) {
      const e = entries[i]
      if (!groups[i] && (e.feature_type === 'routing-cluster' ||
          ['cluster_create', 'cluster_op'].includes(e.feature_type) && (e.cluster_id?.startsWith(`gen_${group}_`) || e.cluster_id === sweepCluster))) groups[i] = group
    }
    if (!entries[first].autogenerated_group_id) {
      if (entries[start]?.op_kind === 'sweep' && !groups[start]) {
        for (let i = start; i < first; i++) groups[i] = group
      }
    }
  }
  return groups
}

export function decorateAutogeneratedRail(rail, thumb, keys, ys, entries) {
  const groups = autogeneratedGroups(entries)
  const visibleGroups = keys.map(key => {
    const entry = entries[key.position]
    if (!entry) return null
    if (key.sub_position != null) {
      const child = entry.children?.[key.sub_position]
      return child?.autogenerated_group_id || child?.params?._generator?.group_id || groups[key.position]
    }
    return groups[key.position]
  })
  rail.querySelectorAll('.fl-notch').forEach(dot => {
    const i = Number(dot.dataset.notchIndex), group = visibleGroups[i]
    if (!group) return
    dot.classList.add('fl-autogenerated-dot')
    dot.title = 'This feature was autogenerated.'
    dot.setAttribute('aria-label', dot.title)
    Object.assign(dot.style, { left: '6px', width: '8px', height: '8px', borderRadius: '50%', background: '#f28c45' })
    if (i > 0 && visibleGroups[i - 1] === group) {
      const line = document.createElement('div')
      line.className = 'fl-notch fl-autogenerated-connection'
      line.style.cssText = `position:absolute;left:9px;top:${ys[i - 1]}px;width:2px;height:${ys[i] - ys[i - 1]}px;background:#f28c45;pointer-events:none;z-index:0`
      rail.insertBefore(line, thumb)
    }
  })
}
