import { expect, it } from 'vitest'
import { autogeneratedGroups, decorateAutogeneratedRail } from './autogenerated_feature_rail.js'

it('recognizes legacy native operations without coloring surrounding manual features', () => {
  const entries = [
    { feature_type: 'snapshot', op_kind: 'nanoparticle-create' },
    { feature_type: 'snapshot', op_kind: 'sweep', params: { sweep_id: 's' } },
    { feature_type: 'routing-cluster' },
    { params: { _generator: { group_id: 'g' } } },
    { feature_type: 'cluster_op', cluster_id: 'gen_g_attachment' },
    { feature_type: 'cluster_op', cluster_id: 'sweep_cluster_s' },
    { feature_type: 'snapshot', op_kind: 'manual' },
    { params: { _generator: { group_id: 'g' } } },
    { feature_type: 'cluster_op', cluster_id: 'gen_g_attachment' },
  ]
  expect(autogeneratedGroups(entries)).toEqual([null, 'g', 'g', 'g', 'g', 'g', null, 'g', null])
})

it('connects only adjacent generated features from the same run, including expanded children', () => {
  const entries = [{ autogenerated_group_id: 'a', children: [{}] }, {}, { autogenerated_group_id: 'b' }]
  const keys = [{ position: -2 }, { position: 0 }, { position: 0, sub_position: 0 }, { position: 1 }, { position: 2 }]
  const rail = document.createElement('div'), thumb = document.createElement('div')
  keys.forEach((_, i) => { const dot = document.createElement('div'); dot.className = 'fl-notch'; dot.dataset.notchIndex = i; rail.append(dot) })
  rail.append(thumb)
  decorateAutogeneratedRail(rail, thumb, keys, [0, 20, 40, 60, 80], entries)
  expect(rail.querySelectorAll('.fl-autogenerated-dot')).toHaveLength(3)
  expect(rail.querySelectorAll('.fl-autogenerated-connection')).toHaveLength(1)
  expect(rail.querySelector('.fl-autogenerated-dot').title).toBe('This feature was autogenerated.')
  expect(rail.querySelector('.fl-autogenerated-dot').style.background).toBe('rgb(242, 140, 69)')
})
