import { describe,it,expect,vi,beforeEach } from 'vitest'
vi.mock('./metric_graph.js',()=>({buildChartSpec:vi.fn(v=>v),drawChart:vi.fn(),SERIES_COLORS:['red','blue']}))
import { initMdSurfaceProfiles,surfaceProfileSeries } from './md_surface_profiles.js'
const value=()=>({frames:8,bulk_Na_mM:100,bulk_Cl_mM:100,reference_debye_nm:.96,screening_fit:{available:false,reason:'Insufficient signal'},distance_nm:[.1],edge_distance_nm:[.2],concentration_mM:{positive:{'Na+':[100]},negative:{'Cl-':[100]}},ionic_charge_e_nm3:{positive:[0],negative:[0]},residual_sheet_fraction:[1]})
const wall=id=>({job_id:id,prep_params:{graphene_only:true,graphene_pore_diameter_nm:0}})
beforeEach(()=>{document.body.innerHTML='<div id="md-metrics-surface-profiles"></div>'})
const open=()=>document.querySelector('[data-open]').click()
const calculate=()=>document.querySelector('form').dispatchEvent(new Event('submit',{cancelable:true,bubbles:true}))
describe('surface profiles',()=>{
 it('maps separate faces and edge-valued screening without mixing units',()=>{
  const series=surfaceProfileSeries(value())
  expect(series.concentration[0].points).toEqual([[.1,100]])
  expect(series.screening[0].points).toEqual([[.2,1]])
 })
 it('opens a popup, restores settings, recalculates edited inputs and replaces graphs',async()=>{
  const generate=vi.fn().mockResolvedValue({...value(),frames:16}),load=vi.fn().mockResolvedValue({...value(),options:{bins:60,dielectric:80}})
  initMdSurfaceProfiles({getSelectedJob:()=>wall('a'),generate,load})
  expect(document.querySelector('#md-metrics-surface-profiles input')).toBeNull()
  open()
  await vi.waitFor(()=>expect(document.querySelectorAll('dialog canvas')).toHaveLength(3))
  expect(document.querySelector('[name=bins]').value).toBe('60')
  document.querySelector('[name=bins]').value='72';calculate()
  await vi.waitFor(()=>expect(document.querySelector('[data-summary]').textContent).toContain('16 sampled frames'))
  expect(generate).toHaveBeenCalledWith('a',expect.objectContaining({bins:72,dielectric:80}))
  expect(document.querySelectorAll('dialog canvas')).toHaveLength(3)
  document.querySelector('[data-close]').click();expect(document.querySelector('dialog')).toBeNull()
 })
 it('rejects an inverted fit window and retains previous graphs when calculation fails',async()=>{
  const generate=vi.fn().mockRejectedValue(Error('No frames'))
  initMdSurfaceProfiles({getSelectedJob:()=>wall('a'),generate,load:async()=>value()});open()
  await vi.waitFor(()=>expect(document.querySelectorAll('canvas')).toHaveLength(3))
  document.querySelector('[name=fit_min_nm]').value='3';calculate();expect(generate).not.toHaveBeenCalled()
  expect(document.querySelector('[data-status]').textContent).toContain('greater')
  document.querySelector('[name=fit_min_nm]').value='.6';calculate()
  await vi.waitFor(()=>expect(document.querySelector('[data-status]').textContent).toContain('Previous graphs retained'))
  expect(document.querySelectorAll('canvas')).toHaveLength(3)
 })
 it('closes on selection change and ignores an in-flight result; production inherits applicability',async()=>{
  let resolve;let job=wall('a')
  const card=initMdSurfaceProfiles({getSelectedJob:()=>job,getJobs:()=>[wall('parent')],generate:()=>new Promise(r=>{resolve=r}),load:async()=>{throw Error('none')}})
  open();calculate();job={job_id:'production',parent_job_id:'parent'};card.sync();resolve(value());await Promise.resolve()
  expect(document.querySelector('dialog')).toBeNull()
  expect(document.querySelector('#md-metrics-surface-profiles').hidden).toBe(false)
  job={job_id:'b'};card.sync();expect(document.querySelector('#md-metrics-surface-profiles').hidden).toBe(true)
 })
})
