import { beforeEach, expect, it, vi } from 'vitest'
vi.mock('../api/client.js', () => ({ patchNanoparticle: vi.fn(), createNanoparticleBiotinDNA: vi.fn(), removeNanoparticleBiotinDNA: vi.fn() }))
import { patchNanoparticle, createNanoparticleBiotinDNA, removeNanoparticleBiotinDNA } from '../api/client.js'
import { openStreptavidinDialog } from './streptavidin_dialog.js'
beforeEach(() => { document.body.innerHTML = ''; vi.clearAllMocks(); HTMLDialogElement.prototype.showModal = function () { this.open = true } })
const change = (id, value, event = 'change') => { const e = document.getElementById(id); e.value = value; e.dispatchEvent(new Event(event)) }
it('uses publication counts, records an override and resets to the publication', async () => {
  const container = document.createElement('div'); document.body.append(container)
  patchNanoparticle.mockResolvedValue({})
  const saved = vi.fn()
  openStreptavidinDialog({ id: 'gold', diameter_nm: 10 }, { container, onSaved: saved })
  change('strep-reference', 'gurtovenko_2019')
  expect(document.getElementById('strep-count').value).toBe('6')
  change('strep-count', '4', 'input')
  document.getElementById('strep-apply').click()
  await vi.waitFor(() => expect(saved).toHaveBeenCalledOnce())
  expect(patchNanoparticle.mock.calls[0][1].coating).toMatchObject({ coverage_reference: 'gurtovenko_2019', count_override: 4 })
  openStreptavidinDialog({ id: 'gold', diameter_nm: 10 }, { container })
  change('strep-count', '1.5', 'input')
  expect(document.getElementById('strep-apply').disabled).toBe(true)
  document.getElementById('strep-reset').click()
  expect(document.getElementById('strep-count').value).toBe('7')
  document.getElementById('strep-apply').click()
  expect(patchNanoparticle.mock.calls[1][1].coating.count_override).toBeNull()
})

const appliedParticle = (mode = 'adsorption') => ({ id: 'gold', kind: 'gold_nanosphere', diameter_nm: 10, coating: { mode, poses: [{}, {}, {}], target_count: 3, count_override: 3, coverage_reference: 'gold_2007', spacer_nm: .3 } })
function open(particle) {
  const container = document.createElement('div'); document.body.append(container)
  return openStreptavidinDialog(particle, { container, compact: true })
}
it('requires an applied coating and rejects uncommitted coating changes', () => {
  open({ id:'gold', kind:'gold_nanosphere', diameter_nm:10 })
  expect(document.getElementById('strep-dna-count').disabled).toBe(true)
  expect(document.getElementById('strep-dna-create').disabled).toBe(true)
  expect(document.getElementById('strep-dna-current').textContent).toContain('Apply the strep coating first')
  document.body.innerHTML = ''; open(appliedParticle())
  expect(document.getElementById('strep-dna-create').disabled).toBe(false)
  change('strep-count','4','input')
  expect(document.getElementById('strep-dna-create').disabled).toBe(true)
  change('strep-count','3','input')
  expect(document.getElementById('strep-dna-create').disabled).toBe(false)
})
it('sends exact occupancy and requires automatic pockets for multiple strands', async () => {
  const p = appliedParticle()
  const attached = { ...p, biotin_dna: Array.from({ length: 6 }, (_, i) => ({ chain: 'C', tetramer_index: Math.floor(i / 2) })) }
  createNanoparticleBiotinDNA.mockResolvedValue({ design: { nanoparticles: [attached] } })
  const container = document.createElement('div'); document.body.append(container)
  const saved = vi.fn(), changed = vi.fn()
  openStreptavidinDialog(p, { container, compact: true, onSaved: saved, onChanged: changed })
  change('strep-dna-pocket','C','input')
  change('strep-dna-count','2','input')
  expect(document.getElementById('strep-dna-pocket').value).toBe('auto')
  expect(document.getElementById('strep-dna-pocket').disabled).toBe(true)
  expect(document.getElementById('strep-dna-current').textContent).toContain('6 DNA requested')
  document.getElementById('strep-dna-create').click()
  expect(createNanoparticleBiotinDNA).toHaveBeenCalledWith('gold', expect.objectContaining({dna_per_strep:2,pocket:'auto'}))
  await vi.waitFor(() => expect(changed).toHaveBeenCalledOnce())
  expect(document.getElementById('streptavidin-dialog')).not.toBeNull()
  expect(saved).not.toHaveBeenCalled()
  expect(document.getElementById('strep-dna-current').textContent).toContain('6 attached')
  expect(document.getElementById('strep-dna-create').disabled).toBe(true)
  expect(document.getElementById('strep-dna-remove').disabled).toBe(false)
  expect(document.getElementById('strep-apply').disabled).toBe(false)
  document.getElementById('strep-apply').click()
  expect(saved).toHaveBeenCalledOnce()
  expect(patchNanoparticle).not.toHaveBeenCalled()
})
it('refreshes removal in place and keeps Remove coating with step one', async () => {
  const p = appliedParticle()
  removeNanoparticleBiotinDNA.mockResolvedValue({ design: { nanoparticles: [p] } })
  open({ ...p, biotin_dna: [{ chain: 'C' }, { chain: 'C' }, { chain: 'C' }] })
  const left = document.querySelector('.strep-coating-controls'), right = document.querySelector('.strep-dna-controls')
  expect(left.lastElementChild.id).toBe('strep-remove')
  expect(right.lastElementChild.className).toBe('strep-actions')
  expect(document.getElementById('strep-apply').textContent).toBe('Apply')
  document.getElementById('strep-dna-remove').click()
  await vi.waitFor(() => expect(document.getElementById('strep-dna-create').disabled).toBe(false))
  expect(document.getElementById('streptavidin-dialog')).not.toBeNull()
  expect(document.getElementById('strep-remove').disabled).toBe(false)
})
it('caps tethered occupancy at three and restores valid controls after a placement failure', async () => {
  createNanoparticleBiotinDNA.mockRejectedValue(new Error('Nothing was attached.'))
  open(appliedParticle('biotin_tether'))
  expect(document.getElementById('strep-dna-count').max).toBe('3')
  change('strep-dna-count','4','input')
  expect(document.getElementById('strep-dna-create').disabled).toBe(true)
  change('strep-dna-count','2','input')
  document.getElementById('strep-dna-create').click()
  await vi.waitFor(() => expect(document.getElementById('strep-error').textContent).toBe('Nothing was attached.'))
  expect(document.getElementById('strep-dna-create').disabled).toBe(false)
  expect(document.getElementById('strep-dna-remove').disabled).toBe(true)
})
