import { it, expect, vi } from 'vitest'
import { initSweepPoints } from './sweep_points.js'

it('selects, edits in nm, adds in order, and deletes every point except origin', () => {
  const root = document.createElement('div'), changed = vi.fn()
  const editor = initSweepPoints(root, changed)
  const z = root.querySelector('[aria-label="Point Z (nm)"]')
  expect(z.step).toBe('1')
  expect(z.value).toBe('10')
  z.stepUp(); z.dispatchEvent(new Event('input'))
  expect(editor.getPoints()[1]).toEqual([0, 0, 11])
  root.querySelector('[aria-label="Add sweep point"]').click()
  expect(editor.getPoints()).toEqual([[0, 0, 0], [0, 0, 11], [0, 0, 22]])
  root.querySelectorAll('[role=option]')[0].click()
  expect(z.value).toBe('0'); expect(z.disabled).toBe(true)
  expect(root.querySelector('[aria-label="Delete point 0"]')).toBeNull()
  root.querySelector('[aria-label="Delete point 1"]').click()
  expect(editor.getPoints()).toEqual([[0, 0, 0], [0, 0, 22]])
  editor.select(1)
  expect(z.value).toBe('22'); expect(z.disabled).toBe(false)
  root.querySelector('[aria-label="Delete point 1"]').click()
  expect(editor.getPoints()).toEqual([[0,0,0]])
  expect(changed).toHaveBeenCalledTimes(4)
})

it('synchronizes scene selection and movement with the fields without moving the origin', () => {
  const root = document.createElement('div'), changed = vi.fn(), selected = vi.fn()
  const editor = initSweepPoints(root, changed, selected)
  editor.select(1); editor.move(1, [3.5, 2, 10])
  expect(selected).toHaveBeenLastCalledWith(1)
  expect(root.querySelector('[aria-label="Point X (nm)"]').value).toBe('3.5')
  editor.move(0, [1,2,3])
  expect(editor.getPoints()[0]).toEqual([0,0,0])
  expect(changed).toHaveBeenCalledTimes(1)
})

it('enables arbitrary orientation independently of XYZ, keeps point associations and protects attached origins', () => {
  const root = document.createElement('div')
  document.body.append(root)
  const editor = initSweepPoints(root, vi.fn(), null, () => [17, 29, 44])
  root.querySelector('[aria-label="Control point orientation"]').click()
  expect(editor.getOrientations()).toEqual([null, [17,29,44]])
  const twist = root.querySelector('[aria-label="Twist (degrees)"]')
  twist.value = '88'; twist.dispatchEvent(new Event('change'))
  expect(editor.getOrientations()[1]).toEqual([17,29,88])
  editor.move(1, [3,4,10])
  expect(editor.getOrientations()[1]).toEqual([17,29,88])
  root.querySelector('[aria-label="Add sweep point"]').click()
  editor.orient(2,[0,90,15])
  root.querySelector('[aria-label="Delete point 1"]').click()
  expect(editor.getOrientations()).toEqual([null,[0,90,15]])
  editor.setOrientations(editor.getOrientations(), true); editor.select(0)
  expect(root.querySelector('[aria-label="Control point orientation"]').disabled).toBe(true)
  editor.orient(0,[15,0,0]); expect(editor.getOrientations()[0]).toBeNull()
  editor.select(1); root.querySelector('[aria-label="Control point orientation"]').click()
  expect(editor.getOrientations()).toEqual([null,null])
  root.remove()
})

it('truncates displayed positions only and puts help in hover tooltips', () => {
  const root = document.createElement('div'), editor = initSweepPoints(root, vi.fn())
  editor.move(1, [1.239, -1.239, 10.000123])
  const x = root.querySelector('[aria-label="Point X (nm)"]')
  expect(x.value).toBe('1.23')
  expect(root.querySelector('[aria-label="Point Y (nm)"]').value).toBe('-1.23')
  expect(root.querySelectorAll('[role=option]')[1].textContent).toContain('1.23, -1.23, 10')
  editor.select(0); editor.select(1)
  expect(editor.getPoints()[1]).toEqual([1.239,-1.239,10.000123])
  x.value = '2.345678'; x.dispatchEvent(new Event('input')); x.dispatchEvent(new Event('blur'))
  expect(x.value).toBe('2.34')
  expect(editor.getPoints()[1][0]).toBe(2.345678)
  expect(root.querySelector('p.tool-help')).toBeNull()
  expect(root.querySelector('.sweep-coordinates').title).toContain('precision')
})
