import { it, expect, vi } from 'vitest'
import { initSweepPoints } from './sweep_points.js'

it('selects, edits in nm, adds in order, and deletes every point except origin', () => {
  const root = document.createElement('div'), changed = vi.fn()
  const editor = initSweepPoints(root, changed)
  const z = root.querySelector('[aria-label="Point Z (nm)"]')
  expect(z.step).toBe('1')
  expect(z.value).toBe('10')
  z.stepUp(); z.dispatchEvent(new Event('input'))
  expect(editor.getPoints()[1]).toEqual([0, 0, 11])
  root.querySelector('[aria-label="Add sweep point"]').click()
  expect(editor.getPoints()).toEqual([[0, 0, 0], [0, 0, 11], [0, 0, 22]])
  root.querySelectorAll('[role=option]')[0].click()
  expect(z.value).toBe('0'); expect(z.disabled).toBe(true)
  expect(root.querySelector('[aria-label="Delete point 0"]')).toBeNull()
  root.querySelector('[aria-label="Delete point 1"]').click()
  expect(editor.getPoints()).toEqual([[0, 0, 0], [0, 0, 22]])
  editor.select(1)
  expect(z.value).toBe('22'); expect(z.disabled).toBe(false)
  root.querySelector('[aria-label="Delete point 1"]').click()
  expect(editor.getPoints()).toEqual([[0,0,0]])
  expect(changed).toHaveBeenCalledTimes(4)
})

it('synchronizes scene selection and movement with the fields without moving the origin', () => {
  const root = document.createElement('div'), changed = vi.fn(), selected = vi.fn()
  const editor = initSweepPoints(root, changed, selected)
  editor.select(1); editor.move(1, [3.5, 2, 10])
  expect(selected).toHaveBeenLastCalledWith(1)
  expect(root.querySelector('[aria-label="Point X (nm)"]').value).toBe('3.5')
  editor.move(0, [1,2,3])
  expect(editor.getPoints()[0]).toEqual([0,0,0])
  expect(changed).toHaveBeenCalledTimes(1)
})
