import { test, expect } from '@playwright/test'
import { copyFile, mkdir, rm } from 'node:fs/promises'
import path from 'node:path'

const scratch = path.resolve(import.meta.dirname, '../../workspace/playwright_tests/__e2e__connectivity.nadoc')
test.beforeAll(async () => {
  await mkdir(path.dirname(scratch), { recursive: true })
  await copyFile(path.resolve(import.meta.dirname, '../../workspace/NP_gen_tests.nadoc'), scratch)
})
test.afterAll(async () => { await rm(scratch, { force: true }) })
test('Help Connectivity shows branch proposals and removes them when disabled', async ({ page }) => {
  test.setTimeout(90000)
  const errors=[]; page.on('pageerror', e=>errors.push(e.message))
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/?doc=e2e-connectivity&open=' + encodeURIComponent(scratch))
  await page.waitForFunction(()=>!!window.__nadocTest?.store)
  await expect.poll(()=>page.evaluate(()=>window.__nadocTest.store.getState().currentDesign?.nanoparticles?.length)).toBe(4)
  await expect(page.locator('#welcome-screen')).toBeHidden()
  await expect(page.locator('#file-load-progress')).toBeHidden()
  const before=await page.evaluate(()=>JSON.stringify(window.__nadocTest.store.getState().currentDesign))
  await page.locator('.menu-item').filter({hasText:'Help'}).first().hover()
  await page.locator('#menu-help-connectivity').click()
  const panel=page.locator('#connectivity-panel')
  await expect(panel).toBeVisible()
  await expect(page.locator('#menu-help-connectivity')).toHaveAttribute('aria-pressed','true')
  await expect(panel.locator('svg path')).toHaveCount(5)
  await expect(panel.locator('svg circle')).toHaveCount(4)
  await expect(panel.locator('svg')).toContainText('18HB')
  expect(await panel.locator('select option').count()).toBeGreaterThan(1)
  await expect.poll(()=>page.evaluate(()=>window.__nadocScene.children.filter(c=>c.userData.connectivityPreview).length)).toBe(1)
  await panel.getByRole('button', { name: 'Frame graph in 3D' }).click()
  await page.mouse.move(800, 500)
  // Capture the actual viewer and graph at desktop size for visual inspection.
  if(process.env.NADOC_CONNECTIVITY_SCREENSHOT) await page.screenshot({path:process.env.NADOC_CONNECTIVITY_SCREENSHOT})
  await panel.getByRole('checkbox', { name: 'Origami pathing preview' }).check()
  await expect(panel.locator('.connectivity-path-stats')).toContainText('6HB on all arms and stems')
  await expect(panel.locator('svg')).toContainText('12HB → 6HB + 6HB')
  const inventory = await page.evaluate(() => {
    const root = window.__nadocScene.children.find(c => c.userData.origamiPathPreview)
    return root.children.filter(c => c.userData.origamiHelixPath).map(c => c.userData.origamiHelixPath.kind)
  })
  expect(inventory.filter(k => k === 'bundle')).toHaveLength(30)
  expect(inventory.filter(k => k === 'junction-extension')).toHaveLength(12)
  await panel.getByRole('button', { name: 'Frame graph in 3D' }).click()
  await page.mouse.move(800, 500)
  if(process.env.NADOC_ORIGAMI_PATH_SCREENSHOT) await page.screenshot({path:process.env.NADOC_ORIGAMI_PATH_SCREENSHOT})
  await panel.getByRole('combobox', { name: 'Uniform bundle size' }).selectOption('12')
  await expect(panel.locator('.connectivity-path-stats')).toContainText('24HB at 2 shared sections')
  await panel.getByRole('checkbox', { name: 'Origami pathing preview' }).uncheck()
  expect(await page.evaluate(()=>window.__nadocScene.children.filter(c=>c.userData.origamiPathPreview).length)).toBe(0)
  const first=await panel.locator('svg').innerHTML()
  await panel.getByRole('combobox', { name: 'Connectivity candidate' }).selectOption('1')
  expect(await panel.locator('svg').innerHTML()).not.toBe(first)
  expect(await page.evaluate(()=>JSON.stringify(window.__nadocTest.store.getState().currentDesign))).toBe(before)
  await panel.getByRole('button',{name:'Close connectivity'}).click()
  await expect(panel).toBeHidden()
  expect(await page.evaluate(()=>window.__nadocScene.children.filter(c=>c.userData.connectivityPreview).length)).toBe(0)
  await page.locator('.menu-item').filter({hasText:'Help'}).first().hover()
  await page.locator('#menu-help-connectivity').click();await expect(panel).toBeVisible()
  expect(await page.evaluate(()=>window.__nadocScene.children.filter(c=>c.userData.connectivityPreview).length)).toBe(1)
  await page.locator('.menu-item').filter({hasText:'Help'}).first().hover()
  await page.locator('#menu-help-connectivity').click();await expect(panel).toBeHidden()
  expect(errors).toEqual([])
})

test('reviewed connectivity generates a routed origami in the current loadout', async ({ page }) => {
  test.setTimeout(120000)
  const errors=[]; page.on('pageerror', e=>errors.push(e.message))
  await page.setViewportSize({width:1600,height:1000})
  await page.goto('/?doc=e2e-connectivity-generation&open='+encodeURIComponent(scratch))
  await page.waitForFunction(()=>!!window.__nadocTest?.store)
  await expect.poll(()=>page.evaluate(()=>window.__nadocTest.store.getState().currentDesign?.nanoparticles?.length)).toBe(4)
  await expect(page.locator('#welcome-screen')).toBeHidden()
  await expect(page.locator('#file-load-progress')).toBeHidden()
  await page.locator('.menu-item').filter({hasText:'Help'}).first().hover()
  await page.locator('#menu-help-connectivity').click()
  const panel=page.locator('#connectivity-panel')
  await panel.getByRole('checkbox',{name:'Origami pathing preview'}).check()
  await panel.getByRole('button',{name:'Frame graph in 3D'}).click()
  await panel.getByRole('button',{name:'Generate this origami…'}).click()
  const generate=page.getByRole('button',{name:'Generate in current loadout'})
  await expect(generate).toBeEnabled({timeout:60000})
  await generate.click()
  await expect(page.getByText('Added routed origami with 4 blunt-end attachment faces.',{exact:false})).toBeVisible({timeout:60000})
  const design=await page.evaluate(()=>window.__nadocTest.store.getState().currentDesign)
  expect(design.helices).toHaveLength(18)
  expect(design.strands.filter(s=>s.strand_type==='scaffold')).toHaveLength(1)
  expect(design.nanoparticles).toHaveLength(4)
  await expect(panel).toBeHidden()
  if(process.env.NADOC_GENERATED_CONNECTIVITY_SCREENSHOT) {
    await page.keyboard.press('Escape')
    await page.mouse.move(800,500)
    await page.screenshot({path:process.env.NADOC_GENERATED_CONNECTIVITY_SCREENSHOT})
  }
  expect(errors).toEqual([])
})
