import { expect, test } from '@playwright/test'

// Read-only modal exercise: no workspace designs, decisions, downloads or saved state.
// Server disables session cache; standard teardown/reporter removes test artifacts.
test('CPD progress shows real evidence, rotates, inspects a failed bond and closes', async ({ page }, testInfo) => {
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.route('**/api/mrdna/jobs*', route => route.fulfill({ json: [] }))
  await page.goto('/')
  const help = page.locator('#menu-bar > .menu-item').filter({ has: page.locator('#menu-help-cpd-progress') })
  await help.hover(); await page.locator('#menu-help-cpd-progress').click()
  const modal = page.locator('.cpd-progress-modal')
  await expect(modal).toBeVisible()
  await expect(modal).toContainText('DNA short pilot: 6/6 assessed (pass)')
  await modal.getByLabel('Photoproduct structure').selectOption('syn-core-corrected')
  await expect(modal).toContainText('longer sampling and convergence remain unvalidated')
  await expect(modal.locator('[data-atom]')).toHaveCount(36)
  await modal.getByLabel('Photoproduct structure').selectOption('syn-boundary-1')
  await expect(modal.locator('[data-atom]')).toHaveCount(49)
  const bond = modal.locator("[data-bond=\"1:C1'—1:N1\"]")
  await bond.focus()
  await expect(modal.locator('.cpd-progress__details')).toContainText('Independent glycosidic-bond geometry')
  await expect(modal.locator('.cpd-progress__details')).toContainText('+0.04025 Å')
  await page.screenshot({ path: testInfo.outputPath('cpd-progress.png') })
  const svg = modal.getByLabel('Interactive CPD atomic structure')
  await svg.scrollIntoViewIfNeeded()
  const before = await modal.locator('[data-atom]').first().getAttribute('cx'); const box = await svg.boundingBox()
  await page.mouse.move(box.x + 20, box.y + 20); await page.mouse.down(); await page.mouse.move(box.x + 80, box.y + 50, { steps: 5 }); await page.mouse.up()
  expect(await modal.locator('[data-atom]').first().getAttribute('cx')).not.toBe(before)
  await modal.getByLabel('Photoproduct structure').selectOption('syn-corrected-1')
  await modal.locator("[data-bond=\"1:C1'—1:N1\"]").focus()
  await expect(modal.locator('.cpd-progress__details')).toContainText('+0.02880 Å error; before +0.02602 Å')
  await expect(modal.locator('.cpd-progress__details')).toContainText('0 newly failing bonds/angles')
  await expect(modal).toContainText('Corrected training minimum')
  await modal.getByLabel('Validation scope').selectOption('local')
  for (const id of ['syn-core-corrected', 'syn-corrected-1', 'syn-corrected-2']) {
    await modal.getByLabel('Photoproduct structure').selectOption(id)
    await expect(modal.locator('[data-atom]:not([fill="#35bd7c"])')).toHaveCount(0)
    await expect(modal.locator('[data-bond]:not([stroke="#35bd7c"])')).toHaveCount(0)
  }
  await page.screenshot({ path: testInfo.outputPath('cpd-progress-corrected.png') })
  await modal.getByLabel('Photoproduct structure').selectOption('anti-boundary-1')
  await expect(modal).toContainText('Audited MP2/6-31G(d) optimized QM fragment')
  await modal.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(modal).toHaveCount(0)
  expect(errors).toEqual([])
})

test('all eight CPD isomers show identifiable DNA attachments and adjustable orientation', async ({ page }) => {
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.route('**/api/mrdna/jobs*', route => route.fulfill({ json: [] }))
  await page.goto('/')
  await page.locator('#menu-bar > .menu-item').filter({ has: page.locator('#menu-help-cpd-progress') }).hover()
  await page.locator('#menu-help-cpd-progress').click()
  const modal = page.locator('.cpd-progress-modal')
  await expect(modal.locator('[data-isomer]')).toHaveCount(8)
  if (process.env.CPD_PROGRESS_SCREENSHOT) await page.screenshot({ path: process.env.CPD_PROGRESS_SCREENSHOT.replace('.png', '-gallery.png') })
  const svg = modal.getByLabel('Interactive CPD atomic structure')
  const cards = await modal.locator('[data-isomer]').evaluateAll(nodes => nodes.map(n => n.dataset.isomer))
  for (const id of cards) {
    await modal.locator(`[data-isomer="${id}"]`).click()
    await expect(modal.getByLabel('Photoproduct structure')).toHaveValue(id)
    await expect(svg.locator('[data-direction]')).toHaveCount(4)
    await expect(svg.locator('[data-backbone-bead]')).toHaveCount(2)
    await expect(svg.locator('[data-crosslink]')).toHaveCount(2)
    await expect(modal.locator('.cpd-progress__details')).toContainText('Ordered C5 configurations')
    if (id !== 'tt-cpd-cis-syn') await expect(modal).toContainText('Estimated conformer')
    const links = await svg.locator('[data-crosslink]').evaluateAll(nodes => nodes.map(n => n.dataset.bond))
    expect(links).toEqual(id.includes('anti') ? ['1:C5—2:C6', '1:C6—2:C5'] : ['1:C5—2:C5', '1:C6—2:C6'])
  }
  await modal.locator('[data-isomer="tt-cpd-cis-anti-i"]').click()
  const bead = svg.locator("[data-atom=\"1:O5'\"]")
  const before = await bead.getAttribute('cx')
  const coreBefore = await svg.locator('[data-atom="1:C5"]').getAttribute('cx')
  await modal.getByLabel('Endpoint 1 sugar rotation').fill('90')
  expect(await bead.getAttribute('cx')).not.toBe(before)
  expect(await svg.locator('[data-atom="1:C5"]').getAttribute('cx')).toBe(coreBefore)
  await modal.getByRole('button', { name: 'Reset view', exact: true }).click()
  expect(await bead.getAttribute('cx')).toBe(before)
  await modal.getByLabel('Show sugar–phosphate context').uncheck()
  await expect(svg.locator('[data-direction]')).toHaveCount(0)
  await expect(svg.locator('[data-crosslink]')).toHaveCount(2)
  await modal.getByLabel('Show sugar–phosphate context').check()
  await svg.scrollIntoViewIfNeeded()
  if (process.env.CPD_PROGRESS_SCREENSHOT) await page.screenshot({ path: process.env.CPD_PROGRESS_SCREENSHOT })
  await modal.getByRole('button', { name: 'Reload evidence', exact: true }).click()
  await expect(modal.getByLabel('Photoproduct structure')).toHaveValue('tt-cpd-cis-anti-i')
  await expect(svg.locator('[data-direction]')).toHaveCount(4)
  await modal.getByRole('button', { name: 'Close', exact: true }).click()
  expect(errors).toEqual([])
})

test('anti campaign distinguishes QM minima from failed additive training', async ({ page }, testInfo) => {
  await page.route('**/api/mrdna/jobs*', route => route.fulfill({ json: [] }))
  await page.goto('/')
  await page.locator('#menu-bar > .menu-item').filter({ has: page.locator('#menu-help-cpd-progress') }).hover()
  await page.locator('#menu-help-cpd-progress').click()
  const modal = page.locator('.cpd-progress-modal')
  await expect(modal).toContainText('basin coverage and energetic transfer remain unresolved')
  await modal.getByLabel('Photoproduct structure').selectOption('anti-boundary-2')
  await expect(modal).toContainText('141 internal modes; 0 imaginary')
  await expect(modal).not.toContainText('Stopped/deferred')
  await modal.getByLabel('Photoproduct structure').selectOption('anti-additive-endpoint-2')
  await expect(modal).toContainText('geometry training failed')
  await expect(modal).toContainText('84 points; 12 bracketed curves')
  await expect(modal).toContainText('none accepted or exported')
  await page.screenshot({ path: testInfo.outputPath('anti-campaign.png') })
})
