import { expect, test } from '@playwright/test'

test('gold creation popup updates optical references and creates the entered size', async ({ page }) => {
  test.setTimeout(120_000)
  await page.route(/\/api\/(md|oxdna)\//, route => route.abort())
  await page.goto('/')
  await page.locator('.menu-item').filter({ hasText: 'File' }).first().hover()
  await page.click('#menu-file-new')
  await page.fill('#new-design-name', '__e2e__gold_creation')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.locator('#welcome-screen')).not.toBeVisible()
  await page.waitForFunction(() => Boolean(window.__nadocTest?.nanoparticles))
  await expect(page.locator('#menu-item-tools')).not.toHaveClass(/disabled/)
  await page.locator('#menu-item-tools > button').click()
  await page.locator('.submenu-item').filter({ has: page.locator('#menu-tools-gold-nanosphere') }).hover()
  await page.click('#menu-tools-gold-nanosphere')
  const dialog = page.getByRole('dialog', { name: 'Gold nanosphere', exact: true })
  await expect(dialog).toBeVisible()
  await expect(page.locator('#gold-spectrum polyline')).toHaveCount(3)
  await expect(page.locator('#gold-coating')).toHaveCount(0)
  const initial = await page.locator('#gold-epsilon').textContent()
  await page.fill('#gold-diameter', '80')
  await expect(page.locator('#gold-epsilon')).not.toHaveText(initial)
  await expect(page.locator('.gold-nearest')).toContainText('80')
  await page.fill('#gold-diameter', '150')
  await expect(page.locator('#gold-optics-content')).toBeHidden()
  await expect(page.locator('#gold-optics-status')).toContainText('unavailable')
  await page.fill('#gold-diameter', '23.5')
  await expect(page.locator('#gold-optics-status')).toContainText('size-interpolated')
  await page.screenshot({ path: '/tmp/nadoc-gold-creation.png' })
  await page.click('#gold-create')
  await expect(dialog).toHaveCount(0, { timeout: 60_000 })
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.rendered()[0]?.diameterNm)).toBe(23.5)
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.gizmoAttached())).toBe(true)
  await page.evaluate(() => document.getElementById('menu-edit-undo').click())
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.rendered().length)).toBe(0)
  await page.evaluate(() => document.getElementById('menu-edit-redo').click())
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.rendered()[0]?.diameterNm)).toBe(23.5)
})
