import { expect, test } from '@playwright/test'
test('create one gold, one strep and one biotin DNA through conjugation manager', async ({ page }) => {
  test.setTimeout(180000)
  await page.route(/\/api\/(md|oxdna)\//, route => route.abort())
  await page.goto('/')
  await page.locator('.menu-item').filter({ hasText: 'File' }).first().hover()
  await page.click('#menu-file-new')
  await page.fill('#new-design-name', '__e2e__gold_strep_dna')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await page.waitForFunction(() => Boolean(window.__nadocTest?.nanoparticles))
  await page.evaluate(async () => {
    await window.__nadocTest.nanoparticles.create(10)
    await window.__nadocTest.nanoparticles.conjugation.open(window.__nadocTest.store.getState().currentDesign.nanoparticles[0].id)
  })
  await page.selectOption('#np-conj-scheme', 'streptavidin')
  await page.fill('#strep-count', '1')
  await expect(page.locator('#strep-dna-create')).toBeDisabled()
  await page.click('#strep-apply')
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toHaveCount(0, { timeout: 60000 })
  await page.evaluate(async () => window.__nadocTest.nanoparticles.conjugation.open(window.__nadocTest.store.getState().currentDesign.nanoparticles[0].id))
  await expect(page.locator('#strep-dna-create')).toBeEnabled()
  await page.fill('#strep-dna-sequence', 'ACGTACGTACGTACGT')
  const attached = page.waitForResponse(r => r.url().endsWith('/biotin-dna') && r.request().method() === 'POST')
  await page.click('#strep-dna-create')
  const response = await attached
  expect(response.status(), await response.text()).toBe(200)
  expect((await response.json()).design.strands).toHaveLength(1)
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toBeVisible()
  await expect(page.locator('#np-conj-preview-census')).toContainText('1 strep · 1 DNA / strep')
  await page.click('#strep-apply')
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toHaveCount(0, { timeout: 60000 })
  const audit = () => page.evaluate(() => {
    const d=window.__nadocTest.store.getState().currentDesign
    return { proteins:d.nanoparticles[0].coating.poses.length, dna:d.strands.length, core:d.nanoparticles[0].oxdna_fixed_core, attached:d.nanoparticles[0].biotin_dna.length }
  })
  await expect.poll(audit).toEqual({ proteins:1,dna:1,core:true,attached:1 })
  await page.evaluate(() => window.__nadocTest.applyCameraPoseForTest({position:[22,18,25],target:[0,0,0]}))
  await page.screenshot({path:'/tmp/nadoc-gold-strep-dna.png'})
  await page.evaluate(async () => window.__nadocTest.nanoparticles.conjugation.open(window.__nadocTest.store.getState().currentDesign.nanoparticles[0].id))
  await expect(page.locator('#np-conj-preview-census')).toContainText('1 strep · 1 DNA / strep')
  await expect(page.locator('#np-conjugate-preview canvas')).toBeVisible()
  await page.click('#np-conj-x')
  await page.evaluate(() => document.getElementById('menu-edit-undo').click())
  await expect.poll(audit).toEqual({ proteins:1,dna:0,core:false,attached:0 })
  await page.evaluate(() => document.getElementById('menu-edit-redo').click())
  await expect.poll(audit).toEqual({ proteins:1,dna:1,core:true,attached:1 })
})
