import { test, expect } from '@playwright/test'
import { loadScaffoldedPart, trackConsoleErrors } from './helpers/scene_harness.js'

// Persistence inventory: __e2e__linear-pattern*.nadoc and its project revisions,
// removed on every outcome by global-teardown.js. Session caching is disabled.
// Screenshots use testInfo.outputPath only, cleaned by artifact-cleanup-reporter.
test('create a linear grid, edit both pattern types through history, and undo/redo', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  await page.setViewportSize({ width: 1800, height: 1000 })
  const errors = trackConsoleErrors(page)
  page.on('response', async response => {
    if (response.status() >= 400) console.log('HTTP failure', response.status(), response.url(), await response.text().catch(() => ''))
  })
  await loadScaffoldedPart(page, { doc: 'e2e-linear-pattern', name: 'linear-pattern' })
  const source = await page.evaluate(async () => {
    const { store } = await import('/src/state/store.js')
    const api = await import('/src/api/client.js')
    const helix = store.getState().currentDesign.helices[0].id
    for (let i = 1; i <= 7; i++) await api.createCluster({ name: `Pattern source ${i}`, helix_ids: [helix] })
    return store.getState().currentDesign.cluster_transforms.find(c => c.helix_ids.length).id
  })
  const helixCount = () => page.evaluate(async () => (await import('/src/state/store.js')).store.getState().currentDesign.helices.length)
  async function openTool(kind) {
    await page.locator('#right-tab-strip [data-tab=clustering]').click()
    await page.getByRole('button', { name: 'Tools', exact: true }).hover()
    await page.locator(`#menu-tools-${kind}-pattern`).click()
    await page.locator(`#cluster-list [data-cluster-id="${source}"]`).click()
    await expect(page.locator(`#${kind}-pattern-panel .cp-panel-body`)).toBeVisible()
  }
  await openTool('linear')
  const panel = page.locator('#linear-pattern-panel')
  for (const name of ['Clusters', 'Direction 1', 'Info']) await expect(panel.getByRole('group', { name, exact: true })).toHaveCSS('border-top-width', '1px')
  const clusterList = panel.getByRole('group', { name: 'Available clusters', exact: true })
  await expect(clusterList).toHaveCSS('overflow-y', 'auto')
  expect(await clusterList.evaluate(node => node.scrollHeight > node.clientHeight)).toBe(true)
  await clusterList.evaluate(node => { node.scrollTop = node.scrollHeight })
  expect(await clusterList.evaluate(node => node.scrollTop)).toBeGreaterThan(0)
  await expect(page.getByRole('button', { name: 'Direction 2 Z', exact: true })).toBeHidden()
  await page.getByRole('checkbox', { name: '2D pattern' }).check()
  await expect(panel.getByRole('group', { name: 'Direction 2', exact: true })).toHaveCSS('border-top-width', '1px')
  for (const [number, vector] of [[1, [3, 4, 0]], [2, [-4, 3, 0]]]) {
    await page.getByRole('button', { name: `Direction ${number} Custom`, exact: true }).click()
    for (const [i, axis] of ['X', 'Y', 'Z'].entries()) await page.getByRole('spinbutton', { name: `Direction ${number} vector ${axis}`, exact: true }).fill(String(vector[i]))
  }
  await page.getByRole('spinbutton', { name: 'Spacing 1 (nm)', exact: true }).fill('14')
  await page.getByRole('button', { name: 'Increase spacing 1 by 1 nm', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: 'Spacing 1 (nm)', exact: true })).toHaveValue('15')
  await page.getByRole('button', { name: 'Increase instances 2 by 1 instance', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: 'Instances 2', exact: true })).toHaveValue('3')
  await page.getByRole('button', { name: 'Decrease instances 2 by 1 instance', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Spacing 2 (nm)', exact: true }).fill('20')
  await expect(page.locator('[aria-label="New BP created"]')).toHaveText('1,000')
  await expect(page.locator('[aria-label="Total after pattern"]')).toHaveText('1,200')
  expect(await helixCount()).toBe(1)
  expect(await page.evaluate(() => window.__nadocTest.scene.getObjectByName('linearPatternPreview').children.length)).toBe(5)
  await page.evaluate(() => window.__nadocTest.applyCameraPoseForTest({ target: [15, 10, 34], position: [150, 130, 180], up: [0, 1, 0] }))
  await page.screenshot({ path: testInfo.outputPath('linear-preview.png') })
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect.poll(helixCount).toBe(6)
  await page.evaluate(async () => { await (await import('/src/api/client.js')).undo() })
  await expect.poll(helixCount).toBe(1)
  await page.evaluate(async () => { await (await import('/src/api/client.js')).redo() })
  await expect.poll(helixCount).toBe(6)
  await openTool('circular')
  await page.getByRole('spinbutton', { name: 'Instances', exact: true }).fill('3')
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect.poll(helixCount).toBe(8)
  await page.locator('.left-tab-btn[data-tab="feature-log"]').click()
  // Editing the earlier linear pattern must preserve the later circular copies.
  await page.locator('#feature-log-panel-body button[title^="Edit Linear pattern:"]').click()
  await expect(page.getByRole('dialog', { name: 'Edit Linear Pattern' })).toBeVisible()
  await expect(page.getByRole('spinbutton', { name: 'Direction 1 vector X', exact: true })).toHaveValue('3')
  await page.getByRole('spinbutton', { name: 'Direction 1 vector Z', exact: true }).fill('1')
  await page.getByRole('spinbutton', { name: 'Instances 1', exact: true }).fill('2')
  await page.getByRole('spinbutton', { name: 'Spacing 1 (nm)', exact: true }).fill('-15')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect.poll(helixCount).toBe(6)
  await page.locator('#feature-log-panel-body button[title^="Edit Circular pattern:"]').click()
  await page.getByRole('spinbutton', { name: 'Instances', exact: true }).fill('2')
  await page.getByRole('spinbutton', { name: 'Total angle (degrees)', exact: true }).fill('180')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect.poll(helixCount).toBe(5)
  expect(await page.evaluate(async () => (await import('/src/state/store.js')).store.getState().currentDesign.feature_log.find(e => e.op_kind === 'linear-pattern').params.vector)).toEqual([3, 4, 1])
  await page.evaluate(async () => { await (await import('/src/api/client.js')).undo() })
  await expect.poll(helixCount).toBe(6)
  await page.evaluate(async () => { await (await import('/src/api/client.js')).redo() })
  await expect.poll(helixCount).toBe(5)
  expect(await page.evaluate(async () => (await import('/src/state/store.js')).store.getState().currentDesign.feature_log.filter(e => e.op_kind?.endsWith('-pattern')).length)).toBe(2)
  await page.evaluate(async () => {
    const api = await import('/src/api/client.js')
    const { store } = await import('/src/state/store.js')
    const path = store.getState().currentDesign.metadata.identity_last_known_path
    if (!path?.startsWith('__e2e__')) throw new Error('Expected a disposable test design path')
    if (!await api.saveDesignToWorkspace(path)) throw new Error('Save failed')
    if (!await api.loadDesign(`workspace/${path}`)) throw new Error('Reload failed')
  })
  await expect.poll(helixCount).toBe(5)
  await page.evaluate(() => window.__nadocTest.applyCameraPoseForTest({ target: [0, 10, 34], position: [160, 140, 190], up: [0, 1, 0] }))
  await page.screenshot({ path: testInfo.outputPath('linear-reloaded.png') })
  expect(errors).toEqual([])
})
