import {test,expect} from '@playwright/test'
const API=process.env.NADOC_E2E_API_BASE || 'http://127.0.0.1:8001'
const owned=new Set(),pending=[]
test.afterEach(async({request})=>{
 await Promise.allSettled(pending)
 const records=await (await request.get(`${API}/api/md/setup-presets`)).json()
 for(const r of records.filter(r=>owned.has(r.id)))expect((await request.delete(`${API}/api/md/setup-presets/${r.id}?revision=${r.revision}`)).ok()).toBeTruthy()
 const remaining=await (await request.get(`${API}/api/md/setup-presets`)).json();expect(remaining.filter(r=>owned.has(r.id))).toEqual([])
 owned.clear();pending.length=0
})
// Persistent artifacts: two __e2e__ documents (global teardown) and exact API-created preset IDs (afterEach above).
test('workspace presets create, select across designs, overwrite, and delete all lower-card settings',async({page},info)=>{
 page.on('response',r=>{if(r.request().method()==='POST' && r.url().endsWith('/api/md/setup-presets'))pending.push(r.json().then(data=>{if(data.id)owned.add(data.id)}))})
 await page.goto('/')
 async function createDesign(name){
  await page.locator('#menu-file-new').evaluate(el=>el.click());await page.fill('#new-design-name',name);await page.getByRole('dialog').getByRole('button',{name:'Create',exact:true}).click()
  await expect.poll(()=>page.evaluate(()=>window.__nadocTest.store.getState().currentDesign?.metadata?.name)).toBe(name)
 }
 await createDesign('__e2e__preset-source')
 await page.locator('.left-tab-btn[data-tab="dynamics"]').click()
 if(await page.locator('#simulate-body').evaluate(el=>getComputedStyle(el).display==='none'))await page.click('#simulate-heading')
 await page.click('.engine-selector-btn[data-engine="namd"]')
 const preset=page.locator('#md-setup-presets'),select=preset.locator('select')
 expect(await page.evaluate(()=>!!(document.getElementById('md-setup-presets').compareDocumentPosition(document.getElementById('md-benchmark-mount'))&Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
 await page.click('#md-box-solvent-toggle')
 await page.selectOption('#md-box-salt','custom')
 await page.fill('#md-box-na','175');await page.fill('#md-box-mg','0')
 await page.click('#md-surface-toggle')
 for(const key of ['hard-surface','screening','peg'])await page.locator(`#md-${key}-settings > summary`).click()
 await page.check('#md-screening-enable');await page.fill('#md-screening-charge','-0.03')
 await page.fill('#md-surface-offset','2')
 await page.check('#md-peg-enable');await page.fill('#md-peg-repeat_units','80');await page.locator('#md-peg-repeat_units').press('Tab')
 await page.locator('#md-anchors-stiffness').evaluate(el=>{el.value='1';el.dispatchEvent(new Event('change',{bubbles:true}))})
 await page.locator('#md-efield-mag').evaluate(el=>{el.value='4';el.dispatchEvent(new Event('input',{bubbles:true}))})
 await preset.getByRole('button',{name:'Create',exact:true}).click()
 await preset.getByLabel('Preset name').fill('__e2e__Brush screening')
 const saved=page.waitForResponse(r=>r.request().method()==='POST' && r.url().endsWith('/api/md/setup-presets'))
 await preset.getByRole('button',{name:'Save preset',exact:true}).click()
 const response=await saved;expect(response.ok()).toBeTruthy();const record=await response.json();owned.add(record.id)
 expect(record.settings.controls['md-box-na'].value).toBe('175')
 expect(record.settings.controls['md-screening-charge'].value).toBe('-0.03')
 expect(record.settings.controls['md-anchors-stiffness'].value).toBe('1')
 expect(record.settings.peg.spec.repeat_units).toBe(80)
 await expect(preset.locator('[role=status]')).toContainText('Created')
 await createDesign('__e2e__preset-target')
 await select.selectOption(record.id)
 await expect(preset.locator('[role=status]')).toContainText('Applied')
 await expect(page.locator('#md-box-na')).toHaveValue('175')
 await expect(page.locator('#md-screening-charge')).toHaveValue('-0.03')
 await expect(page.locator('#md-surface-offset')).toHaveValue('2')
 await expect(page.locator('#md-anchors-stiffness')).toHaveValue('1')
 await expect(page.locator('#md-efield-mag')).toHaveValue('4')
 await expect(page.locator('#md-peg-repeat_units')).toHaveValue('80')
 expect(await page.evaluate(()=>!!window.__nadocScene.getObjectByName('Graphene nanopore preview')?.visible)).toBe(false)
 await page.locator('#md-peg-repeat_units').evaluate(el=>{el.value='120';el.dispatchEvent(new Event('input',{bubbles:true}))})
 await preset.getByRole('button',{name:'Overwrite',exact:true}).click()
 await expect(preset.locator('[role=status]')).toContainText('revision 2')
 await page.check('#md-two-electrodes-enable')
 await page.locator('#md-two-electrodes-settings > summary').click()
 await page.fill('#md-two-electrodes-gap','15')
 await preset.getByRole('button',{name:'Overwrite',exact:true}).click()
 await expect(preset.locator('[role=status]')).toContainText('revision 3')
 await page.check('#md-hard-surface-enable')
 await select.selectOption('')
 await select.selectOption(record.id)
 await expect(page.locator('#md-two-electrodes-enable')).toBeChecked()
 await expect(page.locator('#md-hard-surface-enable')).not.toBeChecked()
 await expect(page.locator('#md-two-electrodes-gap')).toHaveValue('15')
 await preset.screenshot({path:info.outputPath('setup-presets.png')})
 await preset.getByRole('button',{name:'Delete',exact:true}).click()
 await expect(preset.locator('[role=status]')).toContainText('Deleted')
 await expect(select.locator(`option[value="${record.id}"]`)).toHaveCount(0)
 await expect(page.locator('#md-peg-repeat_units')).toHaveValue('120')
})
