import {test,expect} from '@playwright/test'
// Only __e2e__ documents persist; global teardown removes them. No surface-library writes or jobs.
async function open(page,name){
 await page.goto('/')
 await page.locator('#menu-file-new').evaluate(el=>el.click())
 await page.fill('#new-design-name',name)
 await page.getByRole('button',{name:'Create',exact:true}).click()
 await expect.poll(()=>page.evaluate(()=>window.__nadocTest.store.getState().currentDesign?.metadata?.name)).toBe(name)
 await page.locator('.left-tab-btn[data-tab="dynamics"]').click()
 if(await page.locator('#simulate-body').evaluate(el=>getComputedStyle(el).display==='none'))await page.click('#simulate-heading')
 await page.click('.engine-selector-btn[data-engine="namd"]')
 await page.click('#md-surface-toggle')
 await page.locator('#md-peg-settings > summary').click()
}
test('PEG coating is inline, retains disabled settings, and never creates a surface library record',async({page},info)=>{
 const libraryWrites=[];page.on('request',r=>{if(r.method()==='POST' && r.url().endsWith('/md/peg-surfaces'))libraryWrites.push(r.url())})
 await open(page,'__e2e__inline-peg')
 await page.check('#md-peg-enable')
 await expect(page.locator('#md-hard-surface-enable')).toBeChecked()
 await page.fill('#md-peg-repeat_units','80')
 await page.fill('#md-peg-density_per_nm2','0.1')
 await page.locator('[data-review-coating]').click()
 await expect(page.locator('#namd-peg-surfaces [role=status]')).toContainText('40 chains')
 await expect(page.locator('[role=dialog]')).toHaveCount(0)
 await expect(page.locator('[data-new-surface],[data-remove-coating]')).toHaveCount(0)
 await expect.poll(()=>page.evaluate(()=>window.__nadocTest.store.getState().currentDesign?.metadata?.namd_peg_coating?.spec?.repeat_units)).toBe(80)
 await page.uncheck('#md-peg-enable');await expect(page.locator('#md-peg-repeat_units')).toHaveValue('80')
 await page.check('#md-peg-enable')
 await page.locator('#md-peg-option').screenshot({path:info.outputPath('inline-peg-settings.png')})
 expect(libraryWrites).toEqual([])
 expect(await page.evaluate(()=>!!window.__nadocScene.getObjectByName('NAMD PEG coating graft preview')?.visible)).toBe(false)
})
test('inline PEG reports invalid layouts without discarding editable values',async({page})=>{
 await open(page,'__e2e__inline-peg-invalid');await page.check('#md-peg-enable')
 await page.fill('#md-peg-size_nm','2');await page.fill('#md-peg-density_per_nm2','0.000001')
 await expect(page.locator('#namd-peg-surfaces [role=status]')).toContainText('at least one chain')
 await expect(page.locator('#md-peg-size_nm')).toHaveValue('2')
})
