import { expect, test } from '@playwright/test'

test('conjugation schemes and standalone DNA work without overhangs', async ({ page }) => {
  test.setTimeout(180000)
  await page.route(/\/api\/(md|oxdna)\//, route => route.abort())
  await page.goto('/')
  await page.locator('.menu-item').filter({ hasText: 'File' }).first().hover()
  await page.click('#menu-file-new')
  await page.fill('#new-design-name', '__e2e__standalone_gold_sequence')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await page.waitForFunction(() => Boolean(window.__nadocTest?.nanoparticles))
  const open = () => page.evaluate(async () => window.__nadocTest.nanoparticles.conjugation.open(window.__nadocTest.store.getState().currentDesign.nanoparticles[0].id))
  await page.evaluate(() => window.__nadocTest.nanoparticles.create(10))
  await open()
  await expect(page.locator('#np-conj-overhangs')).toContainText('No overhangs yet')
  await expect(page.locator('#np-conj-scheme option')).toHaveCount(5)
  const thiolWindow = await page.locator('#nanoparticle-conjugate-overlay > div').boundingBox()
  await page.selectOption('#np-conj-scheme', 'streptavidin')
  await expect(page.locator('#strep-count')).toBeVisible()
  await page.fill('#strep-count', '1')
  await expect(page.locator('#np-conj-preview-census')).toContainText('10 nm gold · 1 strep · 0 DNA / strep', { timeout: 60000 })
  await expect(page.locator('#np-conjugate-preview canvas')).toBeVisible()
  expect(await page.locator('#nanoparticle-conjugate-overlay > div').boundingBox()).toEqual(thiolWindow)
  for (const id of ['strep-dna-create', 'strep-apply', 'strep-remove']) await expect(page.locator(`#${id}`)).toBeInViewport()
  await expect(page.locator('#strep-reference')).toHaveAttribute('title', /https:/)
  await expect(page.locator('#strep-source')).toBeHidden()
  await page.screenshot({path:'/tmp/nadoc-strep-manager.png'})
  await page.fill('#strep-dna-length', '12')
  await page.click('#strep-dna-generate')
  await expect(page.locator('#strep-dna-sequence')).toHaveValue(/^[ACGT]{12}$/)
  await page.selectOption('#np-conj-scheme', 'peg_thiol')
  await expect(page.locator('#np-conj-sequence')).toBeVisible()
  await page.fill('#np-conj-length', '12')
  await page.click('#np-conj-generate')
  await expect(page.locator('#np-conj-sequence')).toHaveValue(/^[ACGT]{12}$/)
  await page.click('#np-conj-create-handle')
  await page.click('#np-conj-apply')
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => window.__nadocTest.store.getState().currentDesign.strands.length)).toBe(1)
  await open()
  await page.fill('#np-conj-sequence', 'aaccttgg')
  await page.click('#np-conj-create-handle')
  await page.click('#np-conj-apply')
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => window.__nadocTest.store.getState().currentDesign.strands.map(s => s.sequence))).toEqual(['AACCTTGG'])
})
