import { expect, test } from '@playwright/test'

test('quantum-dot catalog imports vendor-sized particles and uses the gold movement controls', async ({ page }) => {
  test.setTimeout(120_000)
  await page.route(/\/api\/nanoparticles\/quantum-dots\/catalog/, route => route.abort())
  await page.route(/\/api\/(md|oxdna)\//, route => route.abort())
  await page.goto('/')
  await page.locator('.menu-item').filter({ hasText: 'File' }).first().hover()
  await page.click('#menu-file-new')
  await page.fill('#new-design-name', '__e2e__quantum_dot')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.locator('#welcome-screen')).not.toBeVisible()
  await page.waitForFunction(() => Boolean(window.__nadocTest?.nanoparticles))
  await expect(page.locator('#menu-item-tools')).not.toHaveClass(/disabled/)
  // Fluorescence also applies to dots imported while the mode is already on.
  await page.evaluate(() => document.getElementById('menu-view-fluorescence').click())
  await page.locator('#menu-item-tools > button').click()
  await page.locator('.submenu-item').filter({ has: page.locator('#menu-tools-quantum-dot') }).hover()
  await page.click('#menu-tools-quantum-dot')
  await expect(page.getByRole('dialog', { name: 'Quantum dots' })).toBeVisible()
  await expect(page.locator('#qd-rows tr')).toHaveCount(23)
  await page.locator('[data-catalog-id="thermo-qdot-655-streptavidin"]').click()
  await expect(page.locator('#qd-import')).toBeDisabled()
  await expect(page.locator('#qd-policy')).toContainText('not enabled yet')
  await page.locator('[data-catalog-id="nn-hecz-600"]').click()
  await page.waitForFunction(() => {
    const img = document.getElementById('qd-spectra')
    return img?.complete && img.naturalWidth > 100
  })
  await expect(page.locator('#qd-diameter')).toHaveValue('9.5')
  await expect(page.locator('#qd-diameter')).toBeInViewport({ ratio: 1 })
  await expect(page.locator('#qd-spectra')).toBeInViewport({ ratio: 1 })
  await page.screenshot({ path: '/tmp/nadoc-quantum-dot-catalog.png' })
  await page.click('#qd-import')
  await expect(page.locator('#quantum-dot-dialog')).toHaveCount(0, { timeout: 45_000 })
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.rendered().length)).toBe(1)
  const particle = await page.evaluate(() => window.__nadocTest.store.getState().currentDesign.nanoparticles[0])
  expect(particle.kind).toBe('quantum_dot')
  expect(particle.quantum_dot.product_code).toBe('HECZ600-10')
  expect(particle.quantum_dot.spectra.source_page).toBe(8)
  expect(particle.diameter_nm).toBe(9.5)
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.gizmoAttached())).toBe(true)
  await expect(page.locator('#mr-current-selection')).toContainText('Quantum dot')
  expect(await page.evaluate(() => window.__nadocTest.nanoparticles.rendered()[0].metalness)).toBe(0)

  await page.evaluate(() => document.getElementById('menu-edit-undo').click())
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.rendered().length), { timeout: 45_000 }).toBe(0)
  await expect(page.locator('#welcome-screen')).not.toBeVisible()
  await page.evaluate(() => document.getElementById('menu-edit-redo').click())
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.rendered().length)).toBe(1)
  await page.evaluate(id => window.__nadocTest.nanoparticles.select(id), particle.id)

  const appearance = () => page.evaluate(() => window.__nadocTest.nanoparticles.rendered()[0])
  const emissionColor = Number.parseInt(particle.quantum_dot.display_color.slice(1), 16)
  expect((await appearance()).fluorescence).toEqual([{ color: emissionColor, position: [0,0,0] }])
  expect((await appearance()).emissiveIntensity).toBe(1.5)

  // Preview then Cancel: the same shared panel and gizmo used by a gold sphere.
  await page.evaluate(() => window.__nadocTest.nanoparticles.gizmoSetTransform([5,2,-3], [0,0,0,1]))
  expect(await page.evaluate(() => window.__nadocTest.nanoparticles.rendered()[0].position)).toEqual([5,2,-3])
  expect((await appearance()).fluorescence[0].position).toEqual([5,2,-3])
  await page.evaluate(() => document.getElementById('menu-view-fluorescence').click())
  expect((await appearance()).fluorescence).toEqual([])
  expect((await appearance()).emissiveIntensity).toBe(0.5)
  expect((await appearance()).position).toEqual([5,2,-3])
  await page.evaluate(() => document.getElementById('menu-view-fluorescence').click())
  expect((await appearance()).fluorescence[0].position).toEqual([5,2,-3])
  await page.click('#mr-cancel-btn')
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.rendered()[0].position)).toEqual([0,0,0])
  await page.evaluate(id => window.__nadocTest.nanoparticles.select(id), particle.id)
  await page.evaluate(() => window.__nadocTest.nanoparticles.gizmoSetTransform([3,4,5], [0,0,0.6,0.8]))
  await page.evaluate(async () => (await import('/src/api/client.js')).ensureDefaultAnimation())
  expect(await page.evaluate(() => window.__nadocTest.nanoparticles.rendered()[0].position)).toEqual([3,4,5])
  await page.click('#mr-apply-btn')
  await expect.poll(() => page.evaluate(() => window.__nadocTest.store.getState().currentDesign.nanoparticles[0].pose.values.filter((_, i) => [3,7,11].includes(i)))).toEqual([3,4,5])
  expect(await page.evaluate(() => window.__nadocTest.store.getState().currentDesign.nanoparticle_conjugations)).toEqual([])

  // Every committed move starts from the newly committed pose, including after undo/redo.
  const position = () => page.evaluate(() => window.__nadocTest.nanoparticles.rendered()[0]?.position)
  await page.evaluate(() => window.__nadocTest.nanoparticles.gizmoSetTransform([1,0,0], [0,0,0.6,0.8]))
  await expect.poll(position).toEqual([4,4,5])
  await page.click('#mr-apply-btn')
  await expect.poll(() => page.evaluate(() => window.__nadocTest.store.getState().currentDesign.nanoparticles[0].pose.values[3])).toBe(4)
  await page.evaluate(() => document.getElementById('menu-edit-undo').click())
  await expect.poll(position).toEqual([3,4,5])
  await expect(page.locator('#welcome-screen')).not.toBeVisible()
  await page.evaluate(() => document.getElementById('menu-edit-redo').click())
  await expect.poll(position).toEqual([4,4,5])
  await page.evaluate(() => window.__nadocTest.nanoparticles.gizmoSetTransform([0,1,0], [0,0,0,1]))
  await expect.poll(position).toEqual([4,5,5])
  await page.click('#mr-cancel-btn')
  await expect.poll(position).toEqual([4,4,5])
  expect((await appearance()).fluorescence).toEqual([{ color: emissionColor, position: [4,4,5] }])
  const entries = await page.evaluate(() => window.__nadocTest.store.getState().currentDesign.feature_log)
  expect(entries.map(e => e.op_kind)).toEqual(['nanoparticle-create', 'nanoparticle-patch', 'nanoparticle-patch'])
  const editDiameter = page.locator('#feature-log-panel-body button[title="Edit scene diameter (currently 9.5 nm)"]')
  await expect(editDiameter).toBeEnabled()

  // Dot selection still works through scene raycasting, not just the import callback.
  await page.evaluate(() => window.__nadocTest.applyCameraPoseForTest({ position:[20,14,25], target:[3,4,5] }))
  const point = await page.evaluate(id => window.__nadocTest.nanoparticles.screenPosition(id), particle.id)
  expect(await page.evaluate(p => window.__nadocTest.nanoparticles.hitAt(p), point)).toMatchObject({ id:particle.id })
  await page.evaluate(id => window.__nadocTest.nanoparticles.select(id), particle.id)
  await page.locator('body').click({ position: { x: 1, y: 1 } })
  await page.keyboard.press('Delete')
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.rendered().length), { timeout: 45_000 }).toBe(0)
  await page.evaluate(() => document.getElementById('menu-edit-undo').click())
  await expect.poll(position).toEqual([4,4,5])
  await page.evaluate(() => document.getElementById('menu-edit-redo').click())
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.rendered().length), { timeout: 45_000 }).toBe(0)
})
