import { test, expect } from '@playwright/test'
import { loadScaffoldedPart, trackConsoleErrors } from './helpers/scene_harness.js'

const control = (column, id) => column.locator(`#${id}, [data-sidebar-source-id="${id}"]`)

test('right side stacks inward with shared controls and independent widths', async ({ page }, testInfo) => {
  test.setTimeout(120_000)
  await page.setViewportSize({ width: 2200, height: 1000 })
  const errors = trackConsoleErrors(page)
  await loadScaffoldedPart(page, { doc: '__e2e__right-sidebar-stack', name: 'right-sidebar-stack' })
  await page.keyboard.press('f')
  const rail = page.locator('#right-tab-strip')
  await rail.locator('[data-tab="visualization"]').click()
  await rail.locator('[data-tab="visualization"]').click()
  const copies = page.locator('#right-panel .sidebar-column[data-panel-type="visualization"]')
  await expect(copies).toHaveCount(2)
  await copies.nth(1).getByRole('button', { name: 'Cylinders', exact: true }).click()
  await expect(page.locator('#menu-view-detail-cylinders')).toHaveClass(/is-checked/)
  await expect(copies.nth(0).getByRole('button', { name: 'Cylinders', exact: true })).toHaveClass(/active/)
  if (!await control(copies.nth(1), 'slab-body').isVisible()) await control(copies.nth(1), 'slab-heading').click()
  const range = control(copies.nth(1), 'sl-cyl-radius')
  await range.hover(); await range.focus()
  await page.keyboard.press('ArrowRight')
  await expect(control(copies.nth(0), 'sl-cyl-radius')).toHaveValue(await range.inputValue())
  const firstBody = copies.nth(0).locator('.sidebar-column-body')
  const secondBody = copies.nth(1).locator('.sidebar-column-body')
  await firstBody.hover({ position: { x: 100, y: 100 } }); await page.mouse.wheel(0, 250)
  await expect.poll(() => firstBody.evaluate(e => e.scrollTop)).toBeGreaterThan(0)
  const firstScroll = await firstBody.evaluate(e => e.scrollTop)
  await secondBody.hover({ position: { x: 100, y: 100 } }); await page.mouse.wheel(0, 500)
  expect(await firstBody.evaluate(e => e.scrollTop)).toBe(firstScroll)
  const before = await copies.evaluateAll(es => es.map(e => e.getBoundingClientRect().width))
  const handle = await copies.nth(1).locator('.sidebar-column-resize').boundingBox()
  await page.mouse.move(handle.x + 2, handle.y + 100); await page.mouse.down()
  await page.mouse.move(handle.x - 48, handle.y + 100); await page.mouse.up()
  const after = await copies.evaluateAll(es => es.map(e => e.getBoundingClientRect().width))
  expect(after[0]).toBe(before[0]); expect(after[1]).toBeGreaterThan(before[1])
  await page.locator('#left-tab-strip [data-tab="scene"]').click()
  await rail.locator('[data-tab="overhangs"]').click()
  await page.screenshot({ path: testInfo.outputPath('right-sidebar-stack.png') })
  const bounds = await page.evaluate(() => {
    const rect = id => document.getElementById(id).getBoundingClientRect()
    return { rail: rect('right-tab-strip').right, stack: rect('right-panel').left, viewport: rect('viewport-container').width }
  })
  expect(Math.abs(bounds.rail - bounds.stack)).toBeLessThan(2)
  expect(bounds.viewport).toBeGreaterThanOrEqual(319)
  for (let i = 0; i < 8; i++) await rail.locator('[data-tab="clustering"]').click()
  await expect(rail.locator('.sidebar-space-notice')).toContainText('No room')
  expect(await page.locator('#viewport-container').evaluate(e => e.getBoundingClientRect().width)).toBeGreaterThanOrEqual(319)
  await copies.nth(1).locator('.sidebar-close').click()
  await expect(copies).toHaveCount(1)
  await rail.locator('#right-tab-toggle').click(); await rail.locator('#right-tab-toggle').click()
  await expect(page.locator('#menu-view-detail-cylinders')).toHaveClass(/is-checked/)
  expect(errors, errors.join('\n')).toEqual([])
})
