import { expect, test } from '@playwright/test'

test('PDB streptavidin coating follows particle movement and survives history', async ({ page }) => {
  test.setTimeout(180_000)
  await page.route(/\/api\/(md|oxdna)\//, route => route.abort())
  await page.goto('/')
  await page.locator('.menu-item').filter({ hasText: 'File' }).first().hover()
  await page.click('#menu-file-new')
  await page.fill('#new-design-name', '__e2e__streptavidin')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.locator('#welcome-screen')).not.toBeVisible()
  await page.waitForFunction(() => Boolean(window.__nadocTest?.nanoparticles))
  await expect(page.locator('#menu-item-tools')).not.toHaveClass(/disabled/)
  await page.locator('#menu-item-tools > button').click()
  await page.locator('.submenu-item').filter({ has: page.locator('#menu-tools-gold-nanosphere') }).hover()
  await page.click('#menu-tools-gold-nanosphere')
  await page.fill('#gold-diameter', '10')
  await expect(page.locator('#gold-coating')).toHaveCount(0)
  await page.click('#gold-create')
  await expect(page.locator('#gold-creation-dialog')).toHaveCount(0, { timeout: 60_000 })
  await page.evaluate(async () => {
    const id = window.__nadocTest.store.getState().currentDesign.nanoparticles[0].id
    await window.__nadocTest.nanoparticles.conjugation.open(id)
  })
  await page.selectOption('#np-conj-scheme', 'streptavidin')
  await expect(page.locator('#np-conj-scheme')).toBeInViewport()
  expect(await page.locator('#streptavidin-dialog').evaluate(el => getComputedStyle(el).position)).toBe('static')
  await page.selectOption('#strep-reference', 'gurtovenko_2019')
  await expect(page.locator('#strep-count')).toHaveValue('6')
  await page.fill('#strep-count', '7')
  await expect(page.locator('#strep-estimate')).toContainText('(override)')
  await page.screenshot({ path: '/tmp/nadoc-strep-manager.png' })
  await page.click('#strep-apply')
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toHaveCount(0, { timeout: 60_000 })
  const rendered = () => page.evaluate(() => window.__nadocTest.nanoparticles.rendered()[0])
  await expect.poll(async () => (await rendered())?.coating?.count, { timeout: 60_000 }).toBe(7)
  const initial = await rendered()
  expect(initial.coating.chains).toBe(4)
  await page.evaluate(() => window.__nadocTest.applyCameraPoseForTest({ position: [23,17,26], target: [0,0,0] }))
  await page.screenshot({ path: '/tmp/nadoc-streptavidin.png' })
  await page.evaluate(() => window.__nadocTest.nanoparticles.gizmoSetTransform([3,4,5], [0,0,0,1]))
  const preview = await rendered()
  preview.coating.firstPosition.forEach((value, i) => expect(value - initial.coating.firstPosition[i]).toBeCloseTo([3,4,5][i], 5))
  await page.click('#mr-cancel-btn')
  await expect.poll(async () => (await rendered()).position).toEqual([0,0,0])
  await page.evaluate(id => window.__nadocTest.nanoparticles.select(id), initial.id)
  await page.evaluate(() => window.__nadocTest.nanoparticles.gizmoSetTransform([3,4,5], [0,0,0,1]))
  await page.click('#mr-apply-btn')
  await expect.poll(() => page.evaluate(() => window.__nadocTest.store.getState().currentDesign.nanoparticles[0].pose.values[3]), { timeout: 60_000 }).toBe(3)
  await page.evaluate(() => document.getElementById('menu-edit-undo').click())
  await expect.poll(async () => (await rendered()).position).toEqual([0,0,0])
  await page.evaluate(() => document.getElementById('menu-edit-redo').click())
  await expect.poll(async () => (await rendered()).position).toEqual([3,4,5])
  await page.evaluate(async id => {
    const { openStreptavidinDialog } = await import('/src/ui/streptavidin_dialog.js')
    openStreptavidinDialog(window.__nadocTest.store.getState().currentDesign.nanoparticles.find(p => p.id === id))
  }, initial.id)
  await expect(page.locator('#strep-size')).toContainText('7 tetramers')
  await page.click('#strep-remove')
  await expect.poll(async () => (await rendered()).coating, { timeout: 60_000 }).toBeNull()
  await page.evaluate(() => document.getElementById('menu-edit-undo').click())
  await expect.poll(async () => (await rendered()).coating?.count).toBe(7)
  await page.evaluate(id => window.__nadocTest.nanoparticles.resize(id, 20), initial.id)
  await expect.poll(async () => (await rendered()).coating?.count, { timeout: 60_000 }).toBe(7)
})
