import { expect, test } from '@playwright/test'

async function clickIntegerArrows(page, id, initial) {
  const input = page.locator(`#${id}`)
  await input.fill(String(initial))
  const box = await input.boundingBox()
  // Click the browser's visible native up/down arrows, not a scripted stepUp.
  await input.click({ position: { x: box.width - 14, y: box.height * .35 } })
  await expect(input).toHaveValue(String(initial + 1))
  await input.click({ position: { x: box.width - 14, y: box.height * .65 } })
  await expect(input).toHaveValue(String(initial))
}

test('apply coating before attaching an exact DNA count per strep, preview, undo and redo', async ({ page }) => {
  test.setTimeout(180000)
  await page.goto('/')
  await page.locator('.menu-item').filter({ hasText: 'File' }).first().hover()
  await page.click('#menu-file-new')
  await page.fill('#new-design-name', '__e2e__strep_DNA_occupancy')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await page.waitForFunction(() => Boolean(window.__nadocTest?.nanoparticles))
  const reopen = () => page.evaluate(async () => {
    const t = window.__nadocTest
    await t.nanoparticles.conjugation.open(t.store.getState().currentDesign.nanoparticles[0].id)
  })
  await page.evaluate(async () => window.__nadocTest.nanoparticles.create(10))
  await reopen()
  await clickIntegerArrows(page, 'np-conj-length', 16)
  await clickIntegerArrows(page, 'np-conj-count', 1)
  await page.selectOption('#np-conj-scheme', 'streptavidin')
  const leftBox = await page.locator('.strep-coating-controls').boundingBox()
  const previewBox = await page.locator('#np-conjugate-preview').boundingBox()
  const rightBox = await page.locator('.strep-dna-controls').boundingBox()
  expect(leftBox.x + leftBox.width).toBeLessThan(previewBox.x)
  expect(previewBox.x + previewBox.width).toBeLessThan(rightBox.x)
  await expect(page.locator('.strep-coating-controls > button').last()).toHaveText('Remove coating')
  await expect(page.locator('.strep-dna-controls .strep-actions button').last()).toHaveText('Apply')
  await expect(page.locator('#strep-dna-count')).toBeDisabled()
  await expect(page.locator('#strep-dna-create')).toBeDisabled()
  await page.fill('#strep-count', '3')
  await page.click('#strep-apply')
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toHaveCount(0, { timeout: 60000 })
  await reopen()
  await expect(page.locator('#strep-dna-create')).toBeEnabled()
  await clickIntegerArrows(page, 'strep-count', 3)
  await clickIntegerArrows(page, 'strep-dna-length', 16)
  await clickIntegerArrows(page, 'strep-dna-count', 1)
  const lengthBox = await page.locator('#strep-dna-length').boundingBox()
  const generateBox = await page.locator('#strep-dna-generate').boundingBox()
  expect(Math.abs(lengthBox.y + lengthBox.height - generateBox.y - generateBox.height)).toBeLessThan(2)
  await expect(page.locator('.strep-length-row label')).toHaveText('Length')
  expect(await page.locator('.strep-dna-controls').evaluate(n => n.scrollHeight <= n.clientHeight + 1)).toBe(true)
  await page.locator('#nanoparticle-conjugate-overlay > div').screenshot({ path: '/tmp/nadoc-integer-spinners.png' })
  await page.fill('#strep-count', '4')
  await expect(page.locator('#strep-dna-create')).toBeDisabled()
  await page.fill('#strep-count', '3')
  await expect(page.locator('#strep-dna-create')).toBeEnabled()
  await page.fill('#strep-dna-count', '2')
  await expect(page.locator('#strep-dna-pocket')).toBeDisabled()
  await expect(page.locator('#strep-dna-current')).toContainText('6 DNA requested')
  await page.fill('#strep-dna-length', '16')
  await page.click('#strep-dna-generate')
  await expect(page.locator('#strep-dna-sequence')).toHaveValue(/^[ACGT]{16}$/)
  const responsePromise = page.waitForResponse(r => r.url().endsWith('/biotin-dna') && r.request().method() === 'POST')
  await page.click('#strep-dna-create')
  const response = await responsePromise
  expect(response.status(), await response.text()).toBe(200)
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toBeVisible()
  const occupancy = () => page.evaluate(() => {
    const d = window.__nadocTest.store.getState().currentDesign, p = d.nanoparticles[0]
    return { strep: p.coating.poses.length, strands: d.strands.length, occupancy: p.coating.poses.map((_, i) => p.biotin_dna.filter(r => (r.tetramer_index ?? 0) === i).length) }
  })
  await expect.poll(occupancy).toEqual({ strep: 3, strands: 6, occupancy: [2,2,2] })
  await expect(page.locator('#np-conj-preview-census')).toContainText('3 strep · 2 DNA / strep')
  await expect(page.locator('#np-conjugate-preview canvas')).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.__nadocTest.nanoparticles.conjugation.strepDnaPreview().map(p => p.nucleotideCount))).toEqual([16,16,16,16,16,16])
  await expect(page.locator('#strep-dna-create')).toBeDisabled()
  await expect(page.locator('#strep-apply')).toBeEnabled()
  await page.click('#strep-apply')
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toHaveCount(0)
  await page.evaluate(() => document.getElementById('menu-edit-undo').click())
  await expect.poll(occupancy).toEqual({ strep: 3, strands: 0, occupancy: [0,0,0] })
  await page.evaluate(() => document.getElementById('menu-edit-redo').click())
  await expect.poll(occupancy).toEqual({ strep: 3, strands: 6, occupancy: [2,2,2] })
  await reopen()
  await page.click('#strep-dna-remove')
  await expect(page.locator('#strep-dna-current')).toContainText('DNA requested')
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toBeVisible()
  await expect(page.locator('#np-conj-preview-census')).toContainText('3 strep · 0 DNA / strep')
  await expect.poll(occupancy).toEqual({ strep: 3, strands: 0, occupancy: [0,0,0] })
  await page.click('#strep-apply')
  await expect(page.locator('#nanoparticle-conjugate-overlay')).toHaveCount(0)
})
