import { test, expect } from '@playwright/test'
import path from 'node:path'

test('Sweep direction, twist and advisory curvature survive desktop editing and history', async ({ page }) => {
  test.setTimeout(90_000)
  await page.setViewportSize({width:1600,height:1000})
  await page.goto('/?test=1&doc=__e2e__sweep-orientation')
  await expect(page.locator('#canvas')).toBeVisible()
  await page.locator('.menu-item').filter({hasText:'File'}).first().hover()
  await page.click('#menu-file-new')
  await page.fill('#new-design-name','__e2e__Sweep orientation')
  await page.getByRole('button',{name:'Create',exact:true}).click()
  await page.locator('.menu-item').filter({hasText:'Tools'}).first().hover()
  await page.click('#menu-tools-sweep')
  await page.evaluate(() => window.SLICE.setSelectedCells(Array.from({length:9},(_,i)=>[0,i])))
  await expect(page.locator('#sweep-apply')).toBeEnabled()
  await page.getByRole('button',{name:'Next',exact:true}).click()
  await page.getByRole('spinbutton',{name:'Point Z (nm)'}).fill('5')
  await page.getByRole('button',{name:'Add sweep point'}).click()
  await page.getByRole('spinbutton',{name:'Point X (nm)'}).fill('5')
  await page.getByRole('spinbutton',{name:'Point Z (nm)'}).fill('5')
  await expect(page.locator('#sweep-apply')).toBeEnabled()
  await page.getByRole('checkbox',{name:'Control point orientation'}).check()
  for(const [name,value] of [['Tilt X (degrees)','0'],['Tilt Y (degrees)','90'],['Twist (degrees)','43']]) {
    await page.getByRole('spinbutton',{name,exact:true}).fill(value)
    await page.getByRole('spinbutton',{name,exact:true}).press('Tab')
  }
  await expect(page.getByRole('spinbutton',{name:'Twist (degrees)',exact:true})).toHaveValue('43')
  await expect(page.locator('#sweep-status')).toContainText('Warning')
  await expect(page.locator('#sweep-apply')).toBeEnabled()
  await page.evaluate(() => window.__nadocTest.applyCameraPoseForTest({position:[30,20,48],target:[-8,0,5]}))
  const hoverWarning=async()=>{
    await expect.poll(()=>page.evaluate(()=>window.__nadocTest.getSweepScreenPositions().warnings.length)).toBeGreaterThan(0)
    const warning=await page.evaluate(()=>window.__nadocTest.getSweepScreenPositions().warnings[0])
    await page.mouse.move(warning.x,warning.y)
    await expect(page.getByRole('tooltip',{name:''}).filter({hasText:'Loop/skip limit is exceeded'}).first()).toBeVisible()
  }
  await hoverWarning()
  await page.screenshot({path:path.resolve(import.meta.dirname,'../../.development-artifacts/sweep-orientation-warning.png')})
  await page.click('#sweep-apply')
  await expect(page.locator('#sweep-panel')).not.toBeVisible().catch(async e => { console.log('Sweep status:',await page.locator('#sweep-status').textContent()); throw e })
  const orientations=()=>page.evaluate(async()=> (await import('/src/state/store.js')).store.getState().currentDesign.feature_log[0].params.orientations_deg)
  expect(await orientations()).toEqual([null,null,[0,90,43]])
  await hoverWarning()
  await page.screenshot({path:path.resolve(import.meta.dirname,'../../.development-artifacts/sweep-created-warning.png')})
  await page.locator('#feature-log-panel-body [data-fl-row="1"]').getByRole('button',{name:'✎'}).click()
  await page.getByRole('option',{name:/Point 2/}).click()
  await expect(page.getByRole('checkbox',{name:'Control point orientation'})).toBeChecked()
  await expect(page.getByRole('spinbutton',{name:'Twist (degrees)',exact:true})).toHaveValue('43')
  await page.getByRole('spinbutton',{name:'Twist (degrees)',exact:true}).fill('90')
  await page.getByRole('spinbutton',{name:'Twist (degrees)',exact:true}).press('Tab')
  await expect(page.locator('#sweep-apply')).toBeEnabled()
  await page.click('#sweep-apply')
  await expect(page.locator('#sweep-panel')).not.toBeVisible().catch(async e => { console.log('Sweep status:',await page.locator('#sweep-status').textContent()); throw e })
  expect((await orientations())[2]).toEqual([0,90,90])
  await page.evaluate(async()=> (await import('/src/api/client.js')).undo())
  expect((await orientations())[2]).toEqual([0,90,43])
  await page.evaluate(async()=> (await import('/src/api/client.js')).redo())
  expect((await orientations())[2]).toEqual([0,90,90])
})

test('Sweep Tab rotates freely while position display and BP total retain precision', async ({page}) => {
  await page.setViewportSize({width:1600,height:1000})
  await page.goto('/?test=1&doc=__e2e__sweep-refinement')
  await page.locator('.menu-item').filter({hasText:'File'}).first().hover()
  await page.click('#menu-file-new'); await page.fill('#new-design-name','__e2e__Sweep refinement')
  await page.getByRole('button',{name:'Create',exact:true}).click()
  await page.locator('.menu-item').filter({hasText:'Tools'}).first().hover()
  await page.click('#menu-tools-sweep')
  await page.evaluate(()=>window.SLICE.setSelectedCells([[0,0],[0,1],[1,0]]))
  await expect(page.locator('#sweep-apply')).toBeEnabled()
  await page.getByRole('button',{name:'Next',exact:true}).click()
  const x=page.getByRole('spinbutton',{name:'Point X (nm)'})
  await x.fill('1.239876'); await x.press('Tab')
  await expect(x).toHaveValue('1.23')
  await expect(page.getByRole('option',{name:/Point 1/})).toContainText('1.23')
  const fonts=await page.evaluate(()=>[document.querySelector('.sweep-point'),document.querySelector('.sweep-coordinates input')].map(e=>{const s=getComputedStyle(e);return [s.fontSize,s.fontFamily,s.fontWeight]}))
  expect(fonts[0]).toEqual(fonts[1])
  await expect(page.locator('#sweep-point-editor .tool-help')).toHaveCount(0)
  await expect(page.locator('#sweep-apply')).toBeEnabled()
  await expect(page.locator('#sweep-total-bp')).toHaveText(/^\d[\d,]*$/)
  await page.evaluate(()=>window.__nadocTest.applyCameraPoseForTest({position:[20,16,40],target:[0,0,5]}))
  await page.getByRole('option',{name:/Point 1/}).click()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('checkbox',{name:'Control point orientation'})).toBeChecked()
  await expect.poll(()=>page.evaluate(()=>window.__nadocTest.getSweepScreenPositions().mode)).toBe('rotate')
  const before=await page.locator('#sweep-point-editor input[type=number]').evaluateAll(es=>es.slice(0,3).map(e=>e.value))
  const anglesBefore=await page.locator('.sweep-orientation input').evaluateAll(es=>es.map(e=>Number(e.value)))
  const info=await page.evaluate(()=>window.__nadocTest.getSweepScreenPositions())
  expect(info.sections).toBe(2)
  const center=info.points[1], ring=info.rings.filter(r=>r.name==='Z' && r.x>400).sort((a,b)=>b.x-a.x)[0]
  expect(ring).toBeTruthy()
  await page.mouse.move(ring.x,ring.y); await page.mouse.down()
  const dx=ring.x-center.x,dy=ring.y-center.y,a=.31
  await page.mouse.move(center.x+dx*Math.cos(a)-dy*Math.sin(a),center.y+dx*Math.sin(a)+dy*Math.cos(a),{steps:12})
  await page.mouse.up()
  await expect(page.locator('#sweep-apply')).toBeEnabled()
  const angles=await page.locator('.sweep-orientation input').evaluateAll(es=>es.map(e=>Number(e.value)))
  expect(angles.some((a,i)=>Math.abs(a-anglesBefore[i])>1)).toBe(true)
  expect(angles.some(a=>Math.abs(a/15-Math.round(a/15))>.01)).toBe(true)
  expect(await page.locator('#sweep-point-editor input[type=number]').evaluateAll(es=>es.slice(0,3).map(e=>e.value))).toEqual(before)
  await page.screenshot({path:path.resolve(import.meta.dirname,'../../.development-artifacts/sweep-refined-controls.png')})
  await page.locator('#canvas').focus(); await page.keyboard.press('Tab')
  await expect.poll(()=>page.evaluate(()=>window.__nadocTest.getSweepScreenPositions().mode)).toBe('translate')
  const total=Number((await page.locator('#sweep-total-bp').textContent()).replaceAll(',',''))
  await page.click('#sweep-apply'); await expect(page.locator('#sweep-panel')).not.toBeVisible()
  const design=await page.evaluate(async()=>(await import('/src/state/store.js')).store.getState().currentDesign)
  expect(design.feature_log[0].params.points_nm[1][0]).toBe(1.239876)
  expect(design.helices.reduce((sum,h)=>sum+h.length_bp,0)).toBe(total)
})
