import { test, expect } from '@playwright/test'

test('VR routing controls use desktop operations and preserve Undo/Redo', async ({ page }) => {
  test.setTimeout(180000)
  await page.goto('/?doc=__e2e__vr-routing')
  await page.locator('.menu-item').filter({ hasText: 'File' }).first().hover()
  await page.click('#menu-file-new')
  await page.fill('#new-design-name', '__e2e__VR Routing')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await page.evaluate(async () => {
    const api = await import('/src/api/client.js')
    await api.createBundle({ cells: [[0,0], [1,0], [0,1], [1,1]], lengthBp: 84, plane:'XY', name:'__e2e__Route' })
    const { createVRRouting } = await import('/src/scene/vr_routing.js')
    window.routingTest = { sequence:0, requests:[] }; window.addEventListener('nadoc:api-request', e => window.routingTest.requests.push(e.detail))
    window.routingTest.bridge = createVRRouting({ request: async (_, opts) => { window.routingTest.wire = JSON.parse(opts.body); return { ok:true } } })
  })
  const click = async id => page.evaluate(async id => {
    const t = window.routingTest
    await t.bridge.publish()
    const row = [...t.wire.roots,...t.wire.controls].find(row => row.id === id)
    if (!row?.enabled) throw new Error(`Unavailable VR action ${id}: ${JSON.stringify({wire:t.wire, requests:t.requests, progress:document.querySelector('#op-progress')?.className})}`)
    await t.bridge.activate({ sequence:++t.sequence, version:t.wire.version, id })
  }, id)
  const choice = async label => {
    const id = await page.evaluate(label => window.routingTest.bridge.snapshot().controls.find(c => c.label === label)?.id, label)
    expect(id).toBeTruthy(); await click(id)
  }
  const ready = () => expect.poll(() => page.evaluate(() => window.routingTest.bridge.snapshot().controls.some(c => c.id === 'dismiss' && c.enabled)), {timeout:60000}).toBe(true)
  const design = () => page.evaluate(async () => (await import('/src/state/store.js')).store.getState().currentDesign)
  const before = await design()
  await click('menu-routing-scaffold-ends');await choice('Run');await ready()
  const routed = await design()
  expect(routed.strands, JSON.stringify(await page.evaluate(() => window.routingTest.bridge.snapshot().controls))).not.toEqual(before.strands)
  await click('menu-edit-undo');await ready()
  expect((await design()).strands).toEqual(before.strands)
  await click('menu-edit-redo');await ready()
  expect((await design()).strands).toEqual(routed.strands)
  await click('dismiss');await click('menu-seq-assign-scaffold')
  await click('custom-sequence')
  for (const base of ['a','c','g','t']) await click(`key-${base}`)
  await click('key-done');await choice('Apply');await ready()
  const sequenced = await design()
  expect(sequenced.strands).not.toEqual(routed.strands)
  await click('menu-edit-undo');await ready();expect((await design()).strands).toEqual(routed.strands)
  await click('menu-edit-redo');await ready();expect((await design()).strands).toEqual(sequenced.strands)
  await click('dismiss');await click('menu-seq-clear-all-loop-skips');await choice('Cancel')
  expect(await page.evaluate(() => window.routingTest.bridge.snapshot().title)).toBe('')
  expect((await design()).strands).toEqual(sequenced.strands)
  await click('menu-seq-assign-staples');await ready()
  const staples = await design()
  expect(staples.strands.some(s => s.strand_type === 'staple' && s.sequence)).toBe(true)
  await click('menu-edit-undo');await ready();expect((await design()).strands).toEqual(sequenced.strands)
  await click('dismiss')
  await page.evaluate(async () => {
    const api = await import('/src/api/client.js')
    const { store } = await import('/src/state/store.js')
    await api.insertLoopSkip(store.getState().currentDesign.helices[0].id, 10, 1)
  })
  const loops = await design()
  expect(loops.helices.some(h => h.loop_skips.length)).toBe(true)
  await click('menu-seq-clear-all-loop-skips');await choice('Clear all');await ready()
  expect((await design()).helices.every(h => !h.loop_skips.length)).toBe(true)
  await click('menu-edit-undo');await ready();expect((await design()).helices).toEqual(loops.helices)
  await click('dismiss')
  for (const id of ['menu-routing-full-autostaple', 'menu-routing-polymerization']) {
    const previous = await design()
    await click(id);await ready()
    const changed = await design()
    expect(changed.feature_log.length, id).toBeGreaterThan(previous.feature_log.length)
    await click('menu-edit-undo');await ready()
    expect((await design()).strands, id).toEqual(previous.strands)
    await click('dismiss')
  }
  await click('menu-seq-generate-overhangs');await ready()
  expect(await page.evaluate(() => window.routingTest.bridge.snapshot().controls.some(c => c.label.includes('No overhangs found')))).toBe(true)
  await click('dismiss');await click('menu-seq-update-routing');await ready()
  expect(await page.evaluate(() => window.routingTest.bridge.snapshot().controls.some(c => c.label.includes('No deformation ops')))).toBe(true)
  await click('dismiss');await click('menu-seq-hairpin-dimer');await ready()
  expect(await page.evaluate(() => window.routingTest.bridge.snapshot().roots.find(c => c.id === 'menu-seq-hairpin-dimer').active)).toBe(true)
  await click('dismiss');await click('menu-seq-hairpin-dimer');await ready()
  expect(await page.evaluate(() => window.routingTest.bridge.snapshot().roots.find(c => c.id === 'menu-seq-hairpin-dimer').active)).toBe(false)
  await click('dismiss')
  await page.evaluate(async () => {
    const api = await import('/src/api/client.js')
    const { store } = await import('/src/state/store.js')
    const helix = store.getState().currentDesign.helices[0]
    await api.extrudeOverhang({helixId:helix.id,bpIndex:0,direction:'REVERSE',isFivePrime:false,neighborRow:0,neighborCol:-1,lengthBp:7})
  })
  const overhangs = (await design()).overhangs
  expect(overhangs.length).toBeGreaterThan(0)
  await click('menu-seq-generate-overhangs');await ready()
  expect((await design()).overhangs).not.toEqual(overhangs)
  await click('menu-edit-undo');await ready();expect((await design()).overhangs).toEqual(overhangs)
  await click('dismiss')
  await page.evaluate(async () => {
    const api = await import('/src/api/client.js')
    await api.createDesign('__e2e__Square Loops', 'SQUARE')
    await api.createBundle({cells:[[0,0],[1,0],[0,1],[1,1]],lengthBp:84,plane:'XY',latticeType:'SQUARE',name:'__e2e__Square'})
    await api.autoScaffoldSeamed()
  })
  const square = await design()
  await click('menu-seq-update-routing');await ready()
  expect((await design()).helices.some(h=>h.loop_skips.length)).toBe(true)
  await click('menu-edit-undo');await ready();expect((await design()).helices).toEqual(square.helices)
  await page.evaluate(() => window.routingTest.bridge.dispose())
})
