import { test, expect } from '@playwright/test'

// No files/design mutations or native processes; cleanup reporter removes traces.
test('Debug flyouts launch visualization directly and retain descriptions as tooltips', async ({ page }) => {
  await page.goto('/?doc=e2e-vr-tour-menu')
  await page.locator('#menu-item-debug > button').click()
  await page.locator('#menu-debug-vr-tours').hover()
  const right = page.locator('[data-category=right]')
  await right.hover()
  const demo = right.locator('[data-start=representations][data-mode=demo]')
  await expect(right.locator('[data-start=representation-colors][data-mode=demo]')).toHaveText('Representation colors demo')
  await expect(demo).toBeVisible()
  await expect(demo).toHaveText('Visualization demo')
  await expect(demo).toHaveAttribute('title', /open design/)
  await expect(page.getByRole('dialog', {name:'VR Tours & Tests'})).toHaveCount(0)
  await page.route('**/api/vr/tours/start', route => route.fulfill({json:{detail:'Open a design before starting the visualization demo.'},status:400}))
  const requested = page.waitForRequest(request => request.url().endsWith('/api/vr/tours/start'))
  await demo.click()
  expect((await requested).postDataJSON()).toEqual({tour:'representations',mode:'demo',assembly_active:false})
  await expect(page.getByText('Open a design before starting the visualization demo.').first()).toBeVisible()
})

test('View Volumes exposes corresponding demo and ScryWrite validation launchers', async ({ page }) => {
  await page.goto('/?doc=e2e-view-volume-tour-menu')
  await page.locator('#menu-item-debug > button').click()
  await page.locator('#menu-debug-vr-tours').hover()
  const group=page.locator('[data-category="view-volumes"]')
  await group.hover()
  const demo=group.locator('[data-start="view-volumes"][data-mode="demo"]')
  const validation=group.locator('[data-start="view-volumes"][data-mode="validate"]')
  await expect(demo).toBeVisible()
  await expect(validation).toHaveText('View volumes validation')
  await expect(demo).toHaveAttribute('title', /Isolated demo part/)
  await page.route('**/api/vr/tours/start', route => route.fulfill({json:{run:{id:'mock-volume-tour',tour:'view-volumes',status:'running',output:'test-only'}}}))
  await page.route('**/api/vr/tours/status', route => route.fulfill({json:{run:{id:'mock-volume-tour',tour:'view-volumes',status:'running',output:'test-only'}}}))
  const requested=page.waitForRequest(request=>request.url().endsWith('/api/vr/tours/start'))
  await demo.click()
  expect((await requested).postDataJSON()).toEqual({tour:'view-volumes',mode:'demo'})
})

test('fresh-part Extrude tour offers demo and four-profile validation', async ({page}) => {
  await page.goto('/?doc=e2e-extrude-tour-menu')
  await page.locator('#menu-item-debug > button').click()
  await page.locator('#menu-debug-vr-tours').hover()
  const group=page.locator('[data-category="authoring"]')
  await group.hover()
  const demo=group.locator('[data-start="extrude"][data-mode="demo"]')
  const validation=group.locator('[data-start="extrude"][data-mode="validate"]')
  await expect(demo).toBeVisible()
  await expect(validation).toBeVisible()
  await expect(demo).toHaveAttribute('title',/new isolated part/)
  await page.route('**/api/vr/tours/start',route=>route.fulfill({json:{run:{id:'mock-extrude-tour',tour:'extrude',status:'running',output:'test-only'}}}))
  await page.route('**/api/vr/tours/status',route=>route.fulfill({json:{run:{id:'mock-extrude-tour',tour:'extrude',status:'running',output:'test-only'}}}))
  const requested=page.waitForRequest(request=>request.url().endsWith('/api/vr/tours/start'))
  await validation.click()
  expect((await requested).postDataJSON()).toEqual({tour:'extrude',mode:'validate'})
})
